-- Table definitions + constraints: audios_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: audios_resource; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audios_resource (
    id uuid DEFAULT uuidv7() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    name text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--

-- Name: audios_resource audios_resource_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audios_resource
    ADD CONSTRAINT audios_resource_pkey PRIMARY KEY (id);


--
