-- Table definitions + constraints: logins_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: logins_resource; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.logins_resource (
    id uuid DEFAULT uuidv7() NOT NULL,
    profile_id uuid,
    auth_id uuid,
    icon_id uuid,
    display_name text DEFAULT '' NOT NULL,
    login_type text DEFAULT 'auth' NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--

-- Name: logins_resource logins_resource_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.logins_resource
    ADD CONSTRAINT logins_resource_pkey PRIMARY KEY (id);


--
