-- Table definitions + constraints: mcp_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: mcp_resource; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mcp_resource (
    id uuid DEFAULT uuidv7() NOT NULL,
    agent_id uuid NOT NULL,
    name text DEFAULT ''::text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--

-- Name: mcp_resource mcp_resource_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mcp_resource
    ADD CONSTRAINT mcp_resource_pkey PRIMARY KEY (id);


--
