-- Table definitions + constraints: permissions_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: permissions_resource; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.permissions_resource (
    id uuid DEFAULT uuidv7() NOT NULL,
    artifact text NOT NULL,
    operation text NOT NULL,
    name text DEFAULT ''::text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--

-- Name: permissions_resource permissions_resource_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permissions_resource
    ADD CONSTRAINT permissions_resource_pkey PRIMARY KEY (id);


--

-- Name: permissions_resource permissions_resource_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permissions_resource
    ADD CONSTRAINT permissions_resource_unique UNIQUE (artifact, operation);


--
