-- Table definitions + constraints: primary_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: primary_departments_resource; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.primary_departments_resource (
    id uuid DEFAULT uuidv7() NOT NULL,
    departments_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--

-- Name: primary_departments_resource primary_departments_resource_departments_id_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.primary_departments_resource
    ADD CONSTRAINT primary_departments_resource_departments_id_unique UNIQUE (departments_id);


--

-- Name: primary_departments_resource primary_departments_resource_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.primary_departments_resource
    ADD CONSTRAINT primary_departments_resource_pkey PRIMARY KEY (id);


--
