-- Table definitions + constraints: request_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: request_limits_resource; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.request_limits_resource (
    id uuid DEFAULT uuidv7() CONSTRAINT request_limits_id_not_null NOT NULL,
    "limit" integer CONSTRAINT request_limits_requests_per_day_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT request_limits_created_at_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT request_limits_active_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT request_limits_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT request_limits_mcp_not_null NOT NULL,
    "interval" interval DEFAULT '1 day'::interval NOT NULL,
    CONSTRAINT request_limits_requests_per_day_check CHECK (("limit" > 0))
);


--

-- Name: request_limits_resource request_limits_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.request_limits_resource
    ADD CONSTRAINT request_limits_pkey PRIMARY KEY (id);


--
