"""Tool definitions for seeding.

Tools reference shared args by key (from database/seeds/resources/args.py).
Regenerate with: python database/scripts/generate_tools.py
"""

from database.seeds.ids import sid

tools = [
    dict(
        id="09794eeb-d970-577e-a5fe-0828394ac893",
        name="Activity Export",
        description="Export operation for Activity",
        permission_id=sid("permission/activity/export"),
        args=[],
    ),
    dict(
        id="f7e125ab-1519-51e8-aabf-b07fee350eb8",
        name="Activity Get",
        description="Get operation for Activity",
        permission_id=sid("permission/activity/get"),
        args=[],
    ),
    dict(
        id="1efe81c6-e3a4-5294-b987-eadaa51dc6ee",
        name="Activity Problem",
        description="Problem operation for Activity",
        permission_id=sid("permission/activity/problem"),
        args=["type", "message"],
    ),
    dict(
        id="13a9ad5c-8caa-5acb-b334-c5fb5d25eb61",
        name="Activity Refresh",
        description="Refresh operation for Activity",
        permission_id=sid("permission/activity/refresh"),
        args=[],
    ),
    dict(
        id="7e3beb89-3c22-58a8-bb29-cc06aab5ec1f",
        name="Activity Resolve",
        description="Resolve operation for Activity",
        permission_id=sid("permission/activity/resolve"),
        args=["problem_id", "resolved"],
    ),
    dict(
        id="7a48b064-ef50-5478-b36d-2cf4b9fc6bde",
        name="Activity Search",
        description="Search operation for Activity",
        permission_id=sid("permission/activity/search"),
        args=["date_from", "date_to", "department_ids", "roles", "active", "page", "page_size", "sort_order"],
    ),
    dict(
        id="4a233fa2-c38e-5f93-b55d-faaf86e31612",
        name="Agent Create",
        description="Create operation for Agent",
        permission_id=sid("permission/agent/create"),
        args=[],
    ),
    dict(
        id="815e7936-b3e6-57c0-9ccf-0ba4288b5541",
        name="Agent Delete",
        description="Delete operation for Agent",
        permission_id=sid("permission/agent/delete"),
        args=[],
    ),
    dict(
        id="bae63b89-e5b0-5049-95d9-7465b6f613dc",
        name="Agent Draft",
        description="Draft operation for Agent",
        permission_id=sid("permission/agent/draft"),
        args=[],
    ),
    dict(
        id="0a17eaf1-36bb-58fe-ac46-b5f71dcc58c0",
        name="Agent Drafts",
        description="Drafts operation for Agent",
        permission_id=sid("permission/agent/drafts"),
        args=[],
    ),
    dict(
        id="473e2d0b-a42e-5308-86cd-4654c1225e34",
        name="Agent Duplicate",
        description="Duplicate operation for Agent",
        permission_id=sid("permission/agent/duplicate"),
        args=[],
    ),
    dict(
        id="95f2d5d2-95a8-5ae8-a2d8-5be994f2633a",
        name="Agent Export",
        description="Export operation for Agent",
        permission_id=sid("permission/agent/export"),
        args=[],
    ),
    dict(
        id="17cb2698-c44a-5655-80d9-0e2a09455b0d",
        name="Agent Get",
        description="Get operation for Agent",
        permission_id=sid("permission/agent/get"),
        args=[],
    ),
    dict(
        id="53aa8ce2-2f54-5398-9534-219330f929b5",
        name="Agent Refresh",
        description="Refresh operation for Agent",
        permission_id=sid("permission/agent/refresh"),
        args=[],
    ),
    dict(
        id="61523ad4-e805-5353-9092-a92907388b5d",
        name="Agent Search",
        description="Search operation for Agent",
        permission_id=sid("permission/agent/search"),
        args=["search", "filter_department_ids", "filter_model_ids", "filter_tool_ids", "department_search", "model_search", "tool_search", "page_size", "page_offset"],
    ),
    dict(
        id="48861156-5f1e-5d03-8722-fb334b801b30",
        name="Agent Update",
        description="Update operation for Agent",
        permission_id=sid("permission/agent/update"),
        args=[],
    ),
    dict(
        id="502f1088-5451-59e7-afc1-af26c1b3d7de",
        name="Attempt Archive",
        description="Archive operation for Attempt",
        permission_id=sid("permission/attempt/archive"),
        args=["archived", "attempt_ids", "start_date", "end_date", "cohort_ids", "department_ids", "simulation_ids", "scenario_ids", "profile_ids_filter", "infinite_mode"],
    ),
    dict(
        id="0a0164c7-64b6-5911-b876-93110db2a5bb",
        name="Attempt Audio",
        description="Audio operation for Attempt",
        permission_id=sid("permission/attempt/audio"),
        args=[],
    ),
    dict(
        id="5a666ce5-034a-5068-81b8-d178d1f87857",
        name="Attempt End",
        description="End operation for Attempt",
        permission_id=sid("permission/attempt/end"),
        args=["attempt_id", "chat_id", "grade", "score", "passed", "time_taken", "feedbacks", "strengths", "improvements", "analyses", "highlights", "replacements"],
    ),
    dict(
        id="c93bb68e-89bc-5d12-b94f-1c29a4cfe5b2",
        name="Attempt End All",
        description="End All operation for Attempt",
        permission_id=sid("permission/attempt/end_all"),
        args=[],
    ),
    dict(
        id="eabd6a15-35be-5160-b51e-a0f665d9a833",
        name="Attempt Export",
        description="Export operation for Attempt",
        permission_id=sid("permission/attempt/export"),
        args=["attempt_id"],
    ),
    dict(
        id="6cc63656-fc69-51a8-908d-e05a0f9e35f0",
        name="Attempt Get",
        description="Get operation for Attempt",
        permission_id=sid("permission/attempt/get"),
        args=["attempt_id"],
    ),
    dict(
        id="f338b515-017f-5d4e-99e9-9db120fdee32",
        name="Attempt Grade",
        description="Grade operation for Attempt",
        permission_id=sid("permission/attempt/grade"),
        args=["attempt_id", "chat_id", "resource_types", "user_instructions", "score", "passed", "time_taken", "feedbacks", "strengths", "improvements", "analyses", "highlights", "replacements"],
    ),
    dict(
        id="c0405c1e-b158-521f-b018-5d7b48229e2e",
        name="Attempt Message",
        description="Message operation for Attempt",
        permission_id=sid("permission/attempt/message"),
        args=["attempt_id", "chat_id", "message", "parent_message_id", "assistant_content", "hints", "contents"],
    ),
    dict(
        id="0a96ff5d-2e0d-53e1-a182-1aa92d0a2f32",
        name="Attempt Next",
        description="Next operation for Attempt",
        permission_id=sid("permission/attempt/next"),
        args=[],
    ),
    dict(
        id="b8dcf644-d5a5-54ff-9156-da3af9d143a9",
        name="Attempt Refresh",
        description="Refresh operation for Attempt",
        permission_id=sid("permission/attempt/refresh"),
        args=[],
    ),
    dict(
        id="b78e2d07-e68c-525f-9c44-2b5806c9ddb3",
        name="Attempt Response",
        description="Response operation for Attempt",
        permission_id=sid("permission/attempt/response"),
        args=[],
    ),
    dict(
        id="8871e59a-9228-53fa-994a-93498ff71850",
        name="Attempt Search",
        description="Search operation for Attempt",
        permission_id=sid("permission/attempt/search"),
        args=["attempt_id", "chat_id", "home_id", "practice_id", "include_entries", "search", "limit", "cursor"],
    ),
    dict(
        id="680d00aa-35b9-505e-988f-7f0052977ec3",
        name="Attempt Start",
        description="Start operation for Attempt",
        permission_id=sid("permission/attempt/start"),
        args=[],
    ),
    dict(
        id="304ac127-2e79-576d-a1ed-97aa17053fc0",
        name="Attempt Stop",
        description="Stop operation for Attempt",
        permission_id=sid("permission/attempt/stop"),
        args=[],
    ),
    dict(
        id="4849b15b-c865-530a-9ed7-48f2572e4d4d",
        name="Attempt Use Previous",
        description="Use Previous operation for Attempt",
        permission_id=sid("permission/attempt/use_previous"),
        args=[],
    ),
    dict(
        id="cbe97ff0-4581-5be4-bf43-ead3e7c1cda6",
        name="Auth Create",
        description="Create operation for Auth",
        permission_id=sid("permission/auth/create"),
        args=[],
    ),
    dict(
        id="619a1519-c8b6-5dfd-9b1c-3a4620784059",
        name="Auth Delete",
        description="Delete operation for Auth",
        permission_id=sid("permission/auth/delete"),
        args=[],
    ),
    dict(
        id="2334ed3f-bea0-52f5-a4eb-2cd6e41904c6",
        name="Auth Draft",
        description="Draft operation for Auth",
        permission_id=sid("permission/auth/draft"),
        args=[],
    ),
    dict(
        id="498d0346-a25b-53c3-9bca-d84c70e44d32",
        name="Auth Drafts",
        description="Drafts operation for Auth",
        permission_id=sid("permission/auth/drafts"),
        args=[],
    ),
    dict(
        id="eb18c45a-af26-5f59-8219-62297ffac028",
        name="Auth Duplicate",
        description="Duplicate operation for Auth",
        permission_id=sid("permission/auth/duplicate"),
        args=[],
    ),
    dict(
        id="1a90d6ba-822c-5bad-9d70-e9bb912a55c0",
        name="Auth Export",
        description="Export operation for Auth",
        permission_id=sid("permission/auth/export"),
        args=["auth_id"],
    ),
    dict(
        id="4b9c870b-b1dc-50f0-bfc7-3cfec00498ee",
        name="Auth Get",
        description="Get operation for Auth",
        permission_id=sid("permission/auth/get"),
        args=[],
    ),
    dict(
        id="c0259670-2583-5015-9eb4-916888dcf1f5",
        name="Auth Refresh",
        description="Refresh operation for Auth",
        permission_id=sid("permission/auth/refresh"),
        args=[],
    ),
    dict(
        id="d064aa5d-cd44-5bba-b9da-d3a174fa2be4",
        name="Auth Search",
        description="Search operation for Auth",
        permission_id=sid("permission/auth/search"),
        args=["search", "filter_department_ids", "department_search", "page_size", "page_offset"],
    ),
    dict(
        id="2c6d108b-026c-5074-9a3b-786439cf2cc9",
        name="Auth Update",
        description="Update operation for Auth",
        permission_id=sid("permission/auth/update"),
        args=[],
    ),
    dict(
        id="ae380854-789b-597e-8394-360300ba24b1",
        name="Benchmark Export",
        description="Export operation for Benchmark",
        permission_id=sid("permission/benchmark/export"),
        args=[],
    ),
    dict(
        id="9744bbcd-88be-5328-8b7c-2070c1dcfd13",
        name="Benchmark Get",
        description="Get operation for Benchmark",
        permission_id=sid("permission/benchmark/get"),
        args=["start_date", "end_date", "department_ids", "history_page", "history_page_size", "history_eval_ids", "history_search", "history_archived", "history_sort_by", "history_sort_order"],
    ),
    dict(
        id="8c774f81-ffa2-5a74-b3bc-c9d86a6918f5",
        name="Benchmark Refresh",
        description="Refresh operation for Benchmark",
        permission_id=sid("permission/benchmark/refresh"),
        args=[],
    ),
    dict(
        id="70ed3d6f-7de0-5f7e-a208-43550f11ae3d",
        name="Benchmark Search",
        description="Search operation for Benchmark",
        permission_id=sid("permission/benchmark/search"),
        args=["start_date", "end_date", "department_ids", "history_page", "history_page_size", "history_eval_ids", "history_search", "history_archived", "history_sort_by", "history_sort_order"],
    ),
    dict(
        id="2f873abd-65d6-5197-b3d4-30a1d84d8f54",
        name="Chat Draft",
        description="Draft operation for Chat",
        permission_id=sid("permission/chat/draft"),
        args=[],
    ),
    dict(
        id="7a83974a-c8b9-5135-b02f-58400c8f14b6",
        name="Chat Drafts",
        description="Drafts operation for Chat",
        permission_id=sid("permission/chat/drafts"),
        args=[],
    ),
    dict(
        id="f0a20c3e-061d-51e0-8219-810eb5694b71",
        name="Chat Export",
        description="Export operation for Chat",
        permission_id=sid("permission/chat/export"),
        args=["chat_entry_id", "attempt_id", "draft_id"],
    ),
    dict(
        id="a02bce0b-96bc-5c7c-a832-7435787c741b",
        name="Chat Get",
        description="Get operation for Chat",
        permission_id=sid("permission/chat/get"),
        args=[],
    ),
    dict(
        id="0ffa5dee-de05-5a12-bc72-7568764a7168",
        name="Chat Refresh",
        description="Refresh operation for Chat",
        permission_id=sid("permission/chat/refresh"),
        args=[],
    ),
    dict(
        id="0d8aedcf-6d06-573d-9a1c-19c010dbbfb2",
        name="Cohort Create",
        description="Create operation for Cohort",
        permission_id=sid("permission/cohort/create"),
        args=[],
    ),
    dict(
        id="c34bc6ac-857c-50ff-959e-4763a12b3044",
        name="Cohort Delete",
        description="Delete operation for Cohort",
        permission_id=sid("permission/cohort/delete"),
        args=[],
    ),
    dict(
        id="906d0c32-5624-54b4-9736-1bdcac51729e",
        name="Cohort Draft",
        description="Draft operation for Cohort",
        permission_id=sid("permission/cohort/draft"),
        args=[],
    ),
    dict(
        id="bc5d30b9-959e-5d25-abda-c37d1d4a78a9",
        name="Cohort Drafts",
        description="Drafts operation for Cohort",
        permission_id=sid("permission/cohort/drafts"),
        args=[],
    ),
    dict(
        id="7f3b747f-e2b3-5032-9bc2-16a9069720ef",
        name="Cohort Duplicate",
        description="Duplicate operation for Cohort",
        permission_id=sid("permission/cohort/duplicate"),
        args=[],
    ),
    dict(
        id="256654bc-e7a1-550f-8a0e-bcc3790817e0",
        name="Cohort Export",
        description="Export operation for Cohort",
        permission_id=sid("permission/cohort/export"),
        args=["cohort_id"],
    ),
    dict(
        id="d41ae36f-d200-5fab-9ad7-cade0dabbcc9",
        name="Cohort Get",
        description="Get operation for Cohort",
        permission_id=sid("permission/cohort/get"),
        args=["cohort_id", "descriptions_search", "simulation_search", "simulation_show_selected", "profile_search", "profile_show_selected", "draft_id"],
    ),
    dict(
        id="53cdf3e4-869d-5773-8318-74f639018b91",
        name="Cohort Refresh",
        description="Refresh operation for Cohort",
        permission_id=sid("permission/cohort/refresh"),
        args=[],
    ),
    dict(
        id="da6519ae-18e9-5d3e-b9c7-6022fb08c264",
        name="Cohort Search",
        description="Search operation for Cohort",
        permission_id=sid("permission/cohort/search"),
        args=["search", "filter_profile_ids", "filter_simulation_ids", "filter_department_ids", "profile_search", "simulation_search", "department_search", "flag_search", "page_size", "page_offset"],
    ),
    dict(
        id="448ecf59-89ee-53d0-8c85-dcdf180f26b1",
        name="Cohort Update",
        description="Update operation for Cohort",
        permission_id=sid("permission/cohort/update"),
        args=[],
    ),
    dict(
        id="eddf3edd-fb3b-57af-a75f-e73dc06aeec4",
        name="Dashboard Export",
        description="Export operation for Dashboard",
        permission_id=sid("permission/dashboard/export"),
        args=[],
    ),
    dict(
        id="3560190d-b76a-51c2-92b9-49f8de156beb",
        name="Dashboard Get",
        description="Get operation for Dashboard",
        permission_id=sid("permission/dashboard/get"),
        args=[],
    ),
    dict(
        id="4893e110-d694-5137-bbc1-3aede11ed3de",
        name="Dashboard Refresh",
        description="Refresh operation for Dashboard",
        permission_id=sid("permission/dashboard/refresh"),
        args=[],
    ),
    dict(
        id="05de300e-1216-585f-b9fd-f74c6d530f23",
        name="Dashboard Search",
        description="Search operation for Dashboard",
        permission_id=sid("permission/dashboard/search"),
        args=["start_date", "end_date", "cohort_ids", "department_ids", "target_profile_id", "practice", "scenario_ids", "infinite_mode", "show_archived", "sort_by", "sort_order", "page", "page_size", "simulation_search", "scenario_search", "profile_search"],
    ),
    dict(
        id="a2fb4635-ba97-5542-993b-ec4ab14488a5",
        name="Department Create",
        description="Create operation for Department",
        permission_id=sid("permission/department/create"),
        args=[],
    ),
    dict(
        id="2a4b70f3-1017-59d6-81fc-ba0b0a2fff91",
        name="Department Delete",
        description="Delete operation for Department",
        permission_id=sid("permission/department/delete"),
        args=[],
    ),
    dict(
        id="083fa6fe-5e6c-5c94-8026-d5a2190d8115",
        name="Department Draft",
        description="Draft operation for Department",
        permission_id=sid("permission/department/draft"),
        args=[],
    ),
    dict(
        id="b3d94c12-8ad4-5b13-8dd2-17c732909ff4",
        name="Department Drafts",
        description="Drafts operation for Department",
        permission_id=sid("permission/department/drafts"),
        args=[],
    ),
    dict(
        id="45050bb3-67e5-5c7e-a5c7-7c8ccb615664",
        name="Department Duplicate",
        description="Duplicate operation for Department",
        permission_id=sid("permission/department/duplicate"),
        args=[],
    ),
    dict(
        id="4e90d0cf-e25e-517f-af03-e2c148fcd133",
        name="Department Export",
        description="Export operation for Department",
        permission_id=sid("permission/department/export"),
        args=["department_id"],
    ),
    dict(
        id="c6a3a721-a82f-5613-b8e3-72270571dfdd",
        name="Department Get",
        description="Get operation for Department",
        permission_id=sid("permission/department/get"),
        args=[],
    ),
    dict(
        id="0ac4fbe9-e095-50b7-9147-b5a17f77b455",
        name="Department Refresh",
        description="Refresh operation for Department",
        permission_id=sid("permission/department/refresh"),
        args=[],
    ),
    dict(
        id="65afc73d-40f5-508e-9c03-03b8bc7cbf74",
        name="Department Search",
        description="Search operation for Department",
        permission_id=sid("permission/department/search"),
        args=["search", "page_size", "page_offset"],
    ),
    dict(
        id="bc5e0ce1-13b3-56f4-ab9f-464ed2d54989",
        name="Department Update",
        description="Update operation for Department",
        permission_id=sid("permission/department/update"),
        args=[],
    ),
    dict(
        id="b9dc7f89-2fbf-5f08-9025-9f1e89c58003",
        name="Document Create",
        description="Create operation for Document",
        permission_id=sid("permission/document/create"),
        args=[],
    ),
    dict(
        id="446a4253-1b13-59ef-aa34-fd73b0d9ba33",
        name="Document Delete",
        description="Delete operation for Document",
        permission_id=sid("permission/document/delete"),
        args=[],
    ),
    dict(
        id="5a4c3390-da4d-5c46-bcaa-8dab4f199438",
        name="Document Draft",
        description="Draft operation for Document",
        permission_id=sid("permission/document/draft"),
        args=[],
    ),
    dict(
        id="6f2a8778-22dd-5c8f-b4fa-2adc19c62628",
        name="Document Drafts",
        description="Drafts operation for Document",
        permission_id=sid("permission/document/drafts"),
        args=[],
    ),
    dict(
        id="154e838a-93b0-595e-88f2-530194839ad2",
        name="Document Duplicate",
        description="Duplicate operation for Document",
        permission_id=sid("permission/document/duplicate"),
        args=[],
    ),
    dict(
        id="ac9e3292-8c84-5579-8ed4-6fc03b845d99",
        name="Document Export",
        description="Export operation for Document",
        permission_id=sid("permission/document/export"),
        args=["document_id"],
    ),
    dict(
        id="29511c88-94b6-5fe2-84cc-04b78e64c013",
        name="Document Get",
        description="Get operation for Document",
        permission_id=sid("permission/document/get"),
        args=[],
    ),
    dict(
        id="ee78d6fd-49ad-5d5d-960e-c3541884e622",
        name="Document Refresh",
        description="Refresh operation for Document",
        permission_id=sid("permission/document/refresh"),
        args=[],
    ),
    dict(
        id="1c23af40-471f-5bf4-8177-c431ab56f9cb",
        name="Document Search",
        description="Search operation for Document",
        permission_id=sid("permission/document/search"),
        args=["search", "scenario_ids", "field_ids", "filter_department_ids", "scenario_search", "field_search", "department_search", "page_size", "page_offset"],
    ),
    dict(
        id="51209c89-905e-53d0-9c7b-eae665f7a0a4",
        name="Document Update",
        description="Update operation for Document",
        permission_id=sid("permission/document/update"),
        args=[],
    ),
    dict(
        id="3f8d829b-6fcc-5a01-9ff1-2e77d70824b6",
        name="Eval Create",
        description="Create operation for Eval",
        permission_id=sid("permission/eval/create"),
        args=[],
    ),
    dict(
        id="911fefb0-6f13-5bdb-982f-ee2a5c7ccd2c",
        name="Eval Delete",
        description="Delete operation for Eval",
        permission_id=sid("permission/eval/delete"),
        args=[],
    ),
    dict(
        id="8388f6a9-36d1-5b9a-8f18-2a0f608ac841",
        name="Eval Draft",
        description="Draft operation for Eval",
        permission_id=sid("permission/eval/draft"),
        args=[],
    ),
    dict(
        id="1e9e7c6e-df57-5c4a-a1b8-bfc85589fe95",
        name="Eval Drafts",
        description="Drafts operation for Eval",
        permission_id=sid("permission/eval/drafts"),
        args=[],
    ),
    dict(
        id="df90ca0c-5f2a-5b74-9131-3c1456c0820e",
        name="Eval Duplicate",
        description="Duplicate operation for Eval",
        permission_id=sid("permission/eval/duplicate"),
        args=[],
    ),
    dict(
        id="1d240a35-0bc5-53dd-a549-cf73ce7ea7a5",
        name="Eval Export",
        description="Export operation for Eval",
        permission_id=sid("permission/eval/export"),
        args=["eval_id"],
    ),
    dict(
        id="50570745-2a72-5b19-aae2-105e8159e802",
        name="Eval Get",
        description="Get operation for Eval",
        permission_id=sid("permission/eval/get"),
        args=[],
    ),
    dict(
        id="97f67765-10cc-563f-a6e8-3ad6fd15d36b",
        name="Eval Refresh",
        description="Refresh operation for Eval",
        permission_id=sid("permission/eval/refresh"),
        args=[],
    ),
    dict(
        id="fea17452-7a64-5a1b-a543-8572d143f47e",
        name="Eval Search",
        description="Search operation for Eval",
        permission_id=sid("permission/eval/search"),
        args=["search", "filter_department_ids", "department_search", "page_size", "page_offset"],
    ),
    dict(
        id="8ab5d2c5-ee40-50d0-8fec-c6f32b9a5db2",
        name="Eval Update",
        description="Update operation for Eval",
        permission_id=sid("permission/eval/update"),
        args=[],
    ),
    dict(
        id="0c5fb9bb-5dee-56e1-af14-ba000dd05f69",
        name="Field Create",
        description="Create operation for Field",
        permission_id=sid("permission/field/create"),
        args=[],
    ),
    dict(
        id="a6ef2dcf-08fc-5b5a-9f27-51012109bada",
        name="Field Delete",
        description="Delete operation for Field",
        permission_id=sid("permission/field/delete"),
        args=[],
    ),
    dict(
        id="2a2267cd-8f28-5de2-8c15-45238795c5a2",
        name="Field Draft",
        description="Draft operation for Field",
        permission_id=sid("permission/field/draft"),
        args=[],
    ),
    dict(
        id="e1b640bd-776e-58a8-8a3a-a7915079e079",
        name="Field Drafts",
        description="Drafts operation for Field",
        permission_id=sid("permission/field/drafts"),
        args=[],
    ),
    dict(
        id="1238501d-320e-5a12-a04a-0eb8d8d81e87",
        name="Field Duplicate",
        description="Duplicate operation for Field",
        permission_id=sid("permission/field/duplicate"),
        args=[],
    ),
    dict(
        id="0f2f3f73-afe6-52bc-9257-fad2d02c8f9e",
        name="Field Export",
        description="Export operation for Field",
        permission_id=sid("permission/field/export"),
        args=["field_id"],
    ),
    dict(
        id="624a1a82-a770-5c0c-b6f6-780e6105a650",
        name="Field Get",
        description="Get operation for Field",
        permission_id=sid("permission/field/get"),
        args=[],
    ),
    dict(
        id="c3270196-51c2-5ec2-bda8-f8fc03e66f12",
        name="Field Refresh",
        description="Refresh operation for Field",
        permission_id=sid("permission/field/refresh"),
        args=[],
    ),
    dict(
        id="40332499-b958-5ff0-b26e-c1904100a8d8",
        name="Field Search",
        description="Search operation for Field",
        permission_id=sid("permission/field/search"),
        args=["search", "parameter_ids", "persona_ids", "filter_department_ids", "parameter_search", "persona_search", "department_search", "page_size", "page_offset"],
    ),
    dict(
        id="19936242-b01f-507c-bfd1-ab98e9973a9d",
        name="Field Update",
        description="Update operation for Field",
        permission_id=sid("permission/field/update"),
        args=[],
    ),
    dict(
        id="0ac89962-650d-58f3-9cf9-6dcde6da84f6",
        name="Group Export",
        description="Export operation for Group",
        permission_id=sid("permission/group/export"),
        args=["group_id"],
    ),
    dict(
        id="3167d978-1c26-5fb6-acb6-c77b0019305c",
        name="Group Generate",
        description="Generate operation for Group",
        permission_id=sid("permission/group/generate"),
        args=[],
    ),
    dict(
        id="4fabbfb3-81ec-56fe-9cff-9515e252c681",
        name="Group Get",
        description="Get operation for Group",
        permission_id=sid("permission/group/get"),
        args=["group_id", "message_limit", "message_offset"],
    ),
    dict(
        id="167eb7f7-8ca8-5339-b58f-54deed33dd0d",
        name="Group Refresh",
        description="Refresh operation for Group",
        permission_id=sid("permission/group/refresh"),
        args=[],
    ),
    dict(
        id="5b5469ce-c2df-5c86-ae9c-81b31efbb251",
        name="Health Export",
        description="Export operation for Health",
        permission_id=sid("permission/health/export"),
        args=[],
    ),
    dict(
        id="b64245d4-c539-54bc-8ee9-f835a856f005",
        name="Health Get",
        description="Get operation for Health",
        permission_id=sid("permission/health/get"),
        args=["service", "date_from", "date_to", "page_limit", "page_offset"],
    ),
    dict(
        id="205e83e5-7189-5464-83fb-d88a835fe560",
        name="Health Refresh",
        description="Refresh operation for Health",
        permission_id=sid("permission/health/refresh"),
        args=[],
    ),
    dict(
        id="a59db208-22dd-5951-8df2-a47ee4bd43e3",
        name="Home Export",
        description="Export operation for Home",
        permission_id=sid("permission/home/export"),
        args=[],
    ),
    dict(
        id="19b0fa1f-0327-57c5-9777-d8f857337c7f",
        name="Home Get",
        description="Get operation for Home",
        permission_id=sid("permission/home/get"),
        args=[],
    ),
    dict(
        id="9f18d019-77a3-5b07-abea-a2b3540d7748",
        name="Home Refresh",
        description="Refresh operation for Home",
        permission_id=sid("permission/home/refresh"),
        args=[],
    ),
    dict(
        id="65665e15-f208-59fd-83ff-491f6c7c8490",
        name="Home Search",
        description="Search operation for Home",
        permission_id=sid("permission/home/search"),
        args=["sort_by", "sort_order", "page", "page_size", "simulation_search", "scenario_search", "scenario_ids", "infinite_mode"],
    ),
    dict(
        id="0c73a382-4668-5122-9e83-cce9fea855df",
        name="Invocation Decrypt",
        description="Decrypt operation for Invocation",
        permission_id=sid("permission/invocation/decrypt"),
        args=[],
    ),
    dict(
        id="2a8c806e-6e7e-5739-96e5-741d08e2d24c",
        name="Invocation Draft",
        description="Draft operation for Invocation",
        permission_id=sid("permission/invocation/draft"),
        args=[],
    ),
    dict(
        id="9886f0a5-eee6-5cc8-92c0-edcc43acb659",
        name="Invocation Drafts",
        description="Drafts operation for Invocation",
        permission_id=sid("permission/invocation/drafts"),
        args=[],
    ),
    dict(
        id="401fc6c1-299a-5840-87c4-2788c59504c5",
        name="Invocation Export",
        description="Export operation for Invocation",
        permission_id=sid("permission/invocation/export"),
        args=["test_id", "invocation_entry_id", "draft_id"],
    ),
    dict(
        id="321b4d4b-07dc-5511-a359-7af0bda7c44b",
        name="Invocation Get",
        description="Get operation for Invocation",
        permission_id=sid("permission/invocation/get"),
        args=[],
    ),
    dict(
        id="db914f5a-9d03-59f6-a98e-05582edfa23b",
        name="Invocation Refresh",
        description="Refresh operation for Invocation",
        permission_id=sid("permission/invocation/refresh"),
        args=[],
    ),
    dict(
        id="60585e46-b32b-52cb-820d-8b885f201d60",
        name="Leaderboard Export",
        description="Export operation for Leaderboard",
        permission_id=sid("permission/leaderboard/export"),
        args=[],
    ),
    dict(
        id="fa6c219b-068f-5f12-989f-930bf3ac8be3",
        name="Leaderboard Get",
        description="Get operation for Leaderboard",
        permission_id=sid("permission/leaderboard/get"),
        args=[],
    ),
    dict(
        id="84b81d50-a051-5dd9-b420-4c79b88f9bb5",
        name="Leaderboard Refresh",
        description="Refresh operation for Leaderboard",
        permission_id=sid("permission/leaderboard/refresh"),
        args=[],
    ),
    dict(
        id="84c5e905-3cc3-56a9-88ad-4e85d69b3e27",
        name="Leaderboard Search",
        description="Search operation for Leaderboard",
        permission_id=sid("permission/leaderboard/search"),
        args=["start_date", "end_date", "cohort_ids", "simulation_ids", "department_ids", "simulation_filters", "target_profile_id", "cohort_id", "simulation_id", "scenario_ids", "search", "sort_by", "sort_order", "page_limit", "page_offset"],
    ),
    dict(
        id="70bdfcfa-4cff-5e85-9c2d-4f351b4f54fc",
        name="Model Create",
        description="Create operation for Model",
        permission_id=sid("permission/model/create"),
        args=[],
    ),
    dict(
        id="73c8e961-b9e3-5e67-ab9d-b93e989e7cfd",
        name="Model Delete",
        description="Delete operation for Model",
        permission_id=sid("permission/model/delete"),
        args=[],
    ),
    dict(
        id="d53b302a-2b60-50cd-ab3e-132685009022",
        name="Model Draft",
        description="Draft operation for Model",
        permission_id=sid("permission/model/draft"),
        args=[],
    ),
    dict(
        id="4d4bcb69-bee6-58d1-a026-0d97e5121f0a",
        name="Model Drafts",
        description="Drafts operation for Model",
        permission_id=sid("permission/model/drafts"),
        args=[],
    ),
    dict(
        id="870e444a-1214-50e1-b07a-9bded72eb3ea",
        name="Model Duplicate",
        description="Duplicate operation for Model",
        permission_id=sid("permission/model/duplicate"),
        args=[],
    ),
    dict(
        id="4d49dd21-58f4-5316-983c-b792777d9a13",
        name="Model Export",
        description="Export operation for Model",
        permission_id=sid("permission/model/export"),
        args=["model_id"],
    ),
    dict(
        id="31d61a6e-b0f0-5d41-acac-fff78dd586f5",
        name="Model Get",
        description="Get operation for Model",
        permission_id=sid("permission/model/get"),
        args=[],
    ),
    dict(
        id="d23a11df-a4b6-54c4-b117-d335633d7e16",
        name="Model Refresh",
        description="Refresh operation for Model",
        permission_id=sid("permission/model/refresh"),
        args=[],
    ),
    dict(
        id="af85f397-9a27-507b-8828-8345f2cda821",
        name="Model Search",
        description="Search operation for Model",
        permission_id=sid("permission/model/search"),
        args=["search", "filter_provider_ids", "filter_department_ids", "filter_agent_ids", "provider_search", "department_search", "agent_search", "page_size", "page_offset"],
    ),
    dict(
        id="3ee5fa67-3469-5e38-930e-6fb0df679572",
        name="Model Update",
        description="Update operation for Model",
        permission_id=sid("permission/model/update"),
        args=[],
    ),
    dict(
        id="81885fc7-ad41-5f5e-914f-002576351412",
        name="Parameter Create",
        description="Create operation for Parameter",
        permission_id=sid("permission/parameter/create"),
        args=[],
    ),
    dict(
        id="f3e6d1ac-de3d-529c-aac3-d6230a4761c4",
        name="Parameter Delete",
        description="Delete operation for Parameter",
        permission_id=sid("permission/parameter/delete"),
        args=[],
    ),
    dict(
        id="926d9a00-6398-5b21-835f-70e0f4702cf6",
        name="Parameter Draft",
        description="Draft operation for Parameter",
        permission_id=sid("permission/parameter/draft"),
        args=[],
    ),
    dict(
        id="9c86ba2d-84c6-55e1-ae26-a6e395491ffe",
        name="Parameter Drafts",
        description="Drafts operation for Parameter",
        permission_id=sid("permission/parameter/drafts"),
        args=[],
    ),
    dict(
        id="e3061ea6-4124-5692-9160-7703705ab193",
        name="Parameter Duplicate",
        description="Duplicate operation for Parameter",
        permission_id=sid("permission/parameter/duplicate"),
        args=[],
    ),
    dict(
        id="4755b335-3fce-5893-9a0a-d24ac92fef9e",
        name="Parameter Export",
        description="Export operation for Parameter",
        permission_id=sid("permission/parameter/export"),
        args=["parameter_id"],
    ),
    dict(
        id="f5f2cea2-c108-5cc7-9f45-f250897f8070",
        name="Parameter Get",
        description="Get operation for Parameter",
        permission_id=sid("permission/parameter/get"),
        args=[],
    ),
    dict(
        id="b55b4347-cc38-591a-82d4-976382aa301e",
        name="Parameter Refresh",
        description="Refresh operation for Parameter",
        permission_id=sid("permission/parameter/refresh"),
        args=[],
    ),
    dict(
        id="a12b2301-1b72-5bd5-a180-86c39bafe751",
        name="Parameter Search",
        description="Search operation for Parameter",
        permission_id=sid("permission/parameter/search"),
        args=["search", "scenario_ids", "field_ids", "filter_department_ids", "scenario_search", "field_search", "department_search", "page_size", "page_offset"],
    ),
    dict(
        id="1cd4b685-586f-5f9e-8ab0-cafbb2a3bfc3",
        name="Parameter Update",
        description="Update operation for Parameter",
        permission_id=sid("permission/parameter/update"),
        args=[],
    ),
    dict(
        id="ddac56a9-7873-5240-a904-d6557e05c7e1",
        name="Persona Create",
        description="Create operation for Persona",
        permission_id=sid("permission/persona/create"),
        args=[],
    ),
    dict(
        id="0da58846-1820-515e-b8f0-03e213cbbd68",
        name="Persona Delete",
        description="Delete operation for Persona",
        permission_id=sid("permission/persona/delete"),
        args=[],
    ),
    dict(
        id="e69bb8ae-940d-5521-8681-446061e4ce68",
        name="Persona Draft",
        description="Draft operation for Persona",
        permission_id=sid("permission/persona/draft"),
        args=[],
    ),
    dict(
        id="14353a32-5d7c-539a-8ce0-0f94416e9d2e",
        name="Persona Drafts",
        description="Drafts operation for Persona",
        permission_id=sid("permission/persona/drafts"),
        args=[],
    ),
    dict(
        id="11c22914-df61-5c0b-b626-47758252e8da",
        name="Persona Duplicate",
        description="Duplicate operation for Persona",
        permission_id=sid("permission/persona/duplicate"),
        args=[],
    ),
    dict(
        id="787d8d72-8f28-5c44-b885-9eb5fb52072f",
        name="Persona Export",
        description="Export operation for Persona",
        permission_id=sid("permission/persona/export"),
        args=[],
    ),
    dict(
        id="baed6bf7-d5a8-5100-be59-7c35ed8b57ea",
        name="Persona Get",
        description="Get operation for Persona",
        permission_id=sid("permission/persona/get"),
        args=[],
    ),
    dict(
        id="9855859a-3c8b-5b72-8d26-1b729c6fa42f",
        name="Persona Refresh",
        description="Refresh operation for Persona",
        permission_id=sid("permission/persona/refresh"),
        args=[],
    ),
    dict(
        id="4ae614e6-9f8e-55aa-b398-093e02b9ef4f",
        name="Persona Search",
        description="Search operation for Persona",
        permission_id=sid("permission/persona/search"),
        args=["search", "scenario_ids", "field_ids", "filter_department_ids", "scenario_search", "field_search", "department_search", "color_search", "icon_search", "voice_search", "instruction_search", "page_size", "page_offset"],
    ),
    dict(
        id="bb297505-40a0-5562-bdc7-f7e9a36b96b7",
        name="Persona Update",
        description="Update operation for Persona",
        permission_id=sid("permission/persona/update"),
        args=[],
    ),
    dict(
        id="835a2c19-64aa-531f-ac61-3081c1e1e255",
        name="Practice Export",
        description="Export operation for Practice",
        permission_id=sid("permission/practice/export"),
        args=[],
    ),
    dict(
        id="4dee5c9d-a949-5b4c-be7a-fe705450d7c4",
        name="Practice Get",
        description="Get operation for Practice",
        permission_id=sid("permission/practice/get"),
        args=[],
    ),
    dict(
        id="cfe5a8b2-d184-53fd-b4c9-4187902aceeb",
        name="Practice Refresh",
        description="Refresh operation for Practice",
        permission_id=sid("permission/practice/refresh"),
        args=[],
    ),
    dict(
        id="f57894f0-3d0d-595e-9109-ba2d1d81fa7e",
        name="Practice Search",
        description="Search operation for Practice",
        permission_id=sid("permission/practice/search"),
        args=["sort_by", "sort_order", "page", "page_size", "simulation_search", "scenario_search", "show_archived", "scenario_ids", "infinite_mode"],
    ),
    dict(
        id="16fe9456-1e83-5d5e-891d-4e453c9fe6cd",
        name="Pricing Export",
        description="Export operation for Pricing",
        permission_id=sid("permission/pricing/export"),
        args=[],
    ),
    dict(
        id="30ae4226-7d90-54f0-a4ce-17cac37657b6",
        name="Pricing Get",
        description="Get operation for Pricing",
        permission_id=sid("permission/pricing/get"),
        args=["start_date", "end_date", "date_from", "date_to"],
    ),
    dict(
        id="e19ac2ec-75ee-51d4-a2cd-b323da7ef605",
        name="Pricing Refresh",
        description="Refresh operation for Pricing",
        permission_id=sid("permission/pricing/refresh"),
        args=[],
    ),
    dict(
        id="65e6e704-4f7b-5806-b8fb-f28127bd4ecd",
        name="Pricing Search",
        description="Search operation for Pricing",
        permission_id=sid("permission/pricing/search"),
        args=["start_date", "end_date", "date_from", "date_to", "page", "page_size", "sort_order"],
    ),
    dict(
        id="146a3cc0-91c2-5d7d-8594-14bba710f800",
        name="Profile Context",
        description="Context operation for Profile",
        permission_id=sid("permission/profile/context"),
        args=[],
    ),
    dict(
        id="8d170106-1dc4-569c-81f4-ca89d8e2b5d2",
        name="Profile Create",
        description="Create operation for Profile",
        permission_id=sid("permission/profile/create"),
        args=[],
    ),
    dict(
        id="4f2ddaed-1e54-5516-91af-c4b79bf56bb3",
        name="Profile Delete",
        description="Delete operation for Profile",
        permission_id=sid("permission/profile/delete"),
        args=[],
    ),
    dict(
        id="98108d2f-d383-5182-ace0-2d7a69798492",
        name="Profile Draft",
        description="Draft operation for Profile",
        permission_id=sid("permission/profile/draft"),
        args=[],
    ),
    dict(
        id="879d37e0-b7d8-5e24-9345-0aaefe37c193",
        name="Profile Drafts",
        description="Drafts operation for Profile",
        permission_id=sid("permission/profile/drafts"),
        args=[],
    ),
    dict(
        id="da656b67-1bee-5770-831d-4504f648e90c",
        name="Profile Duplicate",
        description="Duplicate operation for Profile",
        permission_id=sid("permission/profile/duplicate"),
        args=[],
    ),
    dict(
        id="c96f58a4-b4e6-563b-9bd8-59f29d0dd770",
        name="Profile Emulate",
        description="Emulate operation for Profile",
        permission_id=sid("permission/profile/emulate"),
        args=[],
    ),
    dict(
        id="c0a255ec-5f08-5836-bfa6-308425c7dd8d",
        name="Profile Export",
        description="Export operation for Profile",
        permission_id=sid("permission/profile/export"),
        args=["profile_export_id"],
    ),
    dict(
        id="b46c4c20-3481-54a4-b36c-70d0559cdf03",
        name="Profile Get",
        description="Get operation for Profile",
        permission_id=sid("permission/profile/get"),
        args=[],
    ),
    dict(
        id="3d383b43-37f2-599d-9a37-4b3a8da70083",
        name="Profile Refresh",
        description="Refresh operation for Profile",
        permission_id=sid("permission/profile/refresh"),
        args=[],
    ),
    dict(
        id="7b0e21dd-94ce-58dd-87f7-46ebc16f8304",
        name="Profile Search",
        description="Search operation for Profile",
        permission_id=sid("permission/profile/search"),
        args=["search", "cohort_ids", "filter_department_ids", "role_filter", "cohort_search", "department_search", "role_search", "page_size", "page_offset"],
    ),
    dict(
        id="200381ea-5eba-5cc3-b946-ff50f77080e8",
        name="Profile Unemulate",
        description="Unemulate operation for Profile",
        permission_id=sid("permission/profile/unemulate"),
        args=[],
    ),
    dict(
        id="3b077fdd-dc0a-57a0-a24f-05653457123a",
        name="Profile Update",
        description="Update operation for Profile",
        permission_id=sid("permission/profile/update"),
        args=[],
    ),
    dict(
        id="2e3c8658-757e-516f-b9b3-8e433deee47d",
        name="Provider Create",
        description="Create operation for Provider",
        permission_id=sid("permission/provider/create"),
        args=[],
    ),
    dict(
        id="eeb16374-cf18-5d7c-8c8c-86b1a31513ac",
        name="Provider Decrypt",
        description="Decrypt operation for Provider",
        permission_id=sid("permission/provider/decrypt"),
        args=[],
    ),
    dict(
        id="57453380-2b19-519a-b3a4-7867f9f45a61",
        name="Provider Delete",
        description="Delete operation for Provider",
        permission_id=sid("permission/provider/delete"),
        args=[],
    ),
    dict(
        id="98f24604-4554-5265-a89b-084d5e903c2b",
        name="Provider Draft",
        description="Draft operation for Provider",
        permission_id=sid("permission/provider/draft"),
        args=[],
    ),
    dict(
        id="416a76d6-6a5f-572b-849d-5052f3d74c9b",
        name="Provider Drafts",
        description="Drafts operation for Provider",
        permission_id=sid("permission/provider/drafts"),
        args=[],
    ),
    dict(
        id="61df783a-5114-5355-b805-87cb16c8db8a",
        name="Provider Duplicate",
        description="Duplicate operation for Provider",
        permission_id=sid("permission/provider/duplicate"),
        args=[],
    ),
    dict(
        id="a0033129-e449-55bd-afd5-416a978f9390",
        name="Provider Export",
        description="Export operation for Provider",
        permission_id=sid("permission/provider/export"),
        args=["provider_id"],
    ),
    dict(
        id="04cfba7d-ea9f-5db7-9223-fa6eeee9964a",
        name="Provider Get",
        description="Get operation for Provider",
        permission_id=sid("permission/provider/get"),
        args=[],
    ),
    dict(
        id="710d6e35-48f8-5967-acd2-36d4ce19860a",
        name="Provider Refresh",
        description="Refresh operation for Provider",
        permission_id=sid("permission/provider/refresh"),
        args=[],
    ),
    dict(
        id="0f7cad56-b4e1-5149-a573-b02dc23d9fe9",
        name="Provider Search",
        description="Search operation for Provider",
        permission_id=sid("permission/provider/search"),
        args=["search", "filter_department_ids", "filter_model_ids", "filter_status", "department_search", "model_search", "page_size", "page_offset"],
    ),
    dict(
        id="ae5d23c1-dc1f-59ab-b733-e61be2b33a6d",
        name="Provider Update",
        description="Update operation for Provider",
        permission_id=sid("permission/provider/update"),
        args=[],
    ),
    dict(
        id="5b775fe9-6fd8-5203-af37-8f7ed1850160",
        name="Record Export",
        description="Export operation for Record",
        permission_id=sid("permission/record/export"),
        args=["target_profile_id"],
    ),
    dict(
        id="b16e6a95-3f09-5438-b2a5-82532a0a58c9",
        name="Record Get",
        description="Get operation for Record",
        permission_id=sid("permission/record/get"),
        args=["target_profile_id", "start_date", "end_date", "cohort_ids", "simulation_ids", "department_ids", "simulation_filters", "actor_profile_id", "rubric_ids", "rubric_search", "simulation_picker_ids", "simulation_picker_search", "parameter_ids", "parameter_search", "scenario_ids", "scenario_search", "history_practice", "history_scenario_ids", "history_infinite_mode", "history_show_archived", "history_sort_by", "history_sort_order", "history_page", "history_page_size", "history_simulation_search", "history_scenario_search", "history_profile_search"],
    ),
    dict(
        id="2341abaf-b4aa-53c8-a961-c36fc6051774",
        name="Record Refresh",
        description="Refresh operation for Record",
        permission_id=sid("permission/record/refresh"),
        args=[],
    ),
    dict(
        id="68216feb-45ea-59c4-af7d-8a2b4e7afbe7",
        name="Record Search",
        description="Search operation for Record",
        permission_id=sid("permission/record/search"),
        args=["target_profile_id", "start_date", "end_date", "cohort_ids", "department_ids", "practice", "scenario_ids", "infinite_mode", "show_archived", "sort_by", "sort_order", "page", "page_size", "simulation_search", "scenario_search"],
    ),
    dict(
        id="dd6cf9d1-faf5-5ac5-bb91-bcd520577770",
        name="Reports Export",
        description="Export operation for Reports",
        permission_id=sid("permission/reports/export"),
        args=[],
    ),
    dict(
        id="ec3a2bba-45ce-536b-b26c-3d5f04e47a76",
        name="Reports Get",
        description="Get operation for Reports",
        permission_id=sid("permission/reports/get"),
        args=[],
    ),
    dict(
        id="cae46908-c09d-5298-99e4-b43934bc3be3",
        name="Reports Refresh",
        description="Refresh operation for Reports",
        permission_id=sid("permission/reports/refresh"),
        args=[],
    ),
    dict(
        id="74a2a54e-1893-545e-9c94-64715262c825",
        name="Reports Search",
        description="Search operation for Reports",
        permission_id=sid("permission/reports/search"),
        args=["start_date", "end_date", "cohort_ids", "simulation_ids", "department_ids", "roles", "simulation_filters", "actor_profile_id", "target_profile_id", "profile_ids", "scenario_ids", "search", "sort_by", "sort_order", "page_limit", "page_offset"],
    ),
    dict(
        id="359be470-29e6-58d8-a014-9fdb64bfbedf",
        name="Rubric Create",
        description="Create operation for Rubric",
        permission_id=sid("permission/rubric/create"),
        args=[],
    ),
    dict(
        id="2a1626a2-8930-5001-baca-e411f15a15eb",
        name="Rubric Delete",
        description="Delete operation for Rubric",
        permission_id=sid("permission/rubric/delete"),
        args=[],
    ),
    dict(
        id="777ec0cb-dd48-54fd-97ed-cab922ad2584",
        name="Rubric Draft",
        description="Draft operation for Rubric",
        permission_id=sid("permission/rubric/draft"),
        args=[],
    ),
    dict(
        id="81a0dd62-87d5-56d5-9e74-c4fb809b1aad",
        name="Rubric Drafts",
        description="Drafts operation for Rubric",
        permission_id=sid("permission/rubric/drafts"),
        args=[],
    ),
    dict(
        id="97a48188-a310-560c-be97-5ea00f8234d6",
        name="Rubric Duplicate",
        description="Duplicate operation for Rubric",
        permission_id=sid("permission/rubric/duplicate"),
        args=[],
    ),
    dict(
        id="1c07d3f8-d34f-5bcb-8b30-b10af67d91fc",
        name="Rubric Export",
        description="Export operation for Rubric",
        permission_id=sid("permission/rubric/export"),
        args=["rubric_id"],
    ),
    dict(
        id="c5d34dc0-4cbb-5b19-8c2f-db98387759bd",
        name="Rubric Get",
        description="Get operation for Rubric",
        permission_id=sid("permission/rubric/get"),
        args=[],
    ),
    dict(
        id="10b4ec28-aba3-57f2-ad29-07c3f0695a9d",
        name="Rubric Refresh",
        description="Refresh operation for Rubric",
        permission_id=sid("permission/rubric/refresh"),
        args=[],
    ),
    dict(
        id="a37b5fe5-ac73-5c85-9e56-97370ecc8b21",
        name="Rubric Search",
        description="Search operation for Rubric",
        permission_id=sid("permission/rubric/search"),
        args=["search", "filter_department_ids", "filter_simulation_ids", "department_search", "simulation_search", "page_size", "page_offset"],
    ),
    dict(
        id="98fcb61a-ab59-5809-9813-4fc080ac1c80",
        name="Rubric Update",
        description="Update operation for Rubric",
        permission_id=sid("permission/rubric/update"),
        args=[],
    ),
    dict(
        id="176caf12-5439-5579-95e0-2b8e5fa53584",
        name="Scenario Create",
        description="Create operation for Scenario",
        permission_id=sid("permission/scenario/create"),
        args=[],
    ),
    dict(
        id="a5539636-917f-5a7a-8fed-cd47ad74b3b9",
        name="Scenario Delete",
        description="Delete operation for Scenario",
        permission_id=sid("permission/scenario/delete"),
        args=[],
    ),
    dict(
        id="471f5d8b-d88f-57c1-a894-f901c19994b2",
        name="Scenario Draft",
        description="Draft operation for Scenario",
        permission_id=sid("permission/scenario/draft"),
        args=[],
    ),
    dict(
        id="3bdf61fe-78db-5bf7-a263-ed9c0c72f12a",
        name="Scenario Drafts",
        description="Drafts operation for Scenario",
        permission_id=sid("permission/scenario/drafts"),
        args=[],
    ),
    dict(
        id="02482a87-9153-5788-94e8-e0107803206c",
        name="Scenario Duplicate",
        description="Duplicate operation for Scenario",
        permission_id=sid("permission/scenario/duplicate"),
        args=[],
    ),
    dict(
        id="7ca930fc-16cf-5d8a-85bd-b4f47f119936",
        name="Scenario Export",
        description="Export operation for Scenario",
        permission_id=sid("permission/scenario/export"),
        args=[],
    ),
    dict(
        id="0e9aa497-c25a-53d9-9111-d6e5f0c3f684",
        name="Scenario Get",
        description="Get operation for Scenario",
        permission_id=sid("permission/scenario/get"),
        args=[],
    ),
    dict(
        id="79dff643-c352-5811-9274-d096cf48d332",
        name="Scenario Refresh",
        description="Refresh operation for Scenario",
        permission_id=sid("permission/scenario/refresh"),
        args=[],
    ),
    dict(
        id="b6f9925b-6054-50ca-a390-66e88620a034",
        name="Scenario Search",
        description="Search operation for Scenario",
        permission_id=sid("permission/scenario/search"),
        args=["search", "persona_ids", "simulation_ids", "filter_department_ids", "persona_search", "simulation_search", "department_search", "flag_search", "page_size", "page_offset"],
    ),
    dict(
        id="d5bc114c-068f-5563-b4a3-482124970cdf",
        name="Scenario Update",
        description="Update operation for Scenario",
        permission_id=sid("permission/scenario/update"),
        args=[],
    ),
    dict(
        id="7ae791ab-9c2a-54b1-919f-7e78cba4d958",
        name="Session Export",
        description="Export operation for Session",
        permission_id=sid("permission/session/export"),
        args=["target_session_id"],
    ),
    dict(
        id="2c5cf346-69f2-5a04-8323-c4d33e54f19d",
        name="Session Get",
        description="Get operation for Session",
        permission_id=sid("permission/session/get"),
        args=[],
    ),
    dict(
        id="570878d6-4a3d-5f4e-9cd9-e82156c96f70",
        name="Session Refresh",
        description="Refresh operation for Session",
        permission_id=sid("permission/session/refresh"),
        args=[],
    ),
    dict(
        id="10a921d9-5651-5195-be4f-ee3deb7ff8df",
        name="Setting Create",
        description="Create operation for Setting",
        permission_id=sid("permission/setting/create"),
        args=[],
    ),
    dict(
        id="7a865715-05dd-5ed9-9398-7f4bae0c120e",
        name="Setting Decrypt",
        description="Decrypt operation for Setting",
        permission_id=sid("permission/setting/decrypt"),
        args=[],
    ),
    dict(
        id="03e8d32d-7763-50e0-a818-001da6d046e6",
        name="Setting Delete",
        description="Delete operation for Setting",
        permission_id=sid("permission/setting/delete"),
        args=[],
    ),
    dict(
        id="dc1e84a8-7f93-5505-ab76-7690e3cb9a8b",
        name="Setting Draft",
        description="Draft operation for Setting",
        permission_id=sid("permission/setting/draft"),
        args=[],
    ),
    dict(
        id="4a9518e2-b82e-5fe4-8144-0b1cf9d18824",
        name="Setting Drafts",
        description="Drafts operation for Setting",
        permission_id=sid("permission/setting/drafts"),
        args=[],
    ),
    dict(
        id="c29abd35-60c5-5707-8ed3-cf1cc1326ceb",
        name="Setting Duplicate",
        description="Duplicate operation for Setting",
        permission_id=sid("permission/setting/duplicate"),
        args=[],
    ),
    dict(
        id="75ccc5c3-32b6-5082-b1c5-ca1273def5a7",
        name="Setting Export",
        description="Export operation for Setting",
        permission_id=sid("permission/setting/export"),
        args=["setting_id"],
    ),
    dict(
        id="a0f10474-d77d-5f44-beb0-8015a658f300",
        name="Setting Get",
        description="Get operation for Setting",
        permission_id=sid("permission/setting/get"),
        args=[],
    ),
    dict(
        id="58f5fd71-9c78-542d-bf39-a97e5d943686",
        name="Setting Refresh",
        description="Refresh operation for Setting",
        permission_id=sid("permission/setting/refresh"),
        args=[],
    ),
    dict(
        id="9215de84-e6a7-54d5-86db-382a48293a30",
        name="Setting Search",
        description="Search operation for Setting",
        permission_id=sid("permission/setting/search"),
        args=[],
    ),
    dict(
        id="0a5941d7-2859-51ab-a976-3d034a47b074",
        name="Setting Update",
        description="Update operation for Setting",
        permission_id=sid("permission/setting/update"),
        args=[],
    ),
    dict(
        id="9eb388c5-6909-58c4-b83b-9542b432a876",
        name="Simulation Create",
        description="Create operation for Simulation",
        permission_id=sid("permission/simulation/create"),
        args=[],
    ),
    dict(
        id="eb1ea075-d01d-5009-a0a2-ca9e5919eec5",
        name="Simulation Delete",
        description="Delete operation for Simulation",
        permission_id=sid("permission/simulation/delete"),
        args=[],
    ),
    dict(
        id="0e75316d-75f1-5832-ab7b-686d0bbefbf4",
        name="Simulation Draft",
        description="Draft operation for Simulation",
        permission_id=sid("permission/simulation/draft"),
        args=[],
    ),
    dict(
        id="950f2cc4-0344-5d41-be64-9ea3b5309725",
        name="Simulation Drafts",
        description="Drafts operation for Simulation",
        permission_id=sid("permission/simulation/drafts"),
        args=[],
    ),
    dict(
        id="19d7a637-2668-5adb-8722-740b531fd0c2",
        name="Simulation Duplicate",
        description="Duplicate operation for Simulation",
        permission_id=sid("permission/simulation/duplicate"),
        args=[],
    ),
    dict(
        id="a73f0522-f2b5-560a-95d9-9195accf8ffb",
        name="Simulation Export",
        description="Export operation for Simulation",
        permission_id=sid("permission/simulation/export"),
        args=[],
    ),
    dict(
        id="475ee052-c5db-5390-85ac-9bb46995b50e",
        name="Simulation Get",
        description="Get operation for Simulation",
        permission_id=sid("permission/simulation/get"),
        args=[],
    ),
    dict(
        id="b77f17a3-dd1a-5768-80f2-b49076da9295",
        name="Simulation Refresh",
        description="Refresh operation for Simulation",
        permission_id=sid("permission/simulation/refresh"),
        args=[],
    ),
    dict(
        id="529141c8-3942-55c7-b244-444e1fe71796",
        name="Simulation Search",
        description="Search operation for Simulation",
        permission_id=sid("permission/simulation/search"),
        args=["search", "filter_scenario_ids", "filter_cohort_ids", "filter_department_ids", "scenario_search", "cohort_search", "department_search", "flag_search", "page_size", "page_offset"],
    ),
    dict(
        id="5a29f9a2-f55a-5ade-a287-a5264d790060",
        name="Simulation Update",
        description="Update operation for Simulation",
        permission_id=sid("permission/simulation/update"),
        args=[],
    ),
    dict(
        id="0801462a-2403-517f-9de0-3120ce951af8",
        name="Test Archive",
        description="Archive operation for Test",
        permission_id=sid("permission/test/archive"),
        args=["test_ids", "archived"],
    ),
    dict(
        id="b7f58069-2153-599a-9e65-6cc750799b1d",
        name="Test End",
        description="End operation for Test",
        permission_id=sid("permission/test/end"),
        args=["test_id", "test_invocation_id", "run_id", "grade", "score", "passed", "feedback"],
    ),
    dict(
        id="c3ed0b59-1867-544e-b9f7-177863b01870",
        name="Test Export",
        description="Export operation for Test",
        permission_id=sid("permission/test/export"),
        args=["test_id"],
    ),
    dict(
        id="ce9dcdbe-e621-55e2-82a0-78cff71219ab",
        name="Test Get",
        description="Get operation for Test",
        permission_id=sid("permission/test/get"),
        args=[],
    ),
    dict(
        id="ab7d3866-bc5a-5a93-8e76-8b83f892fa3d",
        name="Test Next",
        description="Next operation for Test",
        permission_id=sid("permission/test/next"),
        args=[],
    ),
    dict(
        id="5bd7c13a-8bbf-588a-8fb9-cb52c606d157",
        name="Test Refresh",
        description="Refresh operation for Test",
        permission_id=sid("permission/test/refresh"),
        args=[],
    ),
    dict(
        id="2216bb71-2762-58f2-9d8f-78ce447429b8",
        name="Test Run",
        description="Run operation for Test",
        permission_id=sid("permission/test/run"),
        args=[],
    ),
    dict(
        id="55459dcc-5cc8-5984-a7f4-7c5888625115",
        name="Test Search",
        description="Search operation for Test",
        permission_id=sid("permission/test/search"),
        args=["test_id", "invocation_id", "benchmark_id", "run_id", "include_entries", "search", "limit", "cursor"],
    ),
    dict(
        id="c0488aef-5177-5612-b499-7a9bee6a577c",
        name="Test Start",
        description="Start operation for Test",
        permission_id=sid("permission/test/start"),
        args=[],
    ),
    dict(
        id="5aacd69e-1692-514f-a73c-e683ef687379",
        name="Test Stop",
        description="Stop operation for Test",
        permission_id=sid("permission/test/stop"),
        args=[],
    ),
    dict(
        id="547621ae-8a64-5591-8f1a-743ec675b5e6",
        name="Tool Create",
        description="Create operation for Tool",
        permission_id=sid("permission/tool/create"),
        args=[],
    ),
    dict(
        id="b798dfe8-a0cc-5e6a-924a-599dc815d060",
        name="Tool Delete",
        description="Delete operation for Tool",
        permission_id=sid("permission/tool/delete"),
        args=[],
    ),
    dict(
        id="ed62bd06-ba7c-57d4-889c-5e2e65ac0f39",
        name="Tool Draft",
        description="Draft operation for Tool",
        permission_id=sid("permission/tool/draft"),
        args=[],
    ),
    dict(
        id="a8780476-94cc-582a-98a8-fc3bd2a76542",
        name="Tool Drafts",
        description="Drafts operation for Tool",
        permission_id=sid("permission/tool/drafts"),
        args=[],
    ),
    dict(
        id="68636bce-e89c-5429-b3c6-9e9e6b43fc96",
        name="Tool Duplicate",
        description="Duplicate operation for Tool",
        permission_id=sid("permission/tool/duplicate"),
        args=[],
    ),
    dict(
        id="7f6c53c3-8c62-54a2-8362-68a3580ce8e7",
        name="Tool Export",
        description="Export operation for Tool",
        permission_id=sid("permission/tool/export"),
        args=["tool_id"],
    ),
    dict(
        id="e9a229bf-3c20-503f-9a73-df7ae233369e",
        name="Tool Get",
        description="Get operation for Tool",
        permission_id=sid("permission/tool/get"),
        args=[],
    ),
    dict(
        id="057bff07-fe88-5879-8834-fb50e840b6bc",
        name="Tool Refresh",
        description="Refresh operation for Tool",
        permission_id=sid("permission/tool/refresh"),
        args=[],
    ),
    dict(
        id="c1756625-7b22-503a-8131-096c6cc4b4dc",
        name="Tool Search",
        description="Search operation for Tool",
        permission_id=sid("permission/tool/search"),
        args=["search", "filter_department_ids", "filter_agent_ids", "filter_creatable", "department_search", "agent_search", "page_size", "page_offset"],
    ),
    dict(
        id="7a5a784a-4b6b-574b-b323-374086a74bb1",
        name="Tool Update",
        description="Update operation for Tool",
        permission_id=sid("permission/tool/update"),
        args=[],
    ),
]
