-- Foreign keys: group_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: group_names_entry group_names_entry_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_names_entry
    ADD CONSTRAINT group_names_entry_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.groups_entry(id) ON DELETE CASCADE;


--
