-- Foreign keys: invocation_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: invocation_entry benchmark_bundle_entry_benchmark_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invocation_entry
    ADD CONSTRAINT benchmark_bundle_entry_benchmark_id_fkey FOREIGN KEY (benchmark_id) REFERENCES public.benchmark_entry(id) ON DELETE CASCADE;


--
