-- Foreign keys: soft_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: soft_calls_entry soft_calls_entry_call_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.soft_calls_entry
    ADD CONSTRAINT soft_calls_entry_call_fkey FOREIGN KEY (call_id) REFERENCES public.calls_entry(id) ON DELETE CASCADE;


--
