"""Generate permissions.py seed from existing tools.py and roles.py data.

Extracts all unique (artifact, operation) combinations from:
1. tools.py — each tool has operation_id + artifact_id → look up the string values
2. roles.py — each role has artifacts → generate standard CRUD operations per artifact

Outputs: database/seeds/resources/permissions.py
"""

import sys
from pathlib import Path
from uuid import uuid5, UUID

# Setup paths
PROJECT_ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "core"))
sys.path.insert(0, str(PROJECT_ROOT))

from database.seeds.ids import sid
from database.seeds.resources.artifacts import artifacts
from database.seeds.resources.operations import operations

# Build lookup maps
artifact_by_id = {a["id"]: a["artifact"] for a in artifacts}
operation_by_id = {o["id"]: o["operation"] for o in operations}

# Collect all unique (artifact, operation) pairs
pairs: set[tuple[str, str]] = set()

# From tools
from database.seeds.tools import tools
for tool in tools:
    artifact = artifact_by_id.get(tool["artifact_id"])
    operation = operation_by_id.get(tool["operation_id"])
    if artifact and operation:
        pairs.add((artifact, operation))

# From roles — generate standard operations for each artifact
from database.seeds.resources.roles import roles
STANDARD_OPS = ["get", "search", "docs", "refresh", "export"]
CRUD_OPS = ["create", "update", "delete", "duplicate", "draft", "drafts"]

for role in roles:
    for artifact in role.get("artifacts", []):
        for op in STANDARD_OPS:
            pairs.add((artifact, op))

# Sort for deterministic output
sorted_pairs = sorted(pairs)

# Generate deterministic UUIDs
SEED_NS = UUID("a1b2c3d4-e5f6-7890-abcd-ef1234567890")

def permission_id(artifact: str, operation: str) -> UUID:
    return uuid5(SEED_NS, f"permission/{artifact}/{operation}")

# Generate output
lines = [
    '"""Permission resource seeds.',
    "",
    "Each permission is a unique (artifact, operation) tuple.",
    "Generated by: python database/scripts/generate_permissions.py",
    '"""',
    "",
    "from database.seeds.ids import sid",
    "",
    "# ---------------------------------------------------------------------------",
    "# Permission definitions — deterministic IDs via sid()",
    "# ---------------------------------------------------------------------------",
    "",
    "permissions = [",
]

# Also build a lookup for tools.py and roles.py to reference
lookup_lines = [
    "",
    "# ---------------------------------------------------------------------------",
    "# Lookup: (artifact, operation) → permission UUID",
    "# ---------------------------------------------------------------------------",
    "",
    "PERMISSION_IDS = {",
]

for artifact, operation in sorted_pairs:
    pid = f'sid("permission/{artifact}/{operation}")'
    name = f"{operation.replace('_', ' ').title()} {artifact.replace('_', ' ').title()}"
    lines.append(f"    dict(")
    lines.append(f'        id={pid},')
    lines.append(f'        artifact="{artifact}",')
    lines.append(f'        operation="{operation}",')
    lines.append(f'        name="{name}",')
    lines.append(f'    ),')
    lookup_lines.append(f'    ("{artifact}", "{operation}"): {pid},')

lines.append("]")
lookup_lines.append("}")

output = "\n".join(lines + lookup_lines) + "\n"

output_path = PROJECT_ROOT / "database" / "seeds" / "resources" / "permissions.py"
output_path.write_text(output)
print(f"Generated {len(sorted_pairs)} permissions → {output_path}")

# Also print stats
artifacts_seen = sorted(set(a for a, _ in sorted_pairs))
operations_seen = sorted(set(o for _, o in sorted_pairs))
print(f"  Artifacts: {len(artifacts_seen)}")
print(f"  Operations: {len(operations_seen)}")
