#!/usr/bin/env bash
set -euo pipefail

# =====================================================================
# Glow Database Startup
#
# Two modes:
#   backup <template>   Restore from history/<template>.sql.gz
#   continue            Use existing database as-is (no-op)
#
# Templates are auto-generated by the seed runner (make seed-gen).
# Available templates are whatever .sql.gz files exist in history/.
# =====================================================================

# --- LOAD .env -------------------------------------------------------
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
project_root="$(cd "$script_dir/../.." && pwd)"
if [[ -f "${script_dir}/../.env" ]]; then
  set -a
  source "${script_dir}/../.env"
  set +a
fi

# --- CONFIG ----------------------------------------------------------
DB_USER=${DB_USER:-myuser}
DB_PASSWORD=${DB_PASSWORD:-mypassword}
DB_NAME=${DB_NAME:-mydb}
DB_HOST=${DB_HOST:-localhost}
DB_PORT=${DB_PORT:-5432}
HISTORY_DIR="$project_root/history"

ADMIN_CONN="postgresql://postgres@${DB_HOST}:${DB_PORT}/postgres"
OWNER_CONN="postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/postgres"

# --- CHECK POSTGRESQL ------------------------------------------------
if [[ -d "/opt/homebrew/opt/postgresql@18/bin" ]]; then
  export PATH="/opt/homebrew/opt/postgresql@18/bin:$PATH"
elif [[ -d "/usr/local/opt/postgresql@18/bin" ]]; then
  export PATH="/usr/local/opt/postgresql@18/bin:$PATH"
fi

if ! command -v psql &>/dev/null; then
  echo "PostgreSQL client not found!"
  echo "Please install PostgreSQL 18: brew install postgresql@18"
  exit 1
fi

PG_VERSION=$(psql --version | grep -oE '[0-9]+\.[0-9]+' | head -1 | cut -d. -f1)
if [[ -z "$PG_VERSION" ]] || [[ "$PG_VERSION" -lt 18 ]]; then
  echo "Warning: PostgreSQL 18+ required for uuidv7() support"
  echo "  Current: $(psql --version)"
fi

if ! pg_isready -q; then
  echo "PostgreSQL server is not running!"
  echo "Start it: brew services start postgresql@18"
  exit 1
fi

# --- HELPERS ---------------------------------------------------------
as_admin()    { psql "$ADMIN_CONN" -qtA "$@"; }
as_owner()    { psql "$OWNER_CONN" -qtA "$@"; }
role_exists() { as_admin -c "SELECT 1 FROM pg_roles    WHERE rolname='$DB_USER';" | grep -q 1; }
db_exists()   { as_admin -c "SELECT 1 FROM pg_database WHERE datname='$DB_NAME';" | grep -q 1; }

setup_database() {
  echo "Setting up database and user..."

  if ! role_exists; then
    echo "  Creating user '$DB_USER'..."
    as_admin -c "CREATE USER $DB_USER WITH PASSWORD '$DB_PASSWORD' SUPERUSER;"
  else
    as_admin -c "ALTER USER $DB_USER WITH SUPERUSER;" > /dev/null 2>&1 || true
  fi

  if db_exists; then
    echo "  Dropping existing database..."
    as_owner -c "SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = '$DB_NAME' AND pid <> pg_backend_pid();" > /dev/null 2>&1 || true
    as_owner -c "DROP DATABASE $DB_NAME;" > /dev/null 2>&1
  fi

  echo "  Creating database '$DB_NAME'..."
  as_owner -c "CREATE DATABASE $DB_NAME OWNER $DB_USER;"
}

restore_from_backup() {
  local backup_file="$1"
  local temp_error_file=$(mktemp)

  echo "Restoring from: $(basename "$backup_file")"

  # Drop and recreate database
  as_owner -c "SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = '$DB_NAME' AND pid <> pg_backend_pid();" > /dev/null 2>&1 || true
  as_owner -c "DROP DATABASE IF EXISTS $DB_NAME;" > /dev/null 2>&1 || true
  as_owner -c "CREATE DATABASE $DB_NAME OWNER $DB_USER;" > /dev/null 2>&1

  export PGPASSWORD="$DB_PASSWORD"

  if [[ "$backup_file" == *.gz ]]; then
    if file "$backup_file" | grep -q "PostgreSQL custom database dump"; then
      # Custom format — use pg_restore
      if pg_restore -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -F c --no-owner "$backup_file" > /dev/null 2>"$temp_error_file"; then
        echo "Restored successfully (custom format)"
      else
        local table_count=$(psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -tAc \
          "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'public'" 2>/dev/null || echo "0")
        if [[ "$table_count" -gt 100 ]]; then
          echo "Restored successfully (with warnings)"
        else
          echo "Backup restoration failed"
          head -20 "$temp_error_file"
          rm -f "$temp_error_file"
          return 1
        fi
      fi
    else
      # Gzipped plain SQL — gunzip | psql
      if gunzip -c "$backup_file" 2>"$temp_error_file" | psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" > /dev/null 2>&1; then
        echo "Restored successfully (plain SQL)"
      else
        local table_count=$(psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -tAc \
          "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'public'" 2>/dev/null || echo "0")
        if [[ "$table_count" -gt 100 ]]; then
          echo "Restored successfully (with warnings)"
        else
          echo "Backup restoration failed"
          head -20 "$temp_error_file"
          rm -f "$temp_error_file"
          return 1
        fi
      fi
    fi
  else
    # Uncompressed SQL
    if psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -f "$backup_file" > /dev/null 2>"$temp_error_file"; then
      echo "Restored successfully"
    else
      local table_count=$(psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -tAc \
        "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'public'" 2>/dev/null || echo "0")
      if [[ "$table_count" -gt 100 ]]; then
        echo "Restored successfully (with warnings)"
      else
        echo "Backup restoration failed"
        head -20 "$temp_error_file"
        rm -f "$temp_error_file"
        return 1
      fi
    fi
  fi

  rm -f "$temp_error_file"

  # Grant permissions
  psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -c "
    GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;
    GRANT ALL PRIVILEGES ON SCHEMA public TO $DB_USER;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $DB_USER;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO $DB_USER;
  " > /dev/null 2>&1 || true
}

# List available templates from history/ folder
list_templates() {
  if [[ -d "$HISTORY_DIR" ]] && ls "$HISTORY_DIR"/*.sql.gz 1> /dev/null 2>&1; then
    for f in "$HISTORY_DIR"/*.sql.gz; do
      basename "$f" .sql.gz
    done
  fi
}

# --- MAIN LOGIC ------------------------------------------------------

MODE="${1:-}"
TEMPLATE="${2:-}"

case "$MODE" in
  backup)
    if [[ -z "$TEMPLATE" ]]; then
      echo "Usage: $0 backup <template>"
      echo ""
      echo "Available templates:"
      list_templates | while read t; do echo "  $t"; done
      exit 1
    fi

    BACKUP_FILE="$HISTORY_DIR/${TEMPLATE}.sql.gz"
    if [[ ! -f "$BACKUP_FILE" ]]; then
      echo "Template '$TEMPLATE' not found at: $BACKUP_FILE"
      echo ""
      echo "Available templates:"
      list_templates | while read t; do echo "  $t"; done
      echo ""
      echo "Run 'make seed-gen' to generate templates."
      exit 1
    fi

    setup_database
    restore_from_backup "$BACKUP_FILE"
    echo "Database ready (template: $TEMPLATE)"
    ;;

  continue)
    if db_exists; then
      echo "Using existing database '$DB_NAME'"
    else
      echo "Database '$DB_NAME' does not exist."
      echo "Use '$0 backup <template>' to create it from a template."
      exit 1
    fi
    ;;

  *)
    echo "Usage: $0 {backup <template>|continue}"
    echo ""
    echo "Modes:"
    echo "  backup <template>  Restore database from history/<template>.sql.gz"
    echo "  continue           Use existing database as-is"
    echo ""
    echo "Available templates:"
    list_templates | while read t; do echo "  $t"; done
    exit 1
    ;;
esac
