#!/usr/bin/env bash
set -euo pipefail

# =====================================================================
# Glow Database Startup
#
# Controlled by a single env var:
#   DB_BACKUP=fresh.sql.gz       Restore history/fresh.sql.gz
#   DB_BACKUP=university.sql.gz  Restore history/university.sql.gz
#   DB_BACKUP=                   Use existing database (default)
#
# Supports .sql.gz and .sql files from the history/ folder.
# Templates are generated by: make seed-gen
# =====================================================================

# --- LOAD .env -------------------------------------------------------
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
project_root="$(cd "$script_dir/../.." && pwd)"
if [[ -f "${script_dir}/../.env" ]]; then
  set -a
  source "${script_dir}/../.env"
  set +a
fi

# --- CONFIG ----------------------------------------------------------
DB_USER=${DB_USER:-myuser}
DB_PASSWORD=${DB_PASSWORD:-mypassword}
DB_NAME=${DB_NAME:-mydb}
DB_HOST=${DB_HOST:-localhost}
DB_PORT=${DB_PORT:-5432}
DB_BACKUP=${DB_BACKUP:-}
HISTORY_DIR="$project_root/history"

ADMIN_CONN="postgresql://postgres@${DB_HOST}:${DB_PORT}/postgres"
OWNER_CONN="postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/postgres"

# --- CHECK POSTGRESQL ------------------------------------------------
if [[ -d "/opt/homebrew/opt/postgresql@18/bin" ]]; then
  export PATH="/opt/homebrew/opt/postgresql@18/bin:$PATH"
elif [[ -d "/usr/local/opt/postgresql@18/bin" ]]; then
  export PATH="/usr/local/opt/postgresql@18/bin:$PATH"
fi

if ! command -v psql &>/dev/null; then
  echo "PostgreSQL client not found!"
  echo "Please install PostgreSQL 18: brew install postgresql@18"
  exit 1
fi

PG_VERSION=$(psql --version | grep -oE '[0-9]+\.[0-9]+' | head -1 | cut -d. -f1)
if [[ -z "$PG_VERSION" ]] || [[ "$PG_VERSION" -lt 18 ]]; then
  echo "Warning: PostgreSQL 18+ required for uuidv7() support"
  echo "  Current: $(psql --version)"
fi

if ! pg_isready -q; then
  echo "PostgreSQL server is not running!"
  echo "Start it: brew services start postgresql@18"
  exit 1
fi

# --- HELPERS ---------------------------------------------------------
as_admin()    { psql "$ADMIN_CONN" -qtA "$@"; }
as_owner()    { psql "$OWNER_CONN" -qtA "$@"; }
role_exists() { as_admin -c "SELECT 1 FROM pg_roles    WHERE rolname='$DB_USER';" | grep -q 1; }
db_exists()   { as_admin -c "SELECT 1 FROM pg_database WHERE datname='$DB_NAME';" | grep -q 1; }

setup_role() {
  if ! role_exists; then
    echo "  Creating user '$DB_USER'..."
    as_admin -c "CREATE USER $DB_USER WITH PASSWORD '$DB_PASSWORD' SUPERUSER;"
  else
    as_admin -c "ALTER USER $DB_USER WITH SUPERUSER;" > /dev/null 2>&1 || true
  fi
}

restore() {
  local backup_file="$1"
  local temp_error_file=$(mktemp)

  echo "Restoring from: $(basename "$backup_file")"

  # Drop and recreate database
  setup_role
  as_owner -c "SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = '$DB_NAME' AND pid <> pg_backend_pid();" > /dev/null 2>&1 || true
  as_owner -c "DROP DATABASE IF EXISTS $DB_NAME;" > /dev/null 2>&1 || true
  as_owner -c "CREATE DATABASE $DB_NAME OWNER $DB_USER;" > /dev/null 2>&1

  export PGPASSWORD="$DB_PASSWORD"

  if [[ "$backup_file" == *.gz ]]; then
    # Gzipped SQL — gunzip | psql
    gunzip -c "$backup_file" 2>"$temp_error_file" \
      | psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" > /dev/null 2>&1
  else
    # Plain SQL
    psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" \
      -f "$backup_file" > /dev/null 2>"$temp_error_file"
  fi

  # Verify
  local table_count=$(psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -tAc \
    "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'public'" 2>/dev/null || echo "0")

  rm -f "$temp_error_file"

  if [[ "$table_count" -gt 0 ]]; then
    echo "Restored ($table_count tables)"
  else
    echo "Restore failed — no tables found"
    exit 1
  fi
}

# --- MAIN ------------------------------------------------------------

if [[ -n "$DB_BACKUP" ]]; then
  BACKUP_FILE="$HISTORY_DIR/$DB_BACKUP"

  if [[ ! -f "$BACKUP_FILE" ]]; then
    echo "Backup not found: $BACKUP_FILE"
    echo ""
    echo "Available in history/:"
    ls "$HISTORY_DIR"/*.sql.gz "$HISTORY_DIR"/*.sql 2>/dev/null | xargs -I{} basename {} || true
    exit 1
  fi

  restore "$BACKUP_FILE"
else
  if db_exists; then
    echo "Using existing database '$DB_NAME'"
  else
    echo "No database '$DB_NAME' and DB_BACKUP is not set."
    echo ""
    echo "Set DB_BACKUP to a file in history/:"
    ls "$HISTORY_DIR"/*.sql.gz "$HISTORY_DIR"/*.sql 2>/dev/null | xargs -I{} basename {} || true
    exit 1
  fi
fi
