-- Indexes: profile_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_profile_drafts_departments_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_profile_drafts_departments_resource_id ON public.profile_drafts_departments_connection USING btree (departments_id);


--

-- Name: idx_profile_drafts_emails_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_profile_drafts_emails_resource_id ON public.profile_drafts_emails_connection USING btree (emails_id);


--

-- Name: idx_profile_drafts_flags_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_profile_drafts_flags_resource_id ON public.profile_drafts_flags_connection USING btree (flags_id);


--

-- Name: idx_profile_drafts_names_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_profile_drafts_names_resource_id ON public.profile_drafts_names_connection USING btree (names_id);


--

-- Name: idx_profile_drafts_primary_departments_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_profile_drafts_primary_departments_resource_id ON public.profile_drafts_primary_departments_connection USING btree (primary_departments_id);


--

-- Name: idx_profile_drafts_roles_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_profile_drafts_roles_resource_id ON public.profile_drafts_roles_connection USING btree (roles_id);


--
