-- Indexes: provider_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_provider_drafts_departments_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_provider_drafts_departments_resource_id ON public.provider_drafts_departments_connection USING btree (departments_id);


--

-- Name: idx_provider_drafts_descriptions_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_provider_drafts_descriptions_resource_id ON public.provider_drafts_descriptions_connection USING btree (descriptions_id);


--

-- Name: idx_provider_drafts_endpoints_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_provider_drafts_endpoints_resource_id ON public.provider_drafts_endpoints_connection USING btree (endpoints_id);


--

-- Name: idx_provider_drafts_flags_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_provider_drafts_flags_resource_id ON public.provider_drafts_flags_connection USING btree (flags_id);


--

-- Name: idx_provider_drafts_keys_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_provider_drafts_keys_resource_id ON public.provider_drafts_keys_connection USING btree (keys_id);


--

-- Name: idx_provider_drafts_names_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_provider_drafts_names_resource_id ON public.provider_drafts_names_connection USING btree (names_id);


--

-- Name: idx_provider_drafts_profiles_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_provider_drafts_profiles_resource_id ON public.provider_drafts_profiles_connection USING btree (profiles_id);


--

-- Name: idx_provider_drafts_values_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_provider_drafts_values_resource_id ON public.provider_drafts_values_connection USING btree (values_id);


--
