-- Indexes: scenario_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_scenario_drafts_departments_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scenario_drafts_departments_resource_id ON public.scenario_drafts_departments_connection USING btree (departments_id);


--

-- Name: idx_scenario_drafts_descriptions_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scenario_drafts_descriptions_resource_id ON public.scenario_drafts_descriptions_connection USING btree (descriptions_id);


--

-- Name: idx_scenario_drafts_documents_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scenario_drafts_documents_resource_id ON public.scenario_drafts_documents_connection USING btree (documents_id);


--

-- Name: idx_scenario_drafts_flags_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scenario_drafts_flags_resource_id ON public.scenario_drafts_flags_connection USING btree (flags_id);


--

-- Name: idx_scenario_drafts_images_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scenario_drafts_images_resource_id ON public.scenario_drafts_images_connection USING btree (images_id);


--

-- Name: idx_scenario_drafts_names_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scenario_drafts_names_resource_id ON public.scenario_drafts_names_connection USING btree (names_id);


--

-- Name: idx_scenario_drafts_objectives_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scenario_drafts_objectives_resource_id ON public.scenario_drafts_objectives_connection USING btree (objectives_id);


--

-- Name: idx_scenario_drafts_options_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scenario_drafts_options_resource_id ON public.scenario_drafts_options_connection USING btree (options_id);


--

-- Name: idx_scenario_drafts_parameter_fields_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scenario_drafts_parameter_fields_resource_id ON public.scenario_drafts_parameter_fields_connection USING btree (parameter_fields_id);


--

-- Name: idx_scenario_drafts_personas_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scenario_drafts_personas_resource_id ON public.scenario_drafts_personas_connection USING btree (personas_id);


--

-- Name: idx_scenario_drafts_problem_statements_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scenario_drafts_problem_statements_resource_id ON public.scenario_drafts_problem_statements_connection USING btree (problem_statements_id);


--

-- Name: idx_scenario_drafts_profiles_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scenario_drafts_profiles_resource_id ON public.scenario_drafts_profiles_connection USING btree (profiles_id);


--

-- Name: idx_scenario_drafts_questions_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scenario_drafts_questions_resource_id ON public.scenario_drafts_questions_connection USING btree (questions_id);


--

-- Name: idx_scenario_drafts_videos_resource_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scenario_drafts_videos_resource_id ON public.scenario_drafts_videos_connection USING btree (videos_id);


--
