-- Indexes: test_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_benchmark_tests_departments_departments_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_benchmark_tests_departments_departments_id ON public.test_departments_connection USING btree (departments_id);


--

-- Name: idx_benchmark_tests_evals_evals_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_benchmark_tests_evals_evals_id ON public.test_evals_connection USING btree (evals_id);


--

-- Name: idx_benchmark_tests_profiles_profiles_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_benchmark_tests_profiles_profiles_id ON public.test_profiles_connection USING btree (profiles_id);


--

-- Name: idx_benchmark_tests_roles_roles_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_benchmark_tests_roles_roles_id ON public.test_roles_connection USING btree (roles_id);


--

-- Name: idx_test_invocation_departments_connection_test_invocation_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_test_invocation_departments_connection_test_invocation_id ON public.test_invocation_departments_connection USING btree (test_invocation_id);


--
