-- Indexes: texts_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_texts_texts_connection_text_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_texts_texts_connection_text_id ON public.texts_texts_connection USING btree (text_id);


--

-- Name: idx_texts_texts_connection_texts_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_texts_texts_connection_texts_id ON public.texts_texts_connection USING btree (texts_id);


--
