-- Table definitions + constraints: group_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: group_names_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.group_names_entry (
    id uuid DEFAULT uuidv7() NOT NULL,
    group_id uuid NOT NULL,
    name text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    session_id uuid NOT NULL
);


--

-- Name: group_names_entry group_names_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_names_entry
    ADD CONSTRAINT group_names_entry_pkey PRIMARY KEY (id);


--
