-- Table definitions + constraints: logouts_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: logouts_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.logouts_entry (
    id uuid DEFAULT uuidv7() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL,
    session_id uuid NOT NULL
);


--

-- Name: logouts_entry logouts_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.logouts_entry
    ADD CONSTRAINT logouts_entry_pkey PRIMARY KEY (id);


--
