-- Table definitions + constraints: refreshes_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: refreshes_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refreshes_entry (
    id uuid DEFAULT uuidv7() CONSTRAINT refresh_entry_id_not_null NOT NULL,
    operation_key uuid CONSTRAINT refresh_entry_operation_key_not_null NOT NULL,
    artifact_type public.artifact_type CONSTRAINT refresh_entry_artifact_type_not_null NOT NULL,
    target text CONSTRAINT refresh_entry_target_not_null NOT NULL,
    session_id uuid CONSTRAINT refresh_entry_session_id_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT refresh_entry_created_at_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT refresh_entry_active_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT refresh_entry_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT refresh_entry_mcp_not_null NOT NULL
);


--

-- Name: refreshes_entry refreshes_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refreshes_entry
    ADD CONSTRAINT refreshes_entry_pkey PRIMARY KEY (id);


--
