-- Table definitions + constraints: refresh_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: refresh_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_entry (
    id uuid DEFAULT uuidv7() NOT NULL,
    operation_key uuid NOT NULL,
    artifact_type public.artifact_type NOT NULL,
    target text NOT NULL,
    session_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--

-- Name: refresh_entry refresh_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_entry
    ADD CONSTRAINT refresh_entry_pkey PRIMARY KEY (id);


--
