-- Table definitions + constraints: setting_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: setting_drafts_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.setting_drafts_entry (
    id uuid DEFAULT uuidv7() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL,
    session_id uuid NOT NULL,
    name text DEFAULT ''::text NOT NULL
);


--

-- Name: setting_drafts_entry setting_drafts_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.setting_drafts_entry
    ADD CONSTRAINT setting_drafts_entry_pkey PRIMARY KEY (id);


--
