-- Table definitions + constraints: soft_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: soft_calls_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.soft_calls_entry (
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    id uuid DEFAULT uuidv7() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL,
    call_id uuid NOT NULL,
    artifact text NOT NULL,
    operation text NOT NULL,
    status text NOT NULL,
    artifact_id uuid NOT NULL,
    patch jsonb,
    CONSTRAINT soft_calls_entry_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'accepted'::text, 'rejected'::text])))
);


--

-- Name: soft_calls_entry soft_calls_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.soft_calls_entry
    ADD CONSTRAINT soft_calls_entry_pkey PRIMARY KEY (id);


--
