-- Table definitions + constraints: tool_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: tool_drafts_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tool_drafts_entry (
    id uuid DEFAULT uuidv7() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL,
    session_id uuid NOT NULL,
    name text DEFAULT ''::text NOT NULL
);


--

-- Name: tool_drafts_entry tool_drafts_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_drafts_entry
    ADD CONSTRAINT tool_drafts_entry_pkey PRIMARY KEY (id);


--
