"""Shared argument resource seeds.

Each arg is defined once with a deterministic ID. Tools reference args
by key instead of inlining duplicate definitions.

Generated from 137 unique args across 259 tools.
Regenerate with: python database/scripts/generate_shared_args.py
"""

from database.seeds.ids import sid

SHARED_ARGS = {
    "active": dict(id=sid("arg/active"), name="active", field_type="boolean"),
    "actor_profile_id": dict(id=sid("arg/actor_profile_id"), name="actor_profile_id", field_type="uuid"),
    "artifact": dict(id=sid("arg/artifact"), name="artifact", field_type="string", description="Target artifact type (e.g. persona, scenario)"),
    "operation": dict(id=sid("arg/operation"), name="operation", field_type="string", description="Target operation (e.g. create, update)"),
    "name": dict(id=sid("arg/name"), name="name", field_type="string", description="Display name"),
    "description": dict(id=sid("arg/description"), name="description", field_type="string", description="Description text"),
    "instructions": dict(id=sid("arg/instructions"), name="instructions", field_type="string", description="Instruction template"),
    "color": dict(id=sid("arg/color"), name="color", field_type="string", description="Color value"),
    "content": dict(id=sid("arg/content"), name="content", field_type="string", description="Text content"),
    "icon": dict(id=sid("arg/icon"), name="icon", field_type="string", description="Icon identifier"),
    "image": dict(id=sid("arg/image"), name="image", field_type="string", description="Base64-encoded image data"),
    "image_id": dict(id=sid("arg/image_id"), name="image_id", field_type="uuid", description="Image resource UUID"),
    "length_seconds": dict(id=sid("arg/length_seconds"), name="length_seconds", field_type="integer", description="Duration of audio in seconds"),
    "muted": dict(id=sid("arg/muted"), name="muted", field_type="boolean", description="Whether to mute the microphone"),
    "problem_statement": dict(id=sid("arg/problem_statement"), name="problem_statement", field_type="string", description="Problem statement text"),
    "agent_search": dict(id=sid("arg/agent_search"), name="agent_search", field_type="string"),
    "analyses": dict(id=sid("arg/analyses"), name="analyses", field_type="object[]"),
    "archived": dict(id=sid("arg/archived"), name="archived", field_type="boolean", required=True),
    "assistant_content": dict(id=sid("arg/assistant_content"), name="assistant_content", field_type="string"),
    "attempt_id": dict(id=sid("arg/attempt_id"), name="attempt_id", field_type="uuid", required=True),
    "audio": dict(id=sid("arg/audio"), name="audio", field_type="string", description="Base64-encoded audio data"),
    "audio_id": dict(id=sid("arg/audio_id"), name="audio_id", field_type="uuid", description="Audio resource UUID"),
    "attempt_ids": dict(id=sid("arg/attempt_ids"), name="attempt_ids", field_type="uuid[]"),
    "auth_id": dict(id=sid("arg/auth_id"), name="auth_id", field_type="uuid"),
    "benchmark_id": dict(id=sid("arg/benchmark_id"), name="benchmark_id", field_type="uuid"),
    "chat_entry_id": dict(id=sid("arg/chat_entry_id"), name="chat_entry_id", field_type="uuid", required=True),
    "call_id": dict(id=sid("arg/call_id"), name="call_id", field_type="uuid", description="Call entry UUID"),
    "chat_id": dict(id=sid("arg/chat_id"), name="chat_id", field_type="uuid", required=True),
    "cohort_id": dict(id=sid("arg/cohort_id"), name="cohort_id", field_type="uuid"),
    "cohort_ids": dict(id=sid("arg/cohort_ids"), name="cohort_ids", field_type="uuid[]"),
    "cohort_search": dict(id=sid("arg/cohort_search"), name="cohort_search", field_type="string"),
    "color_search": dict(id=sid("arg/color_search"), name="color_search", field_type="string"),
    "contents": dict(id=sid("arg/contents"), name="contents", field_type="object[]"),
    "cursor": dict(id=sid("arg/cursor"), name="cursor", field_type="string"),
    "date_from": dict(id=sid("arg/date_from"), name="date_from", field_type="string"),
    "date_to": dict(id=sid("arg/date_to"), name="date_to", field_type="string"),
    "department_id": dict(id=sid("arg/department_id"), name="department_id", field_type="uuid"),
    "department_ids": dict(id=sid("arg/department_ids"), name="department_ids", field_type="string[]"),
    "department_search": dict(id=sid("arg/department_search"), name="department_search", field_type="string"),
    "descriptions_search": dict(id=sid("arg/descriptions_search"), name="descriptions_search", field_type="string"),
    "document_id": dict(id=sid("arg/document_id"), name="document_id", field_type="uuid"),
    "draft_id": dict(id=sid("arg/draft_id"), name="draft_id", field_type="uuid"),
    "end_date": dict(id=sid("arg/end_date"), name="end_date", field_type="string"),
    "eval_id": dict(id=sid("arg/eval_id"), name="eval_id", field_type="uuid"),
    "feedback": dict(id=sid("arg/feedback"), name="feedback", field_type="string"),
    "feedbacks": dict(id=sid("arg/feedbacks"), name="feedbacks", field_type="object[]"),
    "file": dict(id=sid("arg/file"), name="file", field_type="string", description="Base64-encoded file data"),
    "file_id": dict(id=sid("arg/file_id"), name="file_id", field_type="uuid", description="File resource UUID"),
    "field_id": dict(id=sid("arg/field_id"), name="field_id", field_type="uuid"),
    "field_ids": dict(id=sid("arg/field_ids"), name="field_ids", field_type="uuid[]"),
    "field_search": dict(id=sid("arg/field_search"), name="field_search", field_type="string"),
    "filter_agent_ids": dict(id=sid("arg/filter_agent_ids"), name="filter_agent_ids", field_type="uuid[]"),
    "filter_cohort_ids": dict(id=sid("arg/filter_cohort_ids"), name="filter_cohort_ids", field_type="uuid[]"),
    "filter_creatable": dict(id=sid("arg/filter_creatable"), name="filter_creatable", field_type="string[]"),
    "filter_department_ids": dict(id=sid("arg/filter_department_ids"), name="filter_department_ids", field_type="uuid[]"),
    "filter_model_ids": dict(id=sid("arg/filter_model_ids"), name="filter_model_ids", field_type="uuid[]"),
    "filter_profile_ids": dict(id=sid("arg/filter_profile_ids"), name="filter_profile_ids", field_type="uuid[]"),
    "filter_provider_ids": dict(id=sid("arg/filter_provider_ids"), name="filter_provider_ids", field_type="uuid[]"),
    "filter_scenario_ids": dict(id=sid("arg/filter_scenario_ids"), name="filter_scenario_ids", field_type="uuid[]"),
    "filter_simulation_ids": dict(id=sid("arg/filter_simulation_ids"), name="filter_simulation_ids", field_type="uuid[]"),
    "filter_status": dict(id=sid("arg/filter_status"), name="filter_status", field_type="string[]"),
    "filter_tool_ids": dict(id=sid("arg/filter_tool_ids"), name="filter_tool_ids", field_type="uuid[]"),
    "flag_search": dict(id=sid("arg/flag_search"), name="flag_search", field_type="string"),
    "grade": dict(id=sid("arg/grade"), name="grade", field_type="boolean"),
    "grade_id": dict(id=sid("arg/grade_id"), name="grade_id", field_type="uuid", description="Grade entry UUID"),
    "group_id": dict(id=sid("arg/group_id"), name="group_id", field_type="uuid", required=True),
    "id": dict(id=sid("arg/id"), name="id", field_type="uuid", description="Resource UUID"),
    "ids": dict(id=sid("arg/ids"), name="ids", field_type="uuid[]", description="Resource UUIDs"),
    "highlights": dict(id=sid("arg/highlights"), name="highlights", field_type="object[]"),
    "hints": dict(id=sid("arg/hints"), name="hints", field_type="object[]"),
    "history_archived": dict(id=sid("arg/history_archived"), name="history_archived", field_type="boolean"),
    "history_eval_ids": dict(id=sid("arg/history_eval_ids"), name="history_eval_ids", field_type="string[]"),
    "history_infinite_mode": dict(id=sid("arg/history_infinite_mode"), name="history_infinite_mode", field_type="boolean"),
    "history_page": dict(id=sid("arg/history_page"), name="history_page", field_type="integer"),
    "history_page_size": dict(id=sid("arg/history_page_size"), name="history_page_size", field_type="integer"),
    "history_practice": dict(id=sid("arg/history_practice"), name="history_practice", field_type="boolean"),
    "history_profile_search": dict(id=sid("arg/history_profile_search"), name="history_profile_search", field_type="string"),
    "history_scenario_ids": dict(id=sid("arg/history_scenario_ids"), name="history_scenario_ids", field_type="uuid[]"),
    "history_scenario_search": dict(id=sid("arg/history_scenario_search"), name="history_scenario_search", field_type="string"),
    "history_search": dict(id=sid("arg/history_search"), name="history_search", field_type="string"),
    "history_show_archived": dict(id=sid("arg/history_show_archived"), name="history_show_archived", field_type="boolean"),
    "history_simulation_search": dict(id=sid("arg/history_simulation_search"), name="history_simulation_search", field_type="string"),
    "history_sort_by": dict(id=sid("arg/history_sort_by"), name="history_sort_by", field_type="string"),
    "history_sort_order": dict(id=sid("arg/history_sort_order"), name="history_sort_order", field_type="string"),
    "home_id": dict(id=sid("arg/home_id"), name="home_id", field_type="uuid"),
    "icon_search": dict(id=sid("arg/icon_search"), name="icon_search", field_type="string"),
    "improvements": dict(id=sid("arg/improvements"), name="improvements", field_type="object[]"),
    "include_entries": dict(id=sid("arg/include_entries"), name="include_entries", field_type="string[]"),
    "infinite_mode": dict(id=sid("arg/infinite_mode"), name="infinite_mode", field_type="boolean"),
    "instruction_search": dict(id=sid("arg/instruction_search"), name="instruction_search", field_type="string"),
    "invocation_entry_id": dict(id=sid("arg/invocation_entry_id"), name="invocation_entry_id", field_type="uuid"),
    "invocation_id": dict(id=sid("arg/invocation_id"), name="invocation_id", field_type="uuid"),
    "limit": dict(id=sid("arg/limit"), name="limit", field_type="integer"),
    "message": dict(id=sid("arg/message"), name="message", field_type="string", required=True),
    "message_id": dict(id=sid("arg/message_id"), name="message_id", field_type="uuid", description="UUID of the message"),
    "message_limit": dict(id=sid("arg/message_limit"), name="message_limit", field_type="integer"),
    "message_offset": dict(id=sid("arg/message_offset"), name="message_offset", field_type="integer"),
    "model_id": dict(id=sid("arg/model_id"), name="model_id", field_type="uuid"),
    "model_search": dict(id=sid("arg/model_search"), name="model_search", field_type="string"),
    "page": dict(id=sid("arg/page"), name="page", field_type="integer"),
    "page_limit": dict(id=sid("arg/page_limit"), name="page_limit", field_type="integer"),
    "page_offset": dict(id=sid("arg/page_offset"), name="page_offset", field_type="integer"),
    "page_size": dict(id=sid("arg/page_size"), name="page_size", field_type="integer"),
    "parameter_id": dict(id=sid("arg/parameter_id"), name="parameter_id", field_type="uuid"),
    "parameter_ids": dict(id=sid("arg/parameter_ids"), name="parameter_ids", field_type="uuid[]"),
    "parameter_search": dict(id=sid("arg/parameter_search"), name="parameter_search", field_type="string"),
    "parent_message_id": dict(id=sid("arg/parent_message_id"), name="parent_message_id", field_type="uuid"),
    "pass_points": dict(id=sid("arg/pass_points"), name="pass_points", field_type="integer", description="Pass threshold points for rubric criterion"),
    "passed": dict(id=sid("arg/passed"), name="passed", field_type="boolean"),
    "persona_ids": dict(id=sid("arg/persona_ids"), name="persona_ids", field_type="uuid[]"),
    "persona_search": dict(id=sid("arg/persona_search"), name="persona_search", field_type="string"),
    "practice": dict(id=sid("arg/practice"), name="practice", field_type="boolean"),
    "practice_id": dict(id=sid("arg/practice_id"), name="practice_id", field_type="uuid"),
    "problem_id": dict(id=sid("arg/problem_id"), name="problem_id", field_type="uuid", required=True),
    "profile_export_id": dict(id=sid("arg/profile_export_id"), name="profile_export_id", field_type="uuid"),
    "profile_ids": dict(id=sid("arg/profile_ids"), name="profile_ids", field_type="uuid[]"),
    "profile_ids_filter": dict(id=sid("arg/profile_ids_filter"), name="profile_ids_filter", field_type="uuid[]"),
    "profile_search": dict(id=sid("arg/profile_search"), name="profile_search", field_type="string"),
    "profile_show_selected": dict(id=sid("arg/profile_show_selected"), name="profile_show_selected", field_type="boolean"),
    "provider_id": dict(id=sid("arg/provider_id"), name="provider_id", field_type="uuid"),
    "provider_search": dict(id=sid("arg/provider_search"), name="provider_search", field_type="string"),
    "replacements": dict(id=sid("arg/replacements"), name="replacements", field_type="object[]"),
    "resolved": dict(id=sid("arg/resolved"), name="resolved", field_type="boolean"),
    "resource_types": dict(id=sid("arg/resource_types"), name="resource_types", field_type="string[]"),
    "role_filter": dict(id=sid("arg/role_filter"), name="role_filter", field_type="string"),
    "role_search": dict(id=sid("arg/role_search"), name="role_search", field_type="string"),
    "roles": dict(id=sid("arg/roles"), name="roles", field_type="string[]"),
    "rubric_id": dict(id=sid("arg/rubric_id"), name="rubric_id", field_type="uuid"),
    "rubric_ids": dict(id=sid("arg/rubric_ids"), name="rubric_ids", field_type="uuid[]"),
    "rubric_search": dict(id=sid("arg/rubric_search"), name="rubric_search", field_type="string"),
    "run_id": dict(id=sid("arg/run_id"), name="run_id", field_type="uuid", required=True),
    "scenario_ids": dict(id=sid("arg/scenario_ids"), name="scenario_ids", field_type="uuid[]"),
    "scenario_search": dict(id=sid("arg/scenario_search"), name="scenario_search", field_type="string"),
    "score": dict(id=sid("arg/score"), name="score", field_type="integer"),
    "search": dict(id=sid("arg/search"), name="search", field_type="string"),
    "service": dict(id=sid("arg/service"), name="service", field_type="string"),
    "setting_id": dict(id=sid("arg/setting_id"), name="setting_id", field_type="uuid"),
    "show_archived": dict(id=sid("arg/show_archived"), name="show_archived", field_type="boolean"),
    "simulation_filters": dict(id=sid("arg/simulation_filters"), name="simulation_filters", field_type="string[]"),
    "simulation_id": dict(id=sid("arg/simulation_id"), name="simulation_id", field_type="uuid"),
    "simulation_ids": dict(id=sid("arg/simulation_ids"), name="simulation_ids", field_type="uuid[]"),
    "simulation_picker_ids": dict(id=sid("arg/simulation_picker_ids"), name="simulation_picker_ids", field_type="uuid[]"),
    "simulation_picker_search": dict(id=sid("arg/simulation_picker_search"), name="simulation_picker_search", field_type="string"),
    "simulation_search": dict(id=sid("arg/simulation_search"), name="simulation_search", field_type="string"),
    "simulation_show_selected": dict(id=sid("arg/simulation_show_selected"), name="simulation_show_selected", field_type="boolean"),
    "sort_by": dict(id=sid("arg/sort_by"), name="sort_by", field_type="string"),
    "standard_group_id": dict(id=sid("arg/standard_group_id"), name="standard_group_id", field_type="uuid", description="Standard group UUID for feedback criterion"),
    "standard_id": dict(id=sid("arg/standard_id"), name="standard_id", field_type="uuid", description="Standard UUID — the rubric level that best matches performance"),
    "sort_order": dict(id=sid("arg/sort_order"), name="sort_order", field_type="string"),
    "start_date": dict(id=sid("arg/start_date"), name="start_date", field_type="string"),
    "strengths": dict(id=sid("arg/strengths"), name="strengths", field_type="object[]"),
    "target_profile_id": dict(id=sid("arg/target_profile_id"), name="target_profile_id", field_type="uuid"),
    "target_session_id": dict(id=sid("arg/target_session_id"), name="target_session_id", field_type="uuid", required=True),
    "test_id": dict(id=sid("arg/test_id"), name="test_id", field_type="uuid", required=True),
    "text_id": dict(id=sid("arg/text_id"), name="text_id", field_type="uuid", description="Text resource UUID"),
    "test_ids": dict(id=sid("arg/test_ids"), name="test_ids", field_type="uuid[]", required=True),
    "test_invocation_id": dict(id=sid("arg/test_invocation_id"), name="test_invocation_id", field_type="uuid", required=True),
    "time_taken": dict(id=sid("arg/time_taken"), name="time_taken", field_type="integer"),
    "tool_id": dict(id=sid("arg/tool_id"), name="tool_id", field_type="uuid"),
    "tool_search": dict(id=sid("arg/tool_search"), name="tool_search", field_type="string"),
    "type": dict(id=sid("arg/type"), name="type", field_type="string", required=True),
    "user_instructions": dict(id=sid("arg/user_instructions"), name="user_instructions", field_type="string[]"),
    "video": dict(id=sid("arg/video"), name="video", field_type="string", description="Base64-encoded video data"),
    "video_id": dict(id=sid("arg/video_id"), name="video_id", field_type="uuid", description="Video resource UUID"),
    "voice_search": dict(id=sid("arg/voice_search"), name="voice_search", field_type="string"),

    # --- Auto-generated from API request types ---
"active_flag": dict(id=sid("arg/active_flag"), name="active_flag", field_type="boolean", description="Whether the auth provider is active"),
    "active_flag_id": dict(id=sid("arg/active_flag_id"), name="active_flag_id", field_type="uuid", description="UUID of the active flag option"),
    "agent_id": dict(id=sid("arg/agent_id"), name="agent_id", field_type="uuid", description="UUID of the agent to duplicate"),
    "agent_ids": dict(id=sid("arg/agent_ids"), name="agent_ids", field_type="uuid[]", description="Associated agent resource UUIDs"),
    "arg_ids": dict(id=sid("arg/arg_ids"), name="arg_ids", field_type="uuid[]", description="Argument identifiers"),
    "arg_position_ids": dict(id=sid("arg/arg_position_ids"), name="arg_position_ids", field_type="uuid[]", description="Argument position identifiers"),
    "arg_positions_ids": dict(id=sid("arg/arg_positions_ids"), name="arg_positions_ids", field_type="uuid[]", description="Argument position identifiers"),
    "args_ids": dict(id=sid("arg/args_ids"), name="args_ids", field_type="uuid[]", description="Argument identifiers"),
    "args_output_ids": dict(id=sid("arg/args_output_ids"), name="args_output_ids", field_type="uuid[]", description="Argument output identifiers"),
    "args_outputs_ids": dict(id=sid("arg/args_outputs_ids"), name="args_outputs_ids", field_type="uuid[]", description="Argument output identifiers"),
    "auth_ids": dict(id=sid("arg/auth_ids"), name="auth_ids", field_type="uuid[]", description="UUIDs of auth providers to delete"),
    "auth_item_key_ids": dict(id=sid("arg/auth_item_key_ids"), name="auth_item_key_ids", field_type="uuid[]", description="Auth item key UUIDs"),
    "auth_item_value_ids": dict(id=sid("arg/auth_item_value_ids"), name="auth_item_value_ids", field_type="uuid[]", description="Auth item value UUIDs"),
    "auth_resource_ids": dict(id=sid("arg/auth_resource_ids"), name="auth_resource_ids", field_type="uuid[]", description="Auth resource UUIDs"),
    "color_id": dict(id=sid("arg/color_id"), name="color_id", field_type="uuid", description="UUID of an existing color resource"),
    "color_ids": dict(id=sid("arg/color_ids"), name="color_ids", field_type="uuid[]", description="Color resource UUIDs"),
    "conditional_parameter_ids": dict(id=sid("arg/conditional_parameter_ids"), name="conditional_parameter_ids", field_type="uuid[]", description="Conditional parameter UUIDs"),
    "departments": dict(id=sid("arg/departments"), name="departments", field_type="string[]", description="Department names to resolve"),
    "description_id": dict(id=sid("arg/description_id"), name="description_id", field_type="uuid", description="UUID of the description resource"),
    "description_ids": dict(id=sid("arg/description_ids"), name="description_ids", field_type="uuid[]", description="Selected description IDs"),
    "document_ids": dict(id=sid("arg/document_ids"), name="document_ids", field_type="uuid[]", description="Selected document resource IDs"),
    "documents": dict(id=sid("arg/documents"), name="documents", field_type="string[]", description="Document names for matching"),
    "email": dict(id=sid("arg/email"), name="email", field_type="string", description="Email value to resolve or create"),
    "email_ids": dict(id=sid("arg/email_ids"), name="email_ids", field_type="uuid[]", description="Email resource UUIDs"),
    "endpoint": dict(id=sid("arg/endpoint"), name="endpoint", field_type="string", description="Provider API endpoint URL"),
    "endpoint_ids": dict(id=sid("arg/endpoint_ids"), name="endpoint_ids", field_type="uuid[]", description="Selected endpoint IDs"),
    "eval_ids": dict(id=sid("arg/eval_ids"), name="eval_ids", field_type="uuid[]", description="Eval UUIDs to delete"),
    "example_ids": dict(id=sid("arg/example_ids"), name="example_ids", field_type="uuid[]", description="Existing example resource UUIDs to associate"),
    "examples": dict(id=sid("arg/examples"), name="examples", field_type="string[]", description="Example texts"),
    "expected_version": dict(id=sid("arg/expected_version"), name="expected_version", field_type="integer", description="Expected draft version for optimistic lock"),
    "file_ids": dict(id=sid("arg/file_ids"), name="file_ids", field_type="uuid[]", description="Existing file resource UUIDs"),
    "files": dict(id=sid("arg/files"), name="files", field_type="string", description="File values to create resources"),
    "flag_id": dict(id=sid("arg/flag_id"), name="flag_id", field_type="uuid", description="UUID of the flag option"),
    "flag_ids": dict(id=sid("arg/flag_ids"), name="flag_ids", field_type="uuid[]", description="Selected flag IDs"),
    "icon_id": dict(id=sid("arg/icon_id"), name="icon_id", field_type="uuid", description="UUID of an existing icon resource"),
    "image_ids": dict(id=sid("arg/image_ids"), name="image_ids", field_type="uuid[]", description="Selected image resource IDs"),
    "images": dict(id=sid("arg/images"), name="images", field_type="string", description="Image values to create"),
    "images_enabled_flag": dict(id=sid("arg/images_enabled_flag"), name="images_enabled_flag", field_type="boolean", description="Whether images are enabled"),
    "images_enabled_flag_id": dict(id=sid("arg/images_enabled_flag_id"), name="images_enabled_flag_id", field_type="uuid", description="UUID of the images enabled flag option"),
    "input_draft_id": dict(id=sid("arg/input_draft_id"), name="input_draft_id", field_type="uuid", description="Input draft ID to update"),
    "instruction_ids": dict(id=sid("arg/instruction_ids"), name="instruction_ids", field_type="uuid[]", description="Instruction template resource UUIDs"),
    "instructions_id": dict(id=sid("arg/instructions_id"), name="instructions_id", field_type="uuid", description="UUID of an existing instruction resource"),
    "is_primary": dict(id=sid("arg/is_primary"), name="is_primary", field_type="boolean", description="Whether this is the primary department"),
    "item_ids": dict(id=sid("arg/item_ids"), name="item_ids", field_type="uuid[]", description="Auth item UUIDs"),
    "key": dict(id=sid("arg/key"), name="key", field_type="string", description="Provider API key"),
    "key_ids": dict(id=sid("arg/key_ids"), name="key_ids", field_type="uuid[]", description="Selected key IDs"),
    "modality_ids": dict(id=sid("arg/modality_ids"), name="modality_ids", field_type="uuid[]", description="Modality identifiers"),
    "model_flag_ids": dict(id=sid("arg/model_flag_ids"), name="model_flag_ids", field_type="uuid[]", description="Model flag UUIDs"),
    "model_ids": dict(id=sid("arg/model_ids"), name="model_ids", field_type="uuid[]", description="Related model identifiers"),
    "model_position_ids": dict(id=sid("arg/model_position_ids"), name="model_position_ids", field_type="uuid[]", description="Model position UUIDs"),
    "model_rubric_ids": dict(id=sid("arg/model_rubric_ids"), name="model_rubric_ids", field_type="uuid[]", description="Model rubric UUIDs"),
    "name_id": dict(id=sid("arg/name_id"), name="name_id", field_type="uuid", description="UUID of the name resource"),
    "name_ids": dict(id=sid("arg/name_ids"), name="name_ids", field_type="uuid[]", description="Selected name IDs"),
    "objective_ids": dict(id=sid("arg/objective_ids"), name="objective_ids", field_type="uuid[]", description="Selected objective resource IDs"),
    "objectives": dict(id=sid("arg/objectives"), name="objectives", field_type="string[]", description="Objective texts to create"),
    "objectives_enabled_flag": dict(id=sid("arg/objectives_enabled_flag"), name="objectives_enabled_flag", field_type="boolean", description="Whether objectives are enabled"),
    "objectives_enabled_flag_id": dict(id=sid("arg/objectives_enabled_flag_id"), name="objectives_enabled_flag_id", field_type="uuid", description="UUID of the objectives enabled flag option"),
    "option_ids": dict(id=sid("arg/option_ids"), name="option_ids", field_type="uuid[]", description="Selected option resource IDs"),
    "options": dict(id=sid("arg/options"), name="options", field_type="string", description="Option values to create"),
    "parameter_field_ids": dict(id=sid("arg/parameter_field_ids"), name="parameter_field_ids", field_type="uuid[]", description="Selected parameter field resource IDs"),
    "parameter_fields": dict(id=sid("arg/parameter_fields"), name="parameter_fields", field_type="string[]", description="Parameter field names for matching"),
    "permission_ids": dict(id=sid("arg/permission_ids"), name="permission_ids", field_type="uuid[]", description="Permission identifiers"),
    "persona_id": dict(id=sid("arg/persona_id"), name="persona_id", field_type="uuid", description="UUID of the persona to duplicate"),
    "personas": dict(id=sid("arg/personas"), name="personas", field_type="string[]", description="Persona names for matching"),
    "point_ids": dict(id=sid("arg/point_ids"), name="point_ids", field_type="uuid[]", description="Point UUIDs"),
    "practice_flag": dict(id=sid("arg/practice_flag"), name="practice_flag", field_type="boolean", description="Whether this is a practice simulation"),
    "practice_flag_id": dict(id=sid("arg/practice_flag_id"), name="practice_flag_id", field_type="uuid", description="Practice flag resource UUID"),
    "pricing_ids": dict(id=sid("arg/pricing_ids"), name="pricing_ids", field_type="uuid[]", description="Selected pricing IDs"),
    "problem_statement_enabled_flag": dict(id=sid("arg/problem_statement_enabled_flag"), name="problem_statement_enabled_flag", field_type="boolean", description="Whether problem statement is enabled"),
    "problem_statement_enabled_flag_id": dict(id=sid("arg/problem_statement_enabled_flag_id"), name="problem_statement_enabled_flag_id", field_type="uuid", description="UUID of the problem statement enabled flag option"),
    "problem_statement_id": dict(id=sid("arg/problem_statement_id"), name="problem_statement_id", field_type="uuid", description="UUID of the problem statement resource"),
    "problem_statement_ids": dict(id=sid("arg/problem_statement_ids"), name="problem_statement_ids", field_type="uuid[]", description="Selected problem statement resource IDs"),
    "profile_id": dict(id=sid("arg/profile_id"), name="profile_id", field_type="uuid", description="UUID of the profile to update"),
    "profile_persona_ids": dict(id=sid("arg/profile_persona_ids"), name="profile_persona_ids", field_type="uuid[]", description="Profile persona UUIDs"),
    "profile_personas": dict(id=sid("arg/profile_personas"), name="profile_personas", field_type="string", description="Profile persona values to create"),
    "profiles": dict(id=sid("arg/profiles"), name="profiles", field_type="string[]", description="Profile names for resolution"),
    "prompt_id": dict(id=sid("arg/prompt_id"), name="prompt_id", field_type="uuid", description="System prompt resource UUID"),
    "protocol": dict(id=sid("arg/protocol"), name="protocol", field_type="string", description="Protocol value to resolve"),
    "protocol_ids": dict(id=sid("arg/protocol_ids"), name="protocol_ids", field_type="uuid[]", description="Protocol resource UUIDs"),
    "provider_ids": dict(id=sid("arg/provider_ids"), name="provider_ids", field_type="uuid[]", description="List of provider IDs to delete"),
    "provider_key_ids": dict(id=sid("arg/provider_key_ids"), name="provider_key_ids", field_type="uuid[]", description="Provider key UUIDs"),
    "quality_ids": dict(id=sid("arg/quality_ids"), name="quality_ids", field_type="uuid[]", description="Quality level identifiers"),
    "question_ids": dict(id=sid("arg/question_ids"), name="question_ids", field_type="uuid[]", description="Selected question resource IDs"),
    "questions": dict(id=sid("arg/questions"), name="questions", field_type="string", description="Question values to create"),
    "questions_enabled_flag": dict(id=sid("arg/questions_enabled_flag"), name="questions_enabled_flag", field_type="boolean", description="Whether questions are enabled"),
    "questions_enabled_flag_id": dict(id=sid("arg/questions_enabled_flag_id"), name="questions_enabled_flag_id", field_type="uuid", description="UUID of the questions enabled flag option"),
    "reasoning_level_ids": dict(id=sid("arg/reasoning_level_ids"), name="reasoning_level_ids", field_type="uuid[]", description="Selected reasoning level IDs"),
    "request_limit": dict(id=sid("arg/request_limit"), name="request_limit", field_type="integer", description="Request limit value to resolve or create"),
    "request_limit_id": dict(id=sid("arg/request_limit_id"), name="request_limit_id", field_type="uuid", description="UUID of the request limit resource"),
    "request_limit_ids": dict(id=sid("arg/request_limit_ids"), name="request_limit_ids", field_type="uuid[]", description="Request limit resource UUIDs"),
    "role_id": dict(id=sid("arg/role_id"), name="role_id", field_type="uuid", description="Role resource UUID"),
    "scenario_flag_ids": dict(id=sid("arg/scenario_flag_ids"), name="scenario_flag_ids", field_type="uuid[]", description="Associated scenario flag UUIDs"),
    "scenario_flags": dict(id=sid("arg/scenario_flags"), name="scenario_flags", field_type="string", description="Scenario flag values to create"),
    "scenario_id": dict(id=sid("arg/scenario_id"), name="scenario_id", field_type="uuid", description="UUID of the scenario to duplicate"),
    "scenario_position_ids": dict(id=sid("arg/scenario_position_ids"), name="scenario_position_ids", field_type="uuid[]", description="Associated scenario position UUIDs"),
    "scenario_positions": dict(id=sid("arg/scenario_positions"), name="scenario_positions", field_type="string", description="Scenario position values to create"),
    "scenario_rubric_ids": dict(id=sid("arg/scenario_rubric_ids"), name="scenario_rubric_ids", field_type="uuid[]", description="Associated scenario rubric UUIDs"),
    "scenario_rubrics": dict(id=sid("arg/scenario_rubrics"), name="scenario_rubrics", field_type="string", description="Scenario rubric values to create"),
    "scenario_time_limit_ids": dict(id=sid("arg/scenario_time_limit_ids"), name="scenario_time_limit_ids", field_type="uuid[]", description="Associated scenario time limit UUIDs"),
    "scenario_time_limits": dict(id=sid("arg/scenario_time_limits"), name="scenario_time_limits", field_type="string", description="Scenario time limit values to create"),
    "scenarios": dict(id=sid("arg/scenarios"), name="scenarios", field_type="string[]", description="Scenario names for matching"),
    "setting_ids": dict(id=sid("arg/setting_ids"), name="setting_ids", field_type="uuid[]", description="Setting UUIDs to assign"),
    "setting_resource_ids": dict(id=sid("arg/setting_resource_ids"), name="setting_resource_ids", field_type="uuid[]", description="Setting resource UUIDs"),
    "settings_ids": dict(id=sid("arg/settings_ids"), name="settings_ids", field_type="uuid[]", description="Setting UUIDs to assign"),
    "simulation_availability": dict(id=sid("arg/simulation_availability"), name="simulation_availability", field_type="string", description="Simulation availability values to create"),
    "simulation_availability_ids": dict(id=sid("arg/simulation_availability_ids"), name="simulation_availability_ids", field_type="uuid[]", description="Simulation availability UUIDs"),
    "simulation_position_ids": dict(id=sid("arg/simulation_position_ids"), name="simulation_position_ids", field_type="uuid[]", description="Simulation position UUIDs"),
    "simulation_positions": dict(id=sid("arg/simulation_positions"), name="simulation_positions", field_type="string", description="Simulation position values to create"),
    "simulation_rubric_flag": dict(id=sid("arg/simulation_rubric_flag"), name="simulation_rubric_flag", field_type="boolean", description="Whether this is a simulation rubric"),
    "simulation_rubric_flag_id": dict(id=sid("arg/simulation_rubric_flag_id"), name="simulation_rubric_flag_id", field_type="uuid", description="Simulation rubric flag resource UUID"),
    "simulations": dict(id=sid("arg/simulations"), name="simulations", field_type="string[]", description="Simulation names for resolution"),
    "slug": dict(id=sid("arg/slug"), name="slug", field_type="string", description="Slug value to resolve or create"),
    "slug_id": dict(id=sid("arg/slug_id"), name="slug_id", field_type="uuid", description="UUID of the slug resource"),
    "slug_ids": dict(id=sid("arg/slug_ids"), name="slug_ids", field_type="uuid[]", description="Slug resource UUIDs"),
    "standard_group_ids": dict(id=sid("arg/standard_group_ids"), name="standard_group_ids", field_type="uuid[]", description="Standard group UUIDs"),
    "standard_ids": dict(id=sid("arg/standard_ids"), name="standard_ids", field_type="uuid[]", description="Standard UUIDs"),
    "system_ids": dict(id=sid("arg/system_ids"), name="system_ids", field_type="uuid[]", description="System UUIDs to assign"),
    "temperature_level_ids": dict(id=sid("arg/temperature_level_ids"), name="temperature_level_ids", field_type="uuid[]", description="Selected temperature level IDs"),
    "template_flag": dict(id=sid("arg/template_flag"), name="template_flag", field_type="boolean", description="Whether this is a template document"),
    "template_flag_id": dict(id=sid("arg/template_flag_id"), name="template_flag_id", field_type="uuid", description="Template flag resource UUID"),
    "text_ids": dict(id=sid("arg/text_ids"), name="text_ids", field_type="uuid[]", description="Text resource UUIDs"),
    "texts": dict(id=sid("arg/texts"), name="texts", field_type="string", description="Text values to create resources"),
    "threshold_ids": dict(id=sid("arg/threshold_ids"), name="threshold_ids", field_type="uuid[]", description="Threshold UUIDs to assign"),
    "tool_call_id": dict(id=sid("arg/tool_call_id"), name="tool_call_id", field_type="uuid", description="Tool call UUID"),
    "tool_ids": dict(id=sid("arg/tool_ids"), name="tool_ids", field_type="uuid[]", description="Associated tool UUIDs"),
    "total_points": dict(id=sid("arg/total_points"), name="total_points", field_type="integer", description="Total points for rubric criterion"),
    "upload_ids": dict(id=sid("arg/upload_ids"), name="upload_ids", field_type="uuid[]", description="File upload UUIDs"),
    "value": dict(id=sid("arg/value"), name="value", field_type="string", description="Provider identifier value"),
    "value_id": dict(id=sid("arg/value_id"), name="value_id", field_type="uuid", description="Selected value ID"),
    "video_enabled_flag": dict(id=sid("arg/video_enabled_flag"), name="video_enabled_flag", field_type="boolean", description="Whether video is enabled"),
    "video_enabled_flag_id": dict(id=sid("arg/video_enabled_flag_id"), name="video_enabled_flag_id", field_type="uuid", description="UUID of the video enabled flag option"),
    "video_ids": dict(id=sid("arg/video_ids"), name="video_ids", field_type="uuid[]", description="Selected video resource IDs"),
    "video_rubric_flag": dict(id=sid("arg/video_rubric_flag"), name="video_rubric_flag", field_type="boolean", description="Whether this is a video rubric"),
    "video_rubric_flag_id": dict(id=sid("arg/video_rubric_flag_id"), name="video_rubric_flag_id", field_type="uuid", description="Video rubric flag resource UUID"),
    "videos": dict(id=sid("arg/videos"), name="videos", field_type="string", description="Video values to create"),
    "voice_ids": dict(id=sid("arg/voice_ids"), name="voice_ids", field_type="uuid[]", description="Selected voice IDs"),
    "voices": dict(id=sid("arg/voices"), name="voices", field_type="string[]", description="Voice values"),

    # --- Auto-generated from Get request types ---
    "accent": dict(id=sid("arg/accent"), name="accent", field_type="string", description="Accent"),
    "accent_foreground": dict(id=sid("arg/accent_foreground"), name="accent_foreground", field_type="string", description="Accent Foreground"),
    "active_flag_required": dict(id=sid("arg/active_flag_required"), name="active_flag_required", field_type="boolean", description="Whether active flag is required"),
    "active_flag_resource": dict(id=sid("arg/active_flag_resource"), name="active_flag_resource", field_type="string", description="Active flag resource"),
    "actor_name": dict(id=sid("arg/actor_name"), name="actor_name", field_type="string", description="Display name of the current actor"),
    "agents": dict(id=sid("arg/agents"), name="agents", field_type="string", description="List of agents to create"),
    "artifacts": dict(id=sid("arg/artifacts"), name="artifacts", field_type="string", description="Artifacts"),
    "auths": dict(id=sid("arg/auths"), name="auths", field_type="string", description="List of auth providers to create"),
    "background": dict(id=sid("arg/background"), name="background", field_type="string", description="Background"),
    "benchmark_entry_id": dict(id=sid("arg/benchmark_entry_id"), name="benchmark_entry_id", field_type="uuid", description="Benchmark entry identifier"),
    "border": dict(id=sid("arg/border"), name="border", field_type="string", description="Border"),
    "can_edit": dict(id=sid("arg/can_edit"), name="can_edit", field_type="boolean", description="Whether the current user can edit"),
    "candidate_agents": dict(id=sid("arg/candidate_agents"), name="candidate_agents", field_type="string", description="Candidate agent data for scoring"),
    "card": dict(id=sid("arg/card"), name="card", field_type="string", description="Card"),
    "card_foreground": dict(id=sid("arg/card_foreground"), name="card_foreground", field_type="string", description="Card Foreground"),
    "chart1": dict(id=sid("arg/chart1"), name="chart1", field_type="string", description="Chart1"),
    "chart2": dict(id=sid("arg/chart2"), name="chart2", field_type="string", description="Chart2"),
    "chart3": dict(id=sid("arg/chart3"), name="chart3", field_type="string", description="Chart3"),
    "chart4": dict(id=sid("arg/chart4"), name="chart4", field_type="string", description="Chart4"),
    "chart5": dict(id=sid("arg/chart5"), name="chart5", field_type="string", description="Chart5"),
    "cohort_usage_count": dict(id=sid("arg/cohort_usage_count"), name="cohort_usage_count", field_type="integer", description="Number of cohorts using this simulation"),
    "cohorts": dict(id=sid("arg/cohorts"), name="cohorts", field_type="string", description="List of cohorts to create"),
    "color_hex": dict(id=sid("arg/color_hex"), name="color_hex", field_type="string", description="Color Hex"),
    "color_show_selected": dict(id=sid("arg/color_show_selected"), name="color_show_selected", field_type="boolean", description="When true, only return currently selected colors"),
    "conditional_parameter_search": dict(id=sid("arg/conditional_parameter_search"), name="conditional_parameter_search", field_type="string", description="Search query for conditional parameters"),
    "conditional_parameter_show_selected": dict(id=sid("arg/conditional_parameter_show_selected"), name="conditional_parameter_show_selected", field_type="boolean", description="Whether to show only selected parameters"),
    "created_at": dict(id=sid("arg/created_at"), name="created_at", field_type="string", description="Created At"),
    "danger_threshold": dict(id=sid("arg/danger_threshold"), name="danger_threshold", field_type="integer", description="Danger Threshold"),
    "department_resources": dict(id=sid("arg/department_resources"), name="department_resources", field_type="string", description="Selected department resources"),
    "department_suggestions": dict(id=sid("arg/department_suggestions"), name="department_suggestions", field_type="uuid[]", description="Suggested department UUIDs"),
    "departments_has_tools": dict(id=sid("arg/departments_has_tools"), name="departments_has_tools", field_type="boolean", description="Whether departments resource has tools"),
    "departments_required": dict(id=sid("arg/departments_required"), name="departments_required", field_type="boolean", description="Whether departments are required"),
    "description_required": dict(id=sid("arg/description_required"), name="description_required", field_type="boolean", description="Whether description is required"),
    "description_resource": dict(id=sid("arg/description_resource"), name="description_resource", field_type="string", description="Selected description resource"),
    "description_search": dict(id=sid("arg/description_search"), name="description_search", field_type="string", description="Search filter for descriptions"),
    "description_suggestions": dict(id=sid("arg/description_suggestions"), name="description_suggestions", field_type="uuid[]", description="Suggested description resource UUIDs"),
    "descriptions": dict(id=sid("arg/descriptions"), name="descriptions", field_type="string", description="Available description resources"),
    "descriptions_has_tools": dict(id=sid("arg/descriptions_has_tools"), name="descriptions_has_tools", field_type="boolean", description="Whether descriptions resource has tools"),
    "destructive": dict(id=sid("arg/destructive"), name="destructive", field_type="string", description="Destructive"),
    "disabled_reason": dict(id=sid("arg/disabled_reason"), name="disabled_reason", field_type="string", description="Reason the scenario is disabled"),
    "document_resources": dict(id=sid("arg/document_resources"), name="document_resources", field_type="string", description="Selected document resources"),
    "document_search": dict(id=sid("arg/document_search"), name="document_search", field_type="string", description="Search filter for documents"),
    "document_show_selected": dict(id=sid("arg/document_show_selected"), name="document_show_selected", field_type="boolean", description="Whether to show only selected documents"),
    "document_suggestions": dict(id=sid("arg/document_suggestions"), name="document_suggestions", field_type="uuid[]", description="Suggested document UUIDs"),
    "documents_required": dict(id=sid("arg/documents_required"), name="documents_required", field_type="boolean", description="Whether documents are required"),
    "draft_version": dict(id=sid("arg/draft_version"), name="draft_version", field_type="integer", description="Current draft version number"),
    "effective_draft_version": dict(id=sid("arg/effective_draft_version"), name="effective_draft_version", field_type="integer", description="Effective draft version after resolution"),
    "entries": dict(id=sid("arg/entries"), name="entries", field_type="string", description="Entries"),
    "error": dict(id=sid("arg/error"), name="error", field_type="string", description="Error"),
    "evals": dict(id=sid("arg/evals"), name="evals", field_type="string", description="List of evals to create"),
    "field_show_selected_by_param": dict(id=sid("arg/field_show_selected_by_param"), name="field_show_selected_by_param", field_type="string", description="Field-level show_selected filters by parameter"),
    "fields": dict(id=sid("arg/fields"), name="fields", field_type="string", description="List of fields to create"),
    "filter_document_ids": dict(id=sid("arg/filter_document_ids"), name="filter_document_ids", field_type="uuid[]", description="Filter by document UUIDs"),
    "filter_field_ids": dict(id=sid("arg/filter_field_ids"), name="filter_field_ids", field_type="uuid[]", description="Filter by field UUIDs"),
    "filter_parameter_ids": dict(id=sid("arg/filter_parameter_ids"), name="filter_parameter_ids", field_type="uuid[]", description="Filter by parameter UUIDs"),
    "filter_persona_ids": dict(id=sid("arg/filter_persona_ids"), name="filter_persona_ids", field_type="uuid[]", description="Filter by persona UUIDs"),
    "flags_has_tools": dict(id=sid("arg/flags_has_tools"), name="flags_has_tools", field_type="boolean", description="Whether flags resource has tools"),
    "foreground": dict(id=sid("arg/foreground"), name="foreground", field_type="string", description="Foreground"),
    "generated": dict(id=sid("arg/generated"), name="generated", field_type="boolean", description="Generated"),
    "guest_login_enabled": dict(id=sid("arg/guest_login_enabled"), name="guest_login_enabled", field_type="boolean", description="Guest Login Enabled"),
    "icon_show_selected": dict(id=sid("arg/icon_show_selected"), name="icon_show_selected", field_type="boolean", description="When true, only return currently selected icons"),
    "icon_value": dict(id=sid("arg/icon_value"), name="icon_value", field_type="string", description="Icon Value"),
    "ids": dict(id=sid("arg/ids"), name="ids", field_type="uuid[]", description="List of scenario UUIDs to retrieve"),
    "image_resources": dict(id=sid("arg/image_resources"), name="image_resources", field_type="string", description="Selected image resources"),
    "image_search": dict(id=sid("arg/image_search"), name="image_search", field_type="string", description="Search filter for images"),
    "image_suggestions": dict(id=sid("arg/image_suggestions"), name="image_suggestions", field_type="uuid[]", description="Suggested image UUIDs"),
    "images_enabled": dict(id=sid("arg/images_enabled"), name="images_enabled", field_type="boolean", description="Whether images are enabled"),
    "images_enabled_flag_required": dict(id=sid("arg/images_enabled_flag_required"), name="images_enabled_flag_required", field_type="boolean", description="Whether images enabled flag is required"),
    "images_enabled_flag_resource": dict(id=sid("arg/images_enabled_flag_resource"), name="images_enabled_flag_resource", field_type="string", description="Images enabled flag resource"),
    "images_required": dict(id=sid("arg/images_required"), name="images_required", field_type="boolean", description="Whether images are required"),
    "info": dict(id=sid("arg/info"), name="info", field_type="string", description="Info"),
    "info_foreground": dict(id=sid("arg/info_foreground"), name="info_foreground", field_type="string", description="Info Foreground"),
    "input": dict(id=sid("arg/input"), name="input", field_type="string", description="Input"),
    "instructions_search": dict(id=sid("arg/instructions_search"), name="instructions_search", field_type="string", description="Filter instruction options by search text"),
    "items": dict(id=sid("arg/items"), name="items", field_type="string", description="List of scenario items"),
    "mcp": dict(id=sid("arg/mcp"), name="mcp", field_type="boolean", description="Whether this is an MCP request"),
    "models": dict(id=sid("arg/models"), name="models", field_type="string", description="List of models to create"),
    "muted_foreground": dict(id=sid("arg/muted_foreground"), name="muted_foreground", field_type="string", description="Muted Foreground"),
    "name_required": dict(id=sid("arg/name_required"), name="name_required", field_type="boolean", description="Whether name is required"),
    "name_resource": dict(id=sid("arg/name_resource"), name="name_resource", field_type="string", description="Selected name resource"),
    "name_suggestions": dict(id=sid("arg/name_suggestions"), name="name_suggestions", field_type="uuid[]", description="Suggested name resource UUIDs"),
    "names": dict(id=sid("arg/names"), name="names", field_type="string", description="Available name resources"),
    "names_has_tools": dict(id=sid("arg/names_has_tools"), name="names_has_tools", field_type="boolean", description="Whether names resource has tools"),
    "objective_resources": dict(id=sid("arg/objective_resources"), name="objective_resources", field_type="string", description="Selected objective resources"),
    "objective_suggestions": dict(id=sid("arg/objective_suggestions"), name="objective_suggestions", field_type="uuid[]", description="Suggested objective UUIDs"),
    "objectives_enabled": dict(id=sid("arg/objectives_enabled"), name="objectives_enabled", field_type="boolean", description="Whether objectives are enabled"),
    "objectives_enabled_flag_required": dict(id=sid("arg/objectives_enabled_flag_required"), name="objectives_enabled_flag_required", field_type="boolean", description="Whether objectives enabled flag is required"),
    "objectives_enabled_flag_resource": dict(id=sid("arg/objectives_enabled_flag_resource"), name="objectives_enabled_flag_resource", field_type="string", description="Objectives enabled flag resource"),
    "objectives_required": dict(id=sid("arg/objectives_required"), name="objectives_required", field_type="boolean", description="Whether objectives are required"),
    "option_resources": dict(id=sid("arg/option_resources"), name="option_resources", field_type="string", description="Selected option resources"),
    "option_search": dict(id=sid("arg/option_search"), name="option_search", field_type="string", description="Search filter for options"),
    "option_suggestions": dict(id=sid("arg/option_suggestions"), name="option_suggestions", field_type="uuid[]", description="Suggested option UUIDs"),
    "options_required": dict(id=sid("arg/options_required"), name="options_required", field_type="boolean", description="Whether options are required"),
    "parameter_field_resources": dict(id=sid("arg/parameter_field_resources"), name="parameter_field_resources", field_type="string", description="Selected parameter field resources"),
    "parameter_field_search": dict(id=sid("arg/parameter_field_search"), name="parameter_field_search", field_type="string", description="Filter parameter field options by search text"),
    "parameter_field_show_selected": dict(id=sid("arg/parameter_field_show_selected"), name="parameter_field_show_selected", field_type="boolean", description="When true, only return currently selected parameter fields"),
    "parameter_fields_required": dict(id=sid("arg/parameter_fields_required"), name="parameter_fields_required", field_type="boolean", description="Whether parameter fields are required"),
    "parameter_resources": dict(id=sid("arg/parameter_resources"), name="parameter_resources", field_type="string", description="Selected parameter resources"),
    "parameter_show_selected": dict(id=sid("arg/parameter_show_selected"), name="parameter_show_selected", field_type="boolean", description="Show only selected parameters"),
    "parameter_suggestions": dict(id=sid("arg/parameter_suggestions"), name="parameter_suggestions", field_type="uuid[]", description="Suggested parameter UUIDs"),
    "parameters": dict(id=sid("arg/parameters"), name="parameters", field_type="string", description="Available parameter resources"),
    "parameters_required": dict(id=sid("arg/parameters_required"), name="parameters_required", field_type="boolean", description="Whether parameters are required"),
    "persona_resources": dict(id=sid("arg/persona_resources"), name="persona_resources", field_type="string", description="Selected persona resources"),
    "persona_show_selected": dict(id=sid("arg/persona_show_selected"), name="persona_show_selected", field_type="boolean", description="Whether to show only selected personas"),
    "persona_suggestions": dict(id=sid("arg/persona_suggestions"), name="persona_suggestions", field_type="uuid[]", description="Suggested persona UUIDs"),
    "personas_required": dict(id=sid("arg/personas_required"), name="personas_required", field_type="boolean", description="Whether personas are required"),
    "popover": dict(id=sid("arg/popover"), name="popover", field_type="string", description="Popover"),
    "popover_foreground": dict(id=sid("arg/popover_foreground"), name="popover_foreground", field_type="string", description="Popover Foreground"),
    "primary_color": dict(id=sid("arg/primary_color"), name="primary_color", field_type="string", description="Primary Color"),
    "primary_foreground": dict(id=sid("arg/primary_foreground"), name="primary_foreground", field_type="string", description="Primary Foreground"),
    "problem_statement_enabled": dict(id=sid("arg/problem_statement_enabled"), name="problem_statement_enabled", field_type="boolean", description="Whether problem statement is enabled"),
    "problem_statement_enabled_flag_required": dict(id=sid("arg/problem_statement_enabled_flag_required"), name="problem_statement_enabled_flag_required", field_type="boolean", description="Whether problem statement enabled flag is required"),
    "problem_statement_enabled_flag_resource": dict(id=sid("arg/problem_statement_enabled_flag_resource"), name="problem_statement_enabled_flag_resource", field_type="string", description="Problem statement enabled flag resource"),
    "problem_statement_required": dict(id=sid("arg/problem_statement_required"), name="problem_statement_required", field_type="boolean", description="Whether problem statement is required"),
    "problem_statement_resource": dict(id=sid("arg/problem_statement_resource"), name="problem_statement_resource", field_type="string", description="Selected problem statement resource"),
    "problem_statement_search": dict(id=sid("arg/problem_statement_search"), name="problem_statement_search", field_type="string", description="Search filter for problem statements"),
    "problem_statement_suggestions": dict(id=sid("arg/problem_statement_suggestions"), name="problem_statement_suggestions", field_type="uuid[]", description="Suggested problem statement UUIDs"),
    "problem_statements": dict(id=sid("arg/problem_statements"), name="problem_statements", field_type="string", description="Available problem statements"),
    "providers": dict(id=sid("arg/providers"), name="providers", field_type="string", description="List of providers to create"),
    "quality": dict(id=sid("arg/quality"), name="quality", field_type="string", description="Quality"),
    "question_resources": dict(id=sid("arg/question_resources"), name="question_resources", field_type="string", description="Selected question resources"),
    "question_search": dict(id=sid("arg/question_search"), name="question_search", field_type="string", description="Search filter for questions"),
    "question_suggestions": dict(id=sid("arg/question_suggestions"), name="question_suggestions", field_type="uuid[]", description="Suggested question UUIDs"),
    "questions_enabled": dict(id=sid("arg/questions_enabled"), name="questions_enabled", field_type="boolean", description="Whether questions are enabled"),
    "questions_enabled_flag_required": dict(id=sid("arg/questions_enabled_flag_required"), name="questions_enabled_flag_required", field_type="boolean", description="Whether questions enabled flag is required"),
    "questions_enabled_flag_resource": dict(id=sid("arg/questions_enabled_flag_resource"), name="questions_enabled_flag_resource", field_type="string", description="Questions enabled flag resource"),
    "questions_required": dict(id=sid("arg/questions_required"), name="questions_required", field_type="boolean", description="Whether questions are required"),
    "reasoning": dict(id=sid("arg/reasoning"), name="reasoning", field_type="string", description="Reasoning"),
    "resources": dict(id=sid("arg/resources"), name="resources", field_type="string", description="Resources"),
    "ring": dict(id=sid("arg/ring"), name="ring", field_type="string", description="Ring"),
    "role": dict(id=sid("arg/role"), name="role", field_type="string", description="Role"),
    "rubrics": dict(id=sid("arg/rubrics"), name="rubrics", field_type="string", description="List of rubrics to create"),
    "scenario_exists": dict(id=sid("arg/scenario_exists"), name="scenario_exists", field_type="boolean", description="Whether the scenario exists"),
    "scenario_flags_has_tools": dict(id=sid("arg/scenario_flags_has_tools"), name="scenario_flags_has_tools", field_type="boolean", description="Whether scenario flags resource has tools"),
    "scenario_name": dict(id=sid("arg/scenario_name"), name="scenario_name", field_type="string", description="Name of the duplicated scenario"),
    "scenario_positions_has_tools": dict(id=sid("arg/scenario_positions_has_tools"), name="scenario_positions_has_tools", field_type="boolean", description="Whether scenario positions resource has tools"),
    "scenario_rubrics_has_tools": dict(id=sid("arg/scenario_rubrics_has_tools"), name="scenario_rubrics_has_tools", field_type="boolean", description="Whether scenario rubrics resource has tools"),
    "scenario_time_limits_has_tools": dict(id=sid("arg/scenario_time_limits_has_tools"), name="scenario_time_limits_has_tools", field_type="boolean", description="Whether scenario time limits resource has tools"),
    "scenarios_has_tools": dict(id=sid("arg/scenarios_has_tools"), name="scenarios_has_tools", field_type="boolean", description="Whether scenarios resource has tools"),
    "secondary": dict(id=sid("arg/secondary"), name="secondary", field_type="string", description="Secondary"),
    "secondary_foreground": dict(id=sid("arg/secondary_foreground"), name="secondary_foreground", field_type="string", description="Secondary Foreground"),
    "settings": dict(id=sid("arg/settings"), name="settings", field_type="string", description="List of settings to create"),
    "settings_id": dict(id=sid("arg/settings_id"), name="settings_id", field_type="uuid", description="Settings Id"),
    "show_active_flag": dict(id=sid("arg/show_active_flag"), name="show_active_flag", field_type="boolean", description="Whether to show active flag"),
    "show_departments": dict(id=sid("arg/show_departments"), name="show_departments", field_type="boolean", description="Whether to show departments section"),
    "show_description": dict(id=sid("arg/show_description"), name="show_description", field_type="boolean", description="Whether to show description section"),
    "show_documents": dict(id=sid("arg/show_documents"), name="show_documents", field_type="boolean", description="Whether to show documents section"),
    "show_images": dict(id=sid("arg/show_images"), name="show_images", field_type="boolean", description="Whether to show images section"),
    "show_images_enabled_flag": dict(id=sid("arg/show_images_enabled_flag"), name="show_images_enabled_flag", field_type="boolean", description="Whether to show images enabled flag"),
    "show_name": dict(id=sid("arg/show_name"), name="show_name", field_type="boolean", description="Whether to show name section"),
    "show_objectives": dict(id=sid("arg/show_objectives"), name="show_objectives", field_type="boolean", description="Whether to show objectives section"),
    "show_objectives_enabled_flag": dict(id=sid("arg/show_objectives_enabled_flag"), name="show_objectives_enabled_flag", field_type="boolean", description="Whether to show objectives enabled flag"),
    "show_options": dict(id=sid("arg/show_options"), name="show_options", field_type="boolean", description="Whether to show options section"),
    "show_parameter_fields": dict(id=sid("arg/show_parameter_fields"), name="show_parameter_fields", field_type="boolean", description="Whether to show parameter fields section"),
    "show_parameters": dict(id=sid("arg/show_parameters"), name="show_parameters", field_type="boolean", description="Whether to show parameters section"),
    "show_personas": dict(id=sid("arg/show_personas"), name="show_personas", field_type="boolean", description="Whether to show personas section"),
    "show_problem_statement": dict(id=sid("arg/show_problem_statement"), name="show_problem_statement", field_type="boolean", description="Whether to show problem statement section"),
    "show_problem_statement_enabled_flag": dict(id=sid("arg/show_problem_statement_enabled_flag"), name="show_problem_statement_enabled_flag", field_type="boolean", description="Whether to show problem statement enabled flag"),
    "show_questions": dict(id=sid("arg/show_questions"), name="show_questions", field_type="boolean", description="Whether to show questions section"),
    "show_questions_enabled_flag": dict(id=sid("arg/show_questions_enabled_flag"), name="show_questions_enabled_flag", field_type="boolean", description="Whether to show questions enabled flag"),
    "show_video_enabled_flag": dict(id=sid("arg/show_video_enabled_flag"), name="show_video_enabled_flag", field_type="boolean", description="Whether to show video enabled flag"),
    "show_videos": dict(id=sid("arg/show_videos"), name="show_videos", field_type="boolean", description="Whether to show videos section"),
    "sidebar": dict(id=sid("arg/sidebar"), name="sidebar", field_type="string", description="Sidebar"),
    "sidebar_accent": dict(id=sid("arg/sidebar_accent"), name="sidebar_accent", field_type="string", description="Sidebar Accent"),
    "sidebar_accent_foreground": dict(id=sid("arg/sidebar_accent_foreground"), name="sidebar_accent_foreground", field_type="string", description="Sidebar Accent Foreground"),
    "sidebar_background": dict(id=sid("arg/sidebar_background"), name="sidebar_background", field_type="string", description="Sidebar Background"),
    "sidebar_border": dict(id=sid("arg/sidebar_border"), name="sidebar_border", field_type="string", description="Sidebar Border"),
    "sidebar_foreground": dict(id=sid("arg/sidebar_foreground"), name="sidebar_foreground", field_type="string", description="Sidebar Foreground"),
    "sidebar_primary": dict(id=sid("arg/sidebar_primary"), name="sidebar_primary", field_type="string", description="Sidebar Primary"),
    "sidebar_primary_foreground": dict(id=sid("arg/sidebar_primary_foreground"), name="sidebar_primary_foreground", field_type="string", description="Sidebar Primary Foreground"),
    "sidebar_ring": dict(id=sid("arg/sidebar_ring"), name="sidebar_ring", field_type="string", description="Sidebar Ring"),
    "simulation_department_ids": dict(id=sid("arg/simulation_department_ids"), name="simulation_department_ids", field_type="uuid[]", description="Department UUIDs of the simulation"),
    "simulation_exists": dict(id=sid("arg/simulation_exists"), name="simulation_exists", field_type="boolean", description="Whether the simulation exists"),
    "status": dict(id=sid("arg/status"), name="status", field_type="string", description="Filter by test status"),
    "success": dict(id=sid("arg/success"), name="success", field_type="string", description="Success"),
    "success_foreground": dict(id=sid("arg/success_foreground"), name="success_foreground", field_type="string", description="Success Foreground"),
    "success_threshold": dict(id=sid("arg/success_threshold"), name="success_threshold", field_type="integer", description="Success Threshold"),
    "surface": dict(id=sid("arg/surface"), name="surface", field_type="string", description="Surface"),
    "temperature": dict(id=sid("arg/temperature"), name="temperature", field_type="string", description="Temperature"),
    "tools": dict(id=sid("arg/tools"), name="tools", field_type="string", description="List of tools to create"),
    "user_department_ids": dict(id=sid("arg/user_department_ids"), name="user_department_ids", field_type="uuid[]", description="Department UUIDs of the user"),
    "user_role": dict(id=sid("arg/user_role"), name="user_role", field_type="string", description="Role of the current user"),
    "video_enabled": dict(id=sid("arg/video_enabled"), name="video_enabled", field_type="boolean", description="Whether video is enabled"),
    "video_enabled_flag_required": dict(id=sid("arg/video_enabled_flag_required"), name="video_enabled_flag_required", field_type="boolean", description="Whether video enabled flag is required"),
    "video_enabled_flag_resource": dict(id=sid("arg/video_enabled_flag_resource"), name="video_enabled_flag_resource", field_type="string", description="Video enabled flag resource"),
    "video_resources": dict(id=sid("arg/video_resources"), name="video_resources", field_type="string", description="Selected video resources"),
    "video_search": dict(id=sid("arg/video_search"), name="video_search", field_type="string", description="Search filter for videos"),
    "video_suggestions": dict(id=sid("arg/video_suggestions"), name="video_suggestions", field_type="uuid[]", description="Suggested video UUIDs"),
    "videos_required": dict(id=sid("arg/videos_required"), name="videos_required", field_type="boolean", description="Whether videos are required"),
    "warning": dict(id=sid("arg/warning"), name="warning", field_type="string", description="Warning"),
    "warning_foreground": dict(id=sid("arg/warning_foreground"), name="warning_foreground", field_type="string", description="Warning Foreground"),
    "warning_threshold": dict(id=sid("arg/warning_threshold"), name="warning_threshold", field_type="integer", description="Warning Threshold"),

    # --- Attempt Chat fields ---
    "analyses_enabled": dict(id=sid("arg/analyses_enabled"), name="analyses_enabled", field_type="boolean", description="Whether analyses are enabled"),
    "audio_enabled": dict(id=sid("arg/audio_enabled"), name="audio_enabled", field_type="boolean", description="Whether audio is enabled"),
    "departments_ids": dict(id=sid("arg/departments_ids"), name="departments_ids", field_type="uuid[]", description="Department identifiers"),
    "descriptions_ids": dict(id=sid("arg/descriptions_ids"), name="descriptions_ids", field_type="uuid[]", description="Description identifiers"),
    "documents_ids": dict(id=sid("arg/documents_ids"), name="documents_ids", field_type="uuid[]", description="Document identifiers"),
    "hint": dict(id=sid("arg/hint"), name="hint", field_type="text", description="Hint text content"),
    "hints_enabled": dict(id=sid("arg/hints_enabled"), name="hints_enabled", field_type="boolean", description="Whether hints are enabled"),
    "images_ids": dict(id=sid("arg/images_ids"), name="images_ids", field_type="uuid[]", description="Image identifiers"),
    "improvements_enabled": dict(id=sid("arg/improvements_enabled"), name="improvements_enabled", field_type="boolean", description="Whether improvements are enabled"),
    "names_ids": dict(id=sid("arg/names_ids"), name="names_ids", field_type="uuid[]", description="Name identifiers"),
    "objectives_ids": dict(id=sid("arg/objectives_ids"), name="objectives_ids", field_type="uuid[]", description="Objective identifiers"),
    "options_ids": dict(id=sid("arg/options_ids"), name="options_ids", field_type="uuid[]", description="Option identifiers"),
    "parameter_fields_ids": dict(id=sid("arg/parameter_fields_ids"), name="parameter_fields_ids", field_type="uuid[]", description="Parameter field identifiers"),
    "parameters_ids": dict(id=sid("arg/parameters_ids"), name="parameters_ids", field_type="uuid[]", description="Parameter identifiers"),
    "personas_ids": dict(id=sid("arg/personas_ids"), name="personas_ids", field_type="uuid[]", description="Persona identifiers"),
    "position": dict(id=sid("arg/position"), name="position", field_type="integer", description="Chat position"),
    "problem_statements_ids": dict(id=sid("arg/problem_statements_ids"), name="problem_statements_ids", field_type="uuid[]", description="Problem statement identifiers"),
    "questions_ids": dict(id=sid("arg/questions_ids"), name="questions_ids", field_type="uuid[]", description="Question identifiers"),
    "rubrics_ids": dict(id=sid("arg/rubrics_ids"), name="rubrics_ids", field_type="uuid[]", description="Rubric identifiers"),
    "standard_groups_ids": dict(id=sid("arg/standard_groups_ids"), name="standard_groups_ids", field_type="uuid[]", description="Standard group identifiers"),
    "standards_ids": dict(id=sid("arg/standards_ids"), name="standards_ids", field_type="uuid[]", description="Standard identifiers"),
    "strengths_enabled": dict(id=sid("arg/strengths_enabled"), name="strengths_enabled", field_type="boolean", description="Whether strengths are enabled"),
    "text": dict(id=sid("arg/text"), name="text", field_type="text", description="Message text content"),
    "text_enabled": dict(id=sid("arg/text_enabled"), name="text_enabled", field_type="boolean", description="Whether text is enabled"),
    "time_limit": dict(id=sid("arg/time_limit"), name="time_limit", field_type="integer", description="Time limit in seconds"),
    "title": dict(id=sid("arg/title"), name="title", field_type="text", description="Chat title"),
    "total": dict(id=sid("arg/total"), name="total", field_type="integer", description="Total points for feedback"),
    "videos_ids": dict(id=sid("arg/videos_ids"), name="videos_ids", field_type="uuid[]", description="Video identifiers"),
}

# Flat list for seeding
args = list(SHARED_ARGS.values())
