"""Shared args_output resource seeds.

Each args_output maps an input arg to an API field via a Jinja template.
Tools reference args_outputs by key instead of defining them inline.

Naming convention:
  - Payload outputs: named after the API field they target (e.g., "name", "description")
  - Routing outputs: "artifact" and "operation" determine which infra function to call

Routing variants:
  - *_passthrough: template="{{ x }}" — LLM explicitly specifies the value
  - *_<value>:     template="<value>" — hardcoded constant for single-permission tools
"""

from database.seeds.ids import sid

# The args_id for routing outputs points to the shared "artifact" and "operation" args.
_ARTIFACT_ARG_ID = sid("arg/artifact")
_OPERATION_ARG_ID = sid("arg/operation")

SHARED_ARGS_OUTPUTS = {
    # --- Routing: pass-through (for multi-permission tools) ---
    "artifact_passthrough": dict(
        id=sid("args_output/artifact_passthrough"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="{{ artifact }}",
    ),
    "operation_passthrough": dict(
        id=sid("args_output/operation_passthrough"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="{{ operation }}",
    ),
    # --- Routing: hardcoded operations ---
    "operation_create": dict(
        id=sid("args_output/operation_create"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="create",
    ),
    "operation_update": dict(
        id=sid("args_output/operation_update"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="update",
    ),
    "operation_delete": dict(
        id=sid("args_output/operation_delete"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="delete",
    ),
    "operation_search": dict(
        id=sid("args_output/operation_search"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="search",
    ),
    "operation_get": dict(
        id=sid("args_output/operation_get"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="get",
    ),
    "operation_draft": dict(
        id=sid("args_output/operation_draft"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="draft",
    ),
    "operation_drafts": dict(
        id=sid("args_output/operation_drafts"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="drafts",
    ),
    "operation_duplicate": dict(
        id=sid("args_output/operation_duplicate"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="duplicate",
    ),
    "operation_archive": dict(
        id=sid("args_output/operation_archive"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="archive",
    ),
    "operation_context": dict(
        id=sid("args_output/operation_context"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="context",
    ),
    "operation_decrypt": dict(
        id=sid("args_output/operation_decrypt"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="decrypt",
    ),
    "operation_emulate": dict(
        id=sid("args_output/operation_emulate"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="emulate",
    ),
    "operation_unemulate": dict(
        id=sid("args_output/operation_unemulate"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="unemulate",
    ),
    "operation_previous": dict(
        id=sid("args_output/operation_previous"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="previous",
    ),
    "operation_problem": dict(
        id=sid("args_output/operation_problem"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="problem",
    ),
    "operation_resolve": dict(
        id=sid("args_output/operation_resolve"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="resolve",
    ),
    "operation_response": dict(
        id=sid("args_output/operation_response"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="response",
    ),
    "operation_generate": dict(
        id=sid("args_output/operation_generate"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="generate",
    ),
    "operation_run": dict(
        id=sid("args_output/operation_run"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="run",
    ),
    "operation_end_all": dict(
        id=sid("args_output/operation_end_all"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="end_all",
    ),
    # --- Routing: hardcoded artifacts ---
    "artifact_agent": dict(
        id=sid("args_output/artifact_agent"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="agent",
    ),
    "artifact_persona": dict(
        id=sid("args_output/artifact_persona"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="persona",
    ),
    "artifact_scenario": dict(
        id=sid("args_output/artifact_scenario"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="scenario",
    ),
    "artifact_simulation": dict(
        id=sid("args_output/artifact_simulation"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="simulation",
    ),
    "artifact_document": dict(
        id=sid("args_output/artifact_document"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="document",
    ),
    "artifact_rubric": dict(
        id=sid("args_output/artifact_rubric"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="rubric",
    ),
    "artifact_cohort": dict(
        id=sid("args_output/artifact_cohort"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="cohort",
    ),
    "artifact_eval": dict(
        id=sid("args_output/artifact_eval"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="eval",
    ),
    "artifact_department": dict(
        id=sid("args_output/artifact_department"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="department",
    ),
    "artifact_model": dict(
        id=sid("args_output/artifact_model"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="model",
    ),
    "artifact_provider": dict(
        id=sid("args_output/artifact_provider"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="provider",
    ),
    "artifact_tool": dict(
        id=sid("args_output/artifact_tool"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="tool",
    ),
    "artifact_setting": dict(
        id=sid("args_output/artifact_setting"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="setting",
    ),
    "artifact_auth": dict(
        id=sid("args_output/artifact_auth"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="auth",
    ),
    "artifact_field": dict(
        id=sid("args_output/artifact_field"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="field",
    ),
    "artifact_parameter": dict(
        id=sid("args_output/artifact_parameter"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="parameter",
    ),
    "artifact_profile": dict(
        id=sid("args_output/artifact_profile"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="profile",
    ),
    "artifact_scenario_image": dict(
        id=sid("args_output/artifact_scenario_image"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="scenario_image",
    ),
    "artifact_scenario_video": dict(
        id=sid("args_output/artifact_scenario_video"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="scenario_video",
    ),
    "artifact_document_text": dict(
        id=sid("args_output/artifact_document_text"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="document_text",
    ),
    "artifact_document_file": dict(
        id=sid("args_output/artifact_document_file"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="document_file",
    ),
    "artifact_attempt_audio": dict(
        id=sid("args_output/artifact_attempt_audio"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="attempt_audio",
    ),
    # --- Payload: universal fields (all/most create operations) ---
    "name": dict(
        id=sid("args_output/name"),
        args_id=sid("arg/name"),
        name="name",
        template="{{ name }}",
    ),
    "description": dict(
        id=sid("args_output/description"),
        args_id=sid("arg/description"),
        name="description",
        template="{{ description }}",
    ),
    # --- Payload: content-specific fields ---
    "instructions": dict(
        id=sid("args_output/instructions"),
        args_id=sid("arg/instructions"),
        name="instructions",
        template="{{ instructions }}",
    ),
    "color": dict(
        id=sid("args_output/color"),
        args_id=sid("arg/color"),
        name="color",
        template="{{ color }}",
    ),
    "icon": dict(
        id=sid("args_output/icon"),
        args_id=sid("arg/icon"),
        name="icon",
        template="{{ icon }}",
    ),
    "image": dict(
        id=sid("args_output/image"),
        args_id=sid("arg/image"),
        name="image",
        template="{{ image }}",
    ),
    "video": dict(
        id=sid("args_output/video"),
        args_id=sid("arg/video"),
        name="video",
        template="{{ video }}",
    ),
    "audio": dict(
        id=sid("args_output/audio"),
        args_id=sid("arg/audio"),
        name="audio",
        template="{{ audio }}",
    ),
    "content": dict(
        id=sid("args_output/content"),
        args_id=sid("arg/content"),
        name="content",
        template="{{ content }}",
    ),
    "file": dict(
        id=sid("args_output/file"),
        args_id=sid("arg/file"),
        name="file",
        template="{{ file }}",
    ),
    "image_id": dict(
        id=sid("args_output/image_id"),
        args_id=sid("arg/image_id"),
        name="image_id",
        template="{{ image_id }}",
    ),
    "video_id": dict(
        id=sid("args_output/video_id"),
        args_id=sid("arg/video_id"),
        name="video_id",
        template="{{ video_id }}",
    ),
    "audio_id": dict(
        id=sid("args_output/audio_id"),
        args_id=sid("arg/audio_id"),
        name="audio_id",
        template="{{ audio_id }}",
    ),
    "text_id": dict(
        id=sid("args_output/text_id"),
        args_id=sid("arg/text_id"),
        name="text_id",
        template="{{ text_id }}",
    ),
    "file_id": dict(
        id=sid("args_output/file_id"),
        args_id=sid("arg/file_id"),
        name="file_id",
        template="{{ file_id }}",
    ),
    "problem_statement": dict(
        id=sid("args_output/problem_statement"),
        args_id=sid("arg/problem_statement"),
        name="problem_statement",
        template="{{ problem_statement }}",
    ),
    # --- Payload: search/browse fields ---
    "search": dict(
        id=sid("args_output/search"),
        args_id=sid("arg/search"),
        name="search",
        template="{{ search }}",
    ),
    "page": dict(
        id=sid("args_output/page"),
        args_id=sid("arg/page"),
        name="page",
        template="{{ page }}",
    ),
    "page_size": dict(
        id=sid("args_output/page_size"),
        args_id=sid("arg/page_size"),
        name="page_size",
        template="{{ page_size }}",
    ),
    # --- Payload: session/audio fields ---
    "chat_id": dict(
        id=sid("args_output/chat_id"),
        args_id=sid("arg/chat_id"),
        name="chat_id",
        template="{{ chat_id }}",
    ),
    "length_seconds": dict(
        id=sid("args_output/length_seconds"),
        args_id=sid("arg/length_seconds"),
        name="length_seconds",
        template="{{ length_seconds }}",
    ),
    "muted": dict(
        id=sid("args_output/muted"),
        args_id=sid("arg/muted"),
        name="muted",
        template="{{ muted }}",
    ),
    # --- Payload: ID reference fields ---
    "agent_id": dict(
        id=sid("args_output/agent_id"),
        args_id=sid("arg/artifact"),
        name="agent_id",
        template="{{ agent_id }}",
    ),
    "attempt_id": dict(
        id=sid("args_output/attempt_id"),
        args_id=sid("arg/attempt_id"),
        name="attempt_id",
        template="{{ attempt_id }}",
    ),
    "simulation_id": dict(
        id=sid("args_output/simulation_id"),
        args_id=sid("arg/simulation_id"),
        name="simulation_id",
        template="{{ simulation_id }}",
    ),
    "test_id": dict(
        id=sid("args_output/test_id"),
        args_id=sid("arg/test_id"),
        name="test_id",
        template="{{ test_id }}",
    ),
    "draft_id": dict(
        id=sid("args_output/draft_id"),
        args_id=sid("arg/draft_id"),
        name="draft_id",
        template="{{ draft_id }}",
    ),
    # --- Payload: attempt/test fields ---
    "message": dict(
        id=sid("args_output/message"),
        args_id=sid("arg/message"),
        name="message",
        template="{{ message }}",
    ),
    "feedback": dict(
        id=sid("args_output/feedback"),
        args_id=sid("arg/feedback"),
        name="feedback",
        template="{{ feedback }}",
    ),
    "grade": dict(
        id=sid("args_output/grade"),
        args_id=sid("arg/grade"),
        name="grade",
        template="{{ grade }}",
    ),
    "score": dict(
        id=sid("args_output/score"),
        args_id=sid("arg/score"),
        name="score",
        template="{{ score }}",
    ),
    # --- Routing: additional hardcoded operations ---
    "operation_start": dict(
        id=sid("args_output/operation_start"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="start",
    ),
    "operation_end": dict(
        id=sid("args_output/operation_end"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="end",
    ),
    "operation_next": dict(
        id=sid("args_output/operation_next"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="next",
    ),
    "operation_message": dict(
        id=sid("args_output/operation_message"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="message",
    ),
    "operation_grade": dict(
        id=sid("args_output/operation_grade"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="grade",
    ),
    "operation_stop": dict(
        id=sid("args_output/operation_stop"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="stop",
    ),
    "operation_export": dict(
        id=sid("args_output/operation_export"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="export",
    ),
    "operation_refresh": dict(
        id=sid("args_output/operation_refresh"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="refresh",
    ),
    "operation_image_upload": dict(
        id=sid("args_output/operation_image_upload"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="image_upload",
    ),
    "operation_image_download": dict(
        id=sid("args_output/operation_image_download"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="image_download",
    ),
    "operation_video_upload": dict(
        id=sid("args_output/operation_video_upload"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="video_upload",
    ),
    "operation_video_download": dict(
        id=sid("args_output/operation_video_download"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="video_download",
    ),
    "operation_text_upload": dict(
        id=sid("args_output/operation_text_upload"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="text_upload",
    ),
    "operation_text_download": dict(
        id=sid("args_output/operation_text_download"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="text_download",
    ),
    "operation_file_upload": dict(
        id=sid("args_output/operation_file_upload"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="file_upload",
    ),
    "operation_file_download": dict(
        id=sid("args_output/operation_file_download"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="file_download",
    ),
    "operation_file_preview": dict(
        id=sid("args_output/operation_file_preview"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="file_preview",
    ),
    "operation_audio_upload": dict(
        id=sid("args_output/operation_audio_upload"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="audio_upload",
    ),
    "operation_audio_download": dict(
        id=sid("args_output/operation_audio_download"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="audio_download",
    ),
    "operation_audio_start": dict(
        id=sid("args_output/operation_audio_start"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="audio_start",
    ),
    "operation_audio_frame": dict(
        id=sid("args_output/operation_audio_frame"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="audio_frame",
    ),
    "operation_audio_stop": dict(
        id=sid("args_output/operation_audio_stop"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="audio_stop",
    ),
    "operation_audio_mute": dict(
        id=sid("args_output/operation_audio_mute"),
        args_id=_OPERATION_ARG_ID,
        name="operation",
        template="audio_mute",
    ),
    # --- Routing: additional hardcoded artifacts ---
    "artifact_attempt": dict(
        id=sid("args_output/artifact_attempt"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="attempt",
    ),
    "artifact_test": dict(
        id=sid("args_output/artifact_test"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="test",
    ),
    "artifact_dashboard": dict(
        id=sid("args_output/artifact_dashboard"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="dashboard",
    ),
    "artifact_reports": dict(
        id=sid("args_output/artifact_reports"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="reports",
    ),
    "artifact_leaderboard": dict(
        id=sid("args_output/artifact_leaderboard"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="leaderboard",
    ),
    "artifact_activity": dict(
        id=sid("args_output/artifact_activity"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="activity",
    ),
    "artifact_health": dict(
        id=sid("args_output/artifact_health"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="health",
    ),
    "artifact_benchmark": dict(
        id=sid("args_output/artifact_benchmark"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="benchmark",
    ),
    "artifact_home": dict(
        id=sid("args_output/artifact_home"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="home",
    ),
    "artifact_practice": dict(
        id=sid("args_output/artifact_practice"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="practice",
    ),
    "artifact_pricing": dict(
        id=sid("args_output/artifact_pricing"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="pricing",
    ),
    "artifact_record": dict(
        id=sid("args_output/artifact_record"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="record",
    ),
    "artifact_session": dict(
        id=sid("args_output/artifact_session"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="session",
    ),
    "artifact_chat": dict(
        id=sid("args_output/artifact_chat"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="chat",
    ),
    "artifact_invocation": dict(
        id=sid("args_output/artifact_invocation"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="invocation",
    ),
    "artifact_group": dict(
        id=sid("args_output/artifact_group"),
        args_id=_ARTIFACT_ARG_ID,
        name="artifact",
        template="group",
    ),
    # --- Payload: auto-generated pass-through outputs ---
    "active": dict(
        id=sid("args_output/active"),
        args_id=sid("arg/active"),
        name="active",
        template="{{ active }}",
    ),
    "actor_profile_id": dict(
        id=sid("args_output/actor_profile_id"),
        args_id=sid("arg/actor_profile_id"),
        name="actor_profile_id",
        template="{{ actor_profile_id }}",
    ),
    "agent_search": dict(
        id=sid("args_output/agent_search"),
        args_id=sid("arg/agent_search"),
        name="agent_search",
        template="{{ agent_search }}",
    ),
    "analyses": dict(
        id=sid("args_output/analyses"),
        args_id=sid("arg/analyses"),
        name="analyses",
        template="{{ analyses }}",
    ),
    "archived": dict(
        id=sid("args_output/archived"),
        args_id=sid("arg/archived"),
        name="archived",
        template="{{ archived }}",
    ),
    "artifact": dict(
        id=sid("args_output/artifact"),
        args_id=sid("arg/artifact"),
        name="artifact",
        template="{{ artifact }}",
    ),
    "assistant_content": dict(
        id=sid("args_output/assistant_content"),
        args_id=sid("arg/assistant_content"),
        name="assistant_content",
        template="{{ assistant_content }}",
    ),
    "attempt_ids": dict(
        id=sid("args_output/attempt_ids"),
        args_id=sid("arg/attempt_ids"),
        name="attempt_ids",
        template="{{ attempt_ids }}",
    ),
    "auth_id": dict(
        id=sid("args_output/auth_id"),
        args_id=sid("arg/auth_id"),
        name="auth_id",
        template="{{ auth_id }}",
    ),
    "benchmark_id": dict(
        id=sid("args_output/benchmark_id"),
        args_id=sid("arg/benchmark_id"),
        name="benchmark_id",
        template="{{ benchmark_id }}",
    ),
    "chat_entry_id": dict(
        id=sid("args_output/chat_entry_id"),
        args_id=sid("arg/chat_entry_id"),
        name="chat_entry_id",
        template="{{ chat_entry_id }}",
    ),
    "cohort_id": dict(
        id=sid("args_output/cohort_id"),
        args_id=sid("arg/cohort_id"),
        name="cohort_id",
        template="{{ cohort_id }}",
    ),
    "cohort_ids": dict(
        id=sid("args_output/cohort_ids"),
        args_id=sid("arg/cohort_ids"),
        name="cohort_ids",
        template="{{ cohort_ids }}",
    ),
    "cohort_search": dict(
        id=sid("args_output/cohort_search"),
        args_id=sid("arg/cohort_search"),
        name="cohort_search",
        template="{{ cohort_search }}",
    ),
    "color_search": dict(
        id=sid("args_output/color_search"),
        args_id=sid("arg/color_search"),
        name="color_search",
        template="{{ color_search }}",
    ),
    "contents": dict(
        id=sid("args_output/contents"),
        args_id=sid("arg/contents"),
        name="contents",
        template="{{ contents }}",
    ),
    "cursor": dict(
        id=sid("args_output/cursor"),
        args_id=sid("arg/cursor"),
        name="cursor",
        template="{{ cursor }}",
    ),
    "date_from": dict(
        id=sid("args_output/date_from"),
        args_id=sid("arg/date_from"),
        name="date_from",
        template="{{ date_from }}",
    ),
    "date_to": dict(
        id=sid("args_output/date_to"),
        args_id=sid("arg/date_to"),
        name="date_to",
        template="{{ date_to }}",
    ),
    "department_id": dict(
        id=sid("args_output/department_id"),
        args_id=sid("arg/department_id"),
        name="department_id",
        template="{{ department_id }}",
    ),
    "department_ids": dict(
        id=sid("args_output/department_ids"),
        args_id=sid("arg/department_ids"),
        name="department_ids",
        template="{{ department_ids }}",
    ),
    "department_search": dict(
        id=sid("args_output/department_search"),
        args_id=sid("arg/department_search"),
        name="department_search",
        template="{{ department_search }}",
    ),
    "descriptions_search": dict(
        id=sid("args_output/descriptions_search"),
        args_id=sid("arg/descriptions_search"),
        name="descriptions_search",
        template="{{ descriptions_search }}",
    ),
    "document_id": dict(
        id=sid("args_output/document_id"),
        args_id=sid("arg/document_id"),
        name="document_id",
        template="{{ document_id }}",
    ),
    "end_date": dict(
        id=sid("args_output/end_date"),
        args_id=sid("arg/end_date"),
        name="end_date",
        template="{{ end_date }}",
    ),
    "eval_id": dict(
        id=sid("args_output/eval_id"),
        args_id=sid("arg/eval_id"),
        name="eval_id",
        template="{{ eval_id }}",
    ),
    "feedbacks": dict(
        id=sid("args_output/feedbacks"),
        args_id=sid("arg/feedbacks"),
        name="feedbacks",
        template="{{ feedbacks }}",
    ),
    "field_id": dict(
        id=sid("args_output/field_id"),
        args_id=sid("arg/field_id"),
        name="field_id",
        template="{{ field_id }}",
    ),
    "field_ids": dict(
        id=sid("args_output/field_ids"),
        args_id=sid("arg/field_ids"),
        name="field_ids",
        template="{{ field_ids }}",
    ),
    "field_search": dict(
        id=sid("args_output/field_search"),
        args_id=sid("arg/field_search"),
        name="field_search",
        template="{{ field_search }}",
    ),
    "filter_agent_ids": dict(
        id=sid("args_output/filter_agent_ids"),
        args_id=sid("arg/filter_agent_ids"),
        name="filter_agent_ids",
        template="{{ filter_agent_ids }}",
    ),
    "filter_cohort_ids": dict(
        id=sid("args_output/filter_cohort_ids"),
        args_id=sid("arg/filter_cohort_ids"),
        name="filter_cohort_ids",
        template="{{ filter_cohort_ids }}",
    ),
    "filter_creatable": dict(
        id=sid("args_output/filter_creatable"),
        args_id=sid("arg/filter_creatable"),
        name="filter_creatable",
        template="{{ filter_creatable }}",
    ),
    "filter_department_ids": dict(
        id=sid("args_output/filter_department_ids"),
        args_id=sid("arg/filter_department_ids"),
        name="filter_department_ids",
        template="{{ filter_department_ids }}",
    ),
    "filter_model_ids": dict(
        id=sid("args_output/filter_model_ids"),
        args_id=sid("arg/filter_model_ids"),
        name="filter_model_ids",
        template="{{ filter_model_ids }}",
    ),
    "filter_profile_ids": dict(
        id=sid("args_output/filter_profile_ids"),
        args_id=sid("arg/filter_profile_ids"),
        name="filter_profile_ids",
        template="{{ filter_profile_ids }}",
    ),
    "filter_provider_ids": dict(
        id=sid("args_output/filter_provider_ids"),
        args_id=sid("arg/filter_provider_ids"),
        name="filter_provider_ids",
        template="{{ filter_provider_ids }}",
    ),
    "filter_scenario_ids": dict(
        id=sid("args_output/filter_scenario_ids"),
        args_id=sid("arg/filter_scenario_ids"),
        name="filter_scenario_ids",
        template="{{ filter_scenario_ids }}",
    ),
    "filter_simulation_ids": dict(
        id=sid("args_output/filter_simulation_ids"),
        args_id=sid("arg/filter_simulation_ids"),
        name="filter_simulation_ids",
        template="{{ filter_simulation_ids }}",
    ),
    "filter_status": dict(
        id=sid("args_output/filter_status"),
        args_id=sid("arg/filter_status"),
        name="filter_status",
        template="{{ filter_status }}",
    ),
    "filter_tool_ids": dict(
        id=sid("args_output/filter_tool_ids"),
        args_id=sid("arg/filter_tool_ids"),
        name="filter_tool_ids",
        template="{{ filter_tool_ids }}",
    ),
    "flag_search": dict(
        id=sid("args_output/flag_search"),
        args_id=sid("arg/flag_search"),
        name="flag_search",
        template="{{ flag_search }}",
    ),
    "group_id": dict(
        id=sid("args_output/group_id"),
        args_id=sid("arg/group_id"),
        name="group_id",
        template="{{ group_id }}",
    ),
    "highlights": dict(
        id=sid("args_output/highlights"),
        args_id=sid("arg/highlights"),
        name="highlights",
        template="{{ highlights }}",
    ),
    "hints": dict(
        id=sid("args_output/hints"),
        args_id=sid("arg/hints"),
        name="hints",
        template="{{ hints }}",
    ),
    "history_archived": dict(
        id=sid("args_output/history_archived"),
        args_id=sid("arg/history_archived"),
        name="history_archived",
        template="{{ history_archived }}",
    ),
    "history_eval_ids": dict(
        id=sid("args_output/history_eval_ids"),
        args_id=sid("arg/history_eval_ids"),
        name="history_eval_ids",
        template="{{ history_eval_ids }}",
    ),
    "history_infinite_mode": dict(
        id=sid("args_output/history_infinite_mode"),
        args_id=sid("arg/history_infinite_mode"),
        name="history_infinite_mode",
        template="{{ history_infinite_mode }}",
    ),
    "history_page": dict(
        id=sid("args_output/history_page"),
        args_id=sid("arg/history_page"),
        name="history_page",
        template="{{ history_page }}",
    ),
    "history_page_size": dict(
        id=sid("args_output/history_page_size"),
        args_id=sid("arg/history_page_size"),
        name="history_page_size",
        template="{{ history_page_size }}",
    ),
    "history_practice": dict(
        id=sid("args_output/history_practice"),
        args_id=sid("arg/history_practice"),
        name="history_practice",
        template="{{ history_practice }}",
    ),
    "history_profile_search": dict(
        id=sid("args_output/history_profile_search"),
        args_id=sid("arg/history_profile_search"),
        name="history_profile_search",
        template="{{ history_profile_search }}",
    ),
    "history_scenario_ids": dict(
        id=sid("args_output/history_scenario_ids"),
        args_id=sid("arg/history_scenario_ids"),
        name="history_scenario_ids",
        template="{{ history_scenario_ids }}",
    ),
    "history_scenario_search": dict(
        id=sid("args_output/history_scenario_search"),
        args_id=sid("arg/history_scenario_search"),
        name="history_scenario_search",
        template="{{ history_scenario_search }}",
    ),
    "history_search": dict(
        id=sid("args_output/history_search"),
        args_id=sid("arg/history_search"),
        name="history_search",
        template="{{ history_search }}",
    ),
    "history_show_archived": dict(
        id=sid("args_output/history_show_archived"),
        args_id=sid("arg/history_show_archived"),
        name="history_show_archived",
        template="{{ history_show_archived }}",
    ),
    "history_simulation_search": dict(
        id=sid("args_output/history_simulation_search"),
        args_id=sid("arg/history_simulation_search"),
        name="history_simulation_search",
        template="{{ history_simulation_search }}",
    ),
    "history_sort_by": dict(
        id=sid("args_output/history_sort_by"),
        args_id=sid("arg/history_sort_by"),
        name="history_sort_by",
        template="{{ history_sort_by }}",
    ),
    "history_sort_order": dict(
        id=sid("args_output/history_sort_order"),
        args_id=sid("arg/history_sort_order"),
        name="history_sort_order",
        template="{{ history_sort_order }}",
    ),
    "home_id": dict(
        id=sid("args_output/home_id"),
        args_id=sid("arg/home_id"),
        name="home_id",
        template="{{ home_id }}",
    ),
    "icon_search": dict(
        id=sid("args_output/icon_search"),
        args_id=sid("arg/icon_search"),
        name="icon_search",
        template="{{ icon_search }}",
    ),
    "improvements": dict(
        id=sid("args_output/improvements"),
        args_id=sid("arg/improvements"),
        name="improvements",
        template="{{ improvements }}",
    ),
    "include_entries": dict(
        id=sid("args_output/include_entries"),
        args_id=sid("arg/include_entries"),
        name="include_entries",
        template="{{ include_entries }}",
    ),
    "infinite_mode": dict(
        id=sid("args_output/infinite_mode"),
        args_id=sid("arg/infinite_mode"),
        name="infinite_mode",
        template="{{ infinite_mode }}",
    ),
    "instruction_search": dict(
        id=sid("args_output/instruction_search"),
        args_id=sid("arg/instruction_search"),
        name="instruction_search",
        template="{{ instruction_search }}",
    ),
    "invocation_entry_id": dict(
        id=sid("args_output/invocation_entry_id"),
        args_id=sid("arg/invocation_entry_id"),
        name="invocation_entry_id",
        template="{{ invocation_entry_id }}",
    ),
    "invocation_id": dict(
        id=sid("args_output/invocation_id"),
        args_id=sid("arg/invocation_id"),
        name="invocation_id",
        template="{{ invocation_id }}",
    ),
    "limit": dict(
        id=sid("args_output/limit"),
        args_id=sid("arg/limit"),
        name="limit",
        template="{{ limit }}",
    ),
    "message_limit": dict(
        id=sid("args_output/message_limit"),
        args_id=sid("arg/message_limit"),
        name="message_limit",
        template="{{ message_limit }}",
    ),
    "message_offset": dict(
        id=sid("args_output/message_offset"),
        args_id=sid("arg/message_offset"),
        name="message_offset",
        template="{{ message_offset }}",
    ),
    "model_id": dict(
        id=sid("args_output/model_id"),
        args_id=sid("arg/model_id"),
        name="model_id",
        template="{{ model_id }}",
    ),
    "model_search": dict(
        id=sid("args_output/model_search"),
        args_id=sid("arg/model_search"),
        name="model_search",
        template="{{ model_search }}",
    ),
    "operation": dict(
        id=sid("args_output/operation"),
        args_id=sid("arg/operation"),
        name="operation",
        template="{{ operation }}",
    ),
    "page_limit": dict(
        id=sid("args_output/page_limit"),
        args_id=sid("arg/page_limit"),
        name="page_limit",
        template="{{ page_limit }}",
    ),
    "page_offset": dict(
        id=sid("args_output/page_offset"),
        args_id=sid("arg/page_offset"),
        name="page_offset",
        template="{{ page_offset }}",
    ),
    "parameter_id": dict(
        id=sid("args_output/parameter_id"),
        args_id=sid("arg/parameter_id"),
        name="parameter_id",
        template="{{ parameter_id }}",
    ),
    "parameter_ids": dict(
        id=sid("args_output/parameter_ids"),
        args_id=sid("arg/parameter_ids"),
        name="parameter_ids",
        template="{{ parameter_ids }}",
    ),
    "parameter_search": dict(
        id=sid("args_output/parameter_search"),
        args_id=sid("arg/parameter_search"),
        name="parameter_search",
        template="{{ parameter_search }}",
    ),
    "parent_message_id": dict(
        id=sid("args_output/parent_message_id"),
        args_id=sid("arg/parent_message_id"),
        name="parent_message_id",
        template="{{ parent_message_id }}",
    ),
    "passed": dict(
        id=sid("args_output/passed"),
        args_id=sid("arg/passed"),
        name="passed",
        template="{{ passed }}",
    ),
    "persona_ids": dict(
        id=sid("args_output/persona_ids"),
        args_id=sid("arg/persona_ids"),
        name="persona_ids",
        template="{{ persona_ids }}",
    ),
    "persona_search": dict(
        id=sid("args_output/persona_search"),
        args_id=sid("arg/persona_search"),
        name="persona_search",
        template="{{ persona_search }}",
    ),
    "practice": dict(
        id=sid("args_output/practice"),
        args_id=sid("arg/practice"),
        name="practice",
        template="{{ practice }}",
    ),
    "practice_id": dict(
        id=sid("args_output/practice_id"),
        args_id=sid("arg/practice_id"),
        name="practice_id",
        template="{{ practice_id }}",
    ),
    "problem_id": dict(
        id=sid("args_output/problem_id"),
        args_id=sid("arg/problem_id"),
        name="problem_id",
        template="{{ problem_id }}",
    ),
    "profile_export_id": dict(
        id=sid("args_output/profile_export_id"),
        args_id=sid("arg/profile_export_id"),
        name="profile_export_id",
        template="{{ profile_export_id }}",
    ),
    "profile_ids": dict(
        id=sid("args_output/profile_ids"),
        args_id=sid("arg/profile_ids"),
        name="profile_ids",
        template="{{ profile_ids }}",
    ),
    "profile_ids_filter": dict(
        id=sid("args_output/profile_ids_filter"),
        args_id=sid("arg/profile_ids_filter"),
        name="profile_ids_filter",
        template="{{ profile_ids_filter }}",
    ),
    "profile_search": dict(
        id=sid("args_output/profile_search"),
        args_id=sid("arg/profile_search"),
        name="profile_search",
        template="{{ profile_search }}",
    ),
    "profile_show_selected": dict(
        id=sid("args_output/profile_show_selected"),
        args_id=sid("arg/profile_show_selected"),
        name="profile_show_selected",
        template="{{ profile_show_selected }}",
    ),
    "provider_id": dict(
        id=sid("args_output/provider_id"),
        args_id=sid("arg/provider_id"),
        name="provider_id",
        template="{{ provider_id }}",
    ),
    "provider_search": dict(
        id=sid("args_output/provider_search"),
        args_id=sid("arg/provider_search"),
        name="provider_search",
        template="{{ provider_search }}",
    ),
    "replacements": dict(
        id=sid("args_output/replacements"),
        args_id=sid("arg/replacements"),
        name="replacements",
        template="{{ replacements }}",
    ),
    "resolved": dict(
        id=sid("args_output/resolved"),
        args_id=sid("arg/resolved"),
        name="resolved",
        template="{{ resolved }}",
    ),
    "resource_types": dict(
        id=sid("args_output/resource_types"),
        args_id=sid("arg/resource_types"),
        name="resource_types",
        template="{{ resource_types }}",
    ),
    "role_filter": dict(
        id=sid("args_output/role_filter"),
        args_id=sid("arg/role_filter"),
        name="role_filter",
        template="{{ role_filter }}",
    ),
    "role_search": dict(
        id=sid("args_output/role_search"),
        args_id=sid("arg/role_search"),
        name="role_search",
        template="{{ role_search }}",
    ),
    "roles": dict(
        id=sid("args_output/roles"),
        args_id=sid("arg/roles"),
        name="roles",
        template="{{ roles }}",
    ),
    "rubric_id": dict(
        id=sid("args_output/rubric_id"),
        args_id=sid("arg/rubric_id"),
        name="rubric_id",
        template="{{ rubric_id }}",
    ),
    "rubric_ids": dict(
        id=sid("args_output/rubric_ids"),
        args_id=sid("arg/rubric_ids"),
        name="rubric_ids",
        template="{{ rubric_ids }}",
    ),
    "rubric_search": dict(
        id=sid("args_output/rubric_search"),
        args_id=sid("arg/rubric_search"),
        name="rubric_search",
        template="{{ rubric_search }}",
    ),
    "run_id": dict(
        id=sid("args_output/run_id"),
        args_id=sid("arg/run_id"),
        name="run_id",
        template="{{ run_id }}",
    ),
    "scenario_ids": dict(
        id=sid("args_output/scenario_ids"),
        args_id=sid("arg/scenario_ids"),
        name="scenario_ids",
        template="{{ scenario_ids }}",
    ),
    "scenario_search": dict(
        id=sid("args_output/scenario_search"),
        args_id=sid("arg/scenario_search"),
        name="scenario_search",
        template="{{ scenario_search }}",
    ),
    "service": dict(
        id=sid("args_output/service"),
        args_id=sid("arg/service"),
        name="service",
        template="{{ service }}",
    ),
    "setting_id": dict(
        id=sid("args_output/setting_id"),
        args_id=sid("arg/setting_id"),
        name="setting_id",
        template="{{ setting_id }}",
    ),
    "show_archived": dict(
        id=sid("args_output/show_archived"),
        args_id=sid("arg/show_archived"),
        name="show_archived",
        template="{{ show_archived }}",
    ),
    "simulation_filters": dict(
        id=sid("args_output/simulation_filters"),
        args_id=sid("arg/simulation_filters"),
        name="simulation_filters",
        template="{{ simulation_filters }}",
    ),
    "simulation_ids": dict(
        id=sid("args_output/simulation_ids"),
        args_id=sid("arg/simulation_ids"),
        name="simulation_ids",
        template="{{ simulation_ids }}",
    ),
    "simulation_picker_ids": dict(
        id=sid("args_output/simulation_picker_ids"),
        args_id=sid("arg/simulation_picker_ids"),
        name="simulation_picker_ids",
        template="{{ simulation_picker_ids }}",
    ),
    "simulation_picker_search": dict(
        id=sid("args_output/simulation_picker_search"),
        args_id=sid("arg/simulation_picker_search"),
        name="simulation_picker_search",
        template="{{ simulation_picker_search }}",
    ),
    "simulation_search": dict(
        id=sid("args_output/simulation_search"),
        args_id=sid("arg/simulation_search"),
        name="simulation_search",
        template="{{ simulation_search }}",
    ),
    "simulation_show_selected": dict(
        id=sid("args_output/simulation_show_selected"),
        args_id=sid("arg/simulation_show_selected"),
        name="simulation_show_selected",
        template="{{ simulation_show_selected }}",
    ),
    "sort_by": dict(
        id=sid("args_output/sort_by"),
        args_id=sid("arg/sort_by"),
        name="sort_by",
        template="{{ sort_by }}",
    ),
    "sort_order": dict(
        id=sid("args_output/sort_order"),
        args_id=sid("arg/sort_order"),
        name="sort_order",
        template="{{ sort_order }}",
    ),
    "start_date": dict(
        id=sid("args_output/start_date"),
        args_id=sid("arg/start_date"),
        name="start_date",
        template="{{ start_date }}",
    ),
    "strengths": dict(
        id=sid("args_output/strengths"),
        args_id=sid("arg/strengths"),
        name="strengths",
        template="{{ strengths }}",
    ),
    "target_profile_id": dict(
        id=sid("args_output/target_profile_id"),
        args_id=sid("arg/target_profile_id"),
        name="target_profile_id",
        template="{{ target_profile_id }}",
    ),
    "target_session_id": dict(
        id=sid("args_output/target_session_id"),
        args_id=sid("arg/target_session_id"),
        name="target_session_id",
        template="{{ target_session_id }}",
    ),
    "test_ids": dict(
        id=sid("args_output/test_ids"),
        args_id=sid("arg/test_ids"),
        name="test_ids",
        template="{{ test_ids }}",
    ),
    "test_invocation_id": dict(
        id=sid("args_output/test_invocation_id"),
        args_id=sid("arg/test_invocation_id"),
        name="test_invocation_id",
        template="{{ test_invocation_id }}",
    ),
    "time_taken": dict(
        id=sid("args_output/time_taken"),
        args_id=sid("arg/time_taken"),
        name="time_taken",
        template="{{ time_taken }}",
    ),
    "tool_id": dict(
        id=sid("args_output/tool_id"),
        args_id=sid("arg/tool_id"),
        name="tool_id",
        template="{{ tool_id }}",
    ),
    "tool_search": dict(
        id=sid("args_output/tool_search"),
        args_id=sid("arg/tool_search"),
        name="tool_search",
        template="{{ tool_search }}",
    ),
    "type": dict(
        id=sid("args_output/type"),
        args_id=sid("arg/type"),
        name="type",
        template="{{ type }}",
    ),
    "user_instructions": dict(
        id=sid("args_output/user_instructions"),
        args_id=sid("arg/user_instructions"),
        name="user_instructions",
        template="{{ user_instructions }}",
    ),
    "voice_search": dict(
        id=sid("args_output/voice_search"),
        args_id=sid("arg/voice_search"),
        name="voice_search",
        template="{{ voice_search }}",
    ),

}

# Flat list for seeding
args_outputs = list(SHARED_ARGS_OUTPUTS.values())
