"""Shared argument resource seeds.

Each arg is defined once with a deterministic ID. Tools reference args
by key instead of inlining duplicate definitions.

Generated from 137 unique args across 259 tools.
Regenerate with: python database/scripts/generate_shared_args.py
"""

from database.seeds.ids import sid

SHARED_ARGS = {
    "active": dict(id=sid("arg/active"), name="active", field_type="boolean"),
    "actor_profile_id": dict(id=sid("arg/actor_profile_id"), name="actor_profile_id", field_type="uuid"),
    "artifact": dict(id=sid("arg/artifact"), name="artifact", field_type="string", description="Target artifact type (e.g. persona, scenario)"),
    "operation": dict(id=sid("arg/operation"), name="operation", field_type="string", description="Target operation (e.g. create, update)"),
    "name": dict(id=sid("arg/name"), name="name", field_type="string", description="Display name"),
    "description": dict(id=sid("arg/description"), name="description", field_type="string", description="Description text"),
    "instructions": dict(id=sid("arg/instructions"), name="instructions", field_type="string", description="Instruction template"),
    "color": dict(id=sid("arg/color"), name="color", field_type="string", description="Color value"),
    "content": dict(id=sid("arg/content"), name="content", field_type="string", description="Text content"),
    "icon": dict(id=sid("arg/icon"), name="icon", field_type="string", description="Icon identifier"),
    "image": dict(id=sid("arg/image"), name="image", field_type="string", description="Base64-encoded image data"),
    "image_id": dict(id=sid("arg/image_id"), name="image_id", field_type="uuid", description="Image resource UUID"),
    "problem_statement": dict(id=sid("arg/problem_statement"), name="problem_statement", field_type="string", description="Problem statement text"),
    "agent_search": dict(id=sid("arg/agent_search"), name="agent_search", field_type="string"),
    "analyses": dict(id=sid("arg/analyses"), name="analyses", field_type="object[]"),
    "archived": dict(id=sid("arg/archived"), name="archived", field_type="boolean", required=True),
    "assistant_content": dict(id=sid("arg/assistant_content"), name="assistant_content", field_type="string"),
    "attempt_id": dict(id=sid("arg/attempt_id"), name="attempt_id", field_type="uuid", required=True),
    "audio": dict(id=sid("arg/audio"), name="audio", field_type="string", description="Base64-encoded audio data"),
    "audio_id": dict(id=sid("arg/audio_id"), name="audio_id", field_type="uuid", description="Audio resource UUID"),
    "attempt_ids": dict(id=sid("arg/attempt_ids"), name="attempt_ids", field_type="uuid[]"),
    "auth_id": dict(id=sid("arg/auth_id"), name="auth_id", field_type="uuid"),
    "benchmark_id": dict(id=sid("arg/benchmark_id"), name="benchmark_id", field_type="uuid"),
    "chat_entry_id": dict(id=sid("arg/chat_entry_id"), name="chat_entry_id", field_type="uuid", required=True),
    "chat_id": dict(id=sid("arg/chat_id"), name="chat_id", field_type="uuid", required=True),
    "cohort_id": dict(id=sid("arg/cohort_id"), name="cohort_id", field_type="uuid"),
    "cohort_ids": dict(id=sid("arg/cohort_ids"), name="cohort_ids", field_type="uuid[]"),
    "cohort_search": dict(id=sid("arg/cohort_search"), name="cohort_search", field_type="string"),
    "color_search": dict(id=sid("arg/color_search"), name="color_search", field_type="string"),
    "contents": dict(id=sid("arg/contents"), name="contents", field_type="object[]"),
    "cursor": dict(id=sid("arg/cursor"), name="cursor", field_type="string"),
    "date_from": dict(id=sid("arg/date_from"), name="date_from", field_type="string"),
    "date_to": dict(id=sid("arg/date_to"), name="date_to", field_type="string"),
    "department_id": dict(id=sid("arg/department_id"), name="department_id", field_type="uuid"),
    "department_ids": dict(id=sid("arg/department_ids"), name="department_ids", field_type="string[]"),
    "department_search": dict(id=sid("arg/department_search"), name="department_search", field_type="string"),
    "descriptions_search": dict(id=sid("arg/descriptions_search"), name="descriptions_search", field_type="string"),
    "document_id": dict(id=sid("arg/document_id"), name="document_id", field_type="uuid"),
    "draft_id": dict(id=sid("arg/draft_id"), name="draft_id", field_type="uuid"),
    "end_date": dict(id=sid("arg/end_date"), name="end_date", field_type="string"),
    "eval_id": dict(id=sid("arg/eval_id"), name="eval_id", field_type="uuid"),
    "feedback": dict(id=sid("arg/feedback"), name="feedback", field_type="string"),
    "feedbacks": dict(id=sid("arg/feedbacks"), name="feedbacks", field_type="object[]"),
    "file": dict(id=sid("arg/file"), name="file", field_type="string", description="Base64-encoded file data"),
    "file_id": dict(id=sid("arg/file_id"), name="file_id", field_type="uuid", description="File resource UUID"),
    "field_id": dict(id=sid("arg/field_id"), name="field_id", field_type="uuid"),
    "field_ids": dict(id=sid("arg/field_ids"), name="field_ids", field_type="uuid[]"),
    "field_search": dict(id=sid("arg/field_search"), name="field_search", field_type="string"),
    "filter_agent_ids": dict(id=sid("arg/filter_agent_ids"), name="filter_agent_ids", field_type="uuid[]"),
    "filter_cohort_ids": dict(id=sid("arg/filter_cohort_ids"), name="filter_cohort_ids", field_type="uuid[]"),
    "filter_creatable": dict(id=sid("arg/filter_creatable"), name="filter_creatable", field_type="string[]"),
    "filter_department_ids": dict(id=sid("arg/filter_department_ids"), name="filter_department_ids", field_type="uuid[]"),
    "filter_model_ids": dict(id=sid("arg/filter_model_ids"), name="filter_model_ids", field_type="uuid[]"),
    "filter_profile_ids": dict(id=sid("arg/filter_profile_ids"), name="filter_profile_ids", field_type="uuid[]"),
    "filter_provider_ids": dict(id=sid("arg/filter_provider_ids"), name="filter_provider_ids", field_type="uuid[]"),
    "filter_scenario_ids": dict(id=sid("arg/filter_scenario_ids"), name="filter_scenario_ids", field_type="uuid[]"),
    "filter_simulation_ids": dict(id=sid("arg/filter_simulation_ids"), name="filter_simulation_ids", field_type="uuid[]"),
    "filter_status": dict(id=sid("arg/filter_status"), name="filter_status", field_type="string[]"),
    "filter_tool_ids": dict(id=sid("arg/filter_tool_ids"), name="filter_tool_ids", field_type="uuid[]"),
    "flag_search": dict(id=sid("arg/flag_search"), name="flag_search", field_type="string"),
    "grade": dict(id=sid("arg/grade"), name="grade", field_type="boolean"),
    "group_id": dict(id=sid("arg/group_id"), name="group_id", field_type="uuid", required=True),
    "highlights": dict(id=sid("arg/highlights"), name="highlights", field_type="object[]"),
    "hints": dict(id=sid("arg/hints"), name="hints", field_type="object[]"),
    "history_archived": dict(id=sid("arg/history_archived"), name="history_archived", field_type="boolean"),
    "history_eval_ids": dict(id=sid("arg/history_eval_ids"), name="history_eval_ids", field_type="string[]"),
    "history_infinite_mode": dict(id=sid("arg/history_infinite_mode"), name="history_infinite_mode", field_type="boolean"),
    "history_page": dict(id=sid("arg/history_page"), name="history_page", field_type="integer"),
    "history_page_size": dict(id=sid("arg/history_page_size"), name="history_page_size", field_type="integer"),
    "history_practice": dict(id=sid("arg/history_practice"), name="history_practice", field_type="boolean"),
    "history_profile_search": dict(id=sid("arg/history_profile_search"), name="history_profile_search", field_type="string"),
    "history_scenario_ids": dict(id=sid("arg/history_scenario_ids"), name="history_scenario_ids", field_type="uuid[]"),
    "history_scenario_search": dict(id=sid("arg/history_scenario_search"), name="history_scenario_search", field_type="string"),
    "history_search": dict(id=sid("arg/history_search"), name="history_search", field_type="string"),
    "history_show_archived": dict(id=sid("arg/history_show_archived"), name="history_show_archived", field_type="boolean"),
    "history_simulation_search": dict(id=sid("arg/history_simulation_search"), name="history_simulation_search", field_type="string"),
    "history_sort_by": dict(id=sid("arg/history_sort_by"), name="history_sort_by", field_type="string"),
    "history_sort_order": dict(id=sid("arg/history_sort_order"), name="history_sort_order", field_type="string"),
    "home_id": dict(id=sid("arg/home_id"), name="home_id", field_type="uuid"),
    "icon_search": dict(id=sid("arg/icon_search"), name="icon_search", field_type="string"),
    "improvements": dict(id=sid("arg/improvements"), name="improvements", field_type="object[]"),
    "include_entries": dict(id=sid("arg/include_entries"), name="include_entries", field_type="string[]"),
    "infinite_mode": dict(id=sid("arg/infinite_mode"), name="infinite_mode", field_type="boolean"),
    "instruction_search": dict(id=sid("arg/instruction_search"), name="instruction_search", field_type="string"),
    "invocation_entry_id": dict(id=sid("arg/invocation_entry_id"), name="invocation_entry_id", field_type="uuid"),
    "invocation_id": dict(id=sid("arg/invocation_id"), name="invocation_id", field_type="uuid"),
    "limit": dict(id=sid("arg/limit"), name="limit", field_type="integer"),
    "message": dict(id=sid("arg/message"), name="message", field_type="string", required=True),
    "message_limit": dict(id=sid("arg/message_limit"), name="message_limit", field_type="integer"),
    "message_offset": dict(id=sid("arg/message_offset"), name="message_offset", field_type="integer"),
    "model_id": dict(id=sid("arg/model_id"), name="model_id", field_type="uuid"),
    "model_search": dict(id=sid("arg/model_search"), name="model_search", field_type="string"),
    "page": dict(id=sid("arg/page"), name="page", field_type="integer"),
    "page_limit": dict(id=sid("arg/page_limit"), name="page_limit", field_type="integer"),
    "page_offset": dict(id=sid("arg/page_offset"), name="page_offset", field_type="integer"),
    "page_size": dict(id=sid("arg/page_size"), name="page_size", field_type="integer"),
    "parameter_id": dict(id=sid("arg/parameter_id"), name="parameter_id", field_type="uuid"),
    "parameter_ids": dict(id=sid("arg/parameter_ids"), name="parameter_ids", field_type="uuid[]"),
    "parameter_search": dict(id=sid("arg/parameter_search"), name="parameter_search", field_type="string"),
    "parent_message_id": dict(id=sid("arg/parent_message_id"), name="parent_message_id", field_type="uuid"),
    "passed": dict(id=sid("arg/passed"), name="passed", field_type="boolean"),
    "persona_ids": dict(id=sid("arg/persona_ids"), name="persona_ids", field_type="uuid[]"),
    "persona_search": dict(id=sid("arg/persona_search"), name="persona_search", field_type="string"),
    "practice": dict(id=sid("arg/practice"), name="practice", field_type="boolean"),
    "practice_id": dict(id=sid("arg/practice_id"), name="practice_id", field_type="uuid"),
    "problem_id": dict(id=sid("arg/problem_id"), name="problem_id", field_type="uuid", required=True),
    "profile_export_id": dict(id=sid("arg/profile_export_id"), name="profile_export_id", field_type="uuid"),
    "profile_ids": dict(id=sid("arg/profile_ids"), name="profile_ids", field_type="uuid[]"),
    "profile_ids_filter": dict(id=sid("arg/profile_ids_filter"), name="profile_ids_filter", field_type="uuid[]"),
    "profile_search": dict(id=sid("arg/profile_search"), name="profile_search", field_type="string"),
    "profile_show_selected": dict(id=sid("arg/profile_show_selected"), name="profile_show_selected", field_type="boolean"),
    "provider_id": dict(id=sid("arg/provider_id"), name="provider_id", field_type="uuid"),
    "provider_search": dict(id=sid("arg/provider_search"), name="provider_search", field_type="string"),
    "replacements": dict(id=sid("arg/replacements"), name="replacements", field_type="object[]"),
    "resolved": dict(id=sid("arg/resolved"), name="resolved", field_type="boolean"),
    "resource_types": dict(id=sid("arg/resource_types"), name="resource_types", field_type="string[]"),
    "role_filter": dict(id=sid("arg/role_filter"), name="role_filter", field_type="string"),
    "role_search": dict(id=sid("arg/role_search"), name="role_search", field_type="string"),
    "roles": dict(id=sid("arg/roles"), name="roles", field_type="string[]"),
    "rubric_id": dict(id=sid("arg/rubric_id"), name="rubric_id", field_type="uuid"),
    "rubric_ids": dict(id=sid("arg/rubric_ids"), name="rubric_ids", field_type="uuid[]"),
    "rubric_search": dict(id=sid("arg/rubric_search"), name="rubric_search", field_type="string"),
    "run_id": dict(id=sid("arg/run_id"), name="run_id", field_type="uuid", required=True),
    "scenario_ids": dict(id=sid("arg/scenario_ids"), name="scenario_ids", field_type="uuid[]"),
    "scenario_search": dict(id=sid("arg/scenario_search"), name="scenario_search", field_type="string"),
    "score": dict(id=sid("arg/score"), name="score", field_type="integer"),
    "search": dict(id=sid("arg/search"), name="search", field_type="string"),
    "service": dict(id=sid("arg/service"), name="service", field_type="string"),
    "setting_id": dict(id=sid("arg/setting_id"), name="setting_id", field_type="uuid"),
    "show_archived": dict(id=sid("arg/show_archived"), name="show_archived", field_type="boolean"),
    "simulation_filters": dict(id=sid("arg/simulation_filters"), name="simulation_filters", field_type="string[]"),
    "simulation_id": dict(id=sid("arg/simulation_id"), name="simulation_id", field_type="uuid"),
    "simulation_ids": dict(id=sid("arg/simulation_ids"), name="simulation_ids", field_type="uuid[]"),
    "simulation_picker_ids": dict(id=sid("arg/simulation_picker_ids"), name="simulation_picker_ids", field_type="uuid[]"),
    "simulation_picker_search": dict(id=sid("arg/simulation_picker_search"), name="simulation_picker_search", field_type="string"),
    "simulation_search": dict(id=sid("arg/simulation_search"), name="simulation_search", field_type="string"),
    "simulation_show_selected": dict(id=sid("arg/simulation_show_selected"), name="simulation_show_selected", field_type="boolean"),
    "sort_by": dict(id=sid("arg/sort_by"), name="sort_by", field_type="string"),
    "sort_order": dict(id=sid("arg/sort_order"), name="sort_order", field_type="string"),
    "start_date": dict(id=sid("arg/start_date"), name="start_date", field_type="string"),
    "strengths": dict(id=sid("arg/strengths"), name="strengths", field_type="object[]"),
    "target_profile_id": dict(id=sid("arg/target_profile_id"), name="target_profile_id", field_type="uuid"),
    "target_session_id": dict(id=sid("arg/target_session_id"), name="target_session_id", field_type="uuid", required=True),
    "test_id": dict(id=sid("arg/test_id"), name="test_id", field_type="uuid", required=True),
    "text_id": dict(id=sid("arg/text_id"), name="text_id", field_type="uuid", description="Text resource UUID"),
    "test_ids": dict(id=sid("arg/test_ids"), name="test_ids", field_type="uuid[]", required=True),
    "test_invocation_id": dict(id=sid("arg/test_invocation_id"), name="test_invocation_id", field_type="uuid", required=True),
    "time_taken": dict(id=sid("arg/time_taken"), name="time_taken", field_type="integer"),
    "tool_id": dict(id=sid("arg/tool_id"), name="tool_id", field_type="uuid"),
    "tool_search": dict(id=sid("arg/tool_search"), name="tool_search", field_type="string"),
    "type": dict(id=sid("arg/type"), name="type", field_type="string", required=True),
    "user_instructions": dict(id=sid("arg/user_instructions"), name="user_instructions", field_type="string[]"),
    "video": dict(id=sid("arg/video"), name="video", field_type="string", description="Base64-encoded video data"),
    "video_id": dict(id=sid("arg/video_id"), name="video_id", field_type="uuid", description="Video resource UUID"),
    "voice_search": dict(id=sid("arg/voice_search"), name="voice_search", field_type="string"),
}

# Flat list for seeding
args = list(SHARED_ARGS.values())
