"""Flag resource seeds.

46 rows of feature flags and toggles used across different artifact types.
Flags control behaviors like active state, audio/text/video modes, rubric types,
and various scenario configuration options.
"""

from database.seeds.ids import sid

flags = [
    dict(
        id=sid("flag/active"),
        name="active",
        description="Active flag",
        type="active",
        icon_id=sid("icon/power"),
        value=True,
    ),
    dict(
        id=sid("flag/guest-login-enabled"),
        name="guest_login_enabled",
        description="Guest login enabled",
        type="guest_login_enabled",
        icon_id=sid("icon/user-check"),
        value=True,
    ),
    dict(
        id=sid("flag/practice"),
        name="Practice",
        description="Practice flag",
        type="practice",
        icon_id=sid("icon/target"),
        value=True,
    ),
    dict(
        id=sid("flag/video"),
        name="Video",
        description="Video enabled",
        type="video_enabled",
        icon_id=sid("icon/film"),
        value=True,
    ),
    dict(
        id=sid("flag/problem-statement"),
        name="Problem Statement",
        description="Problem statement enabled",
        type="problem_statement_enabled",
        icon_id=sid("icon/message-square"),
        value=True,
    ),
    dict(
        id=sid("flag/objectives"),
        name="Objectives",
        description="Objectives enabled",
        type="objectives_enabled",
        icon_id=sid("icon/target"),
        value=True,
    ),
    dict(
        id=sid("flag/questions"),
        name="Questions",
        description="Questions enabled",
        type="questions_enabled",
        icon_id=sid("icon/help-circle"),
        value=True,
    ),
    dict(
        id=sid("flag/images"),
        name="Images",
        description="Images enabled",
        type="images_enabled",
        icon_id=sid("icon/image"),
        value=True,
    ),
    dict(
        id=sid("flag/groups"),
        name="groups",
        description="Groups flag",
        type="groups",
        icon_id=sid("icon/users"),
        value=True,
    ),
    dict(
        id=sid("flag/dynamic"),
        name="dynamic",
        description="Dynamic flag",
        type="dynamic",
        icon_id=sid("icon/zap"),
        value=True,
    ),
    dict(
        id=sid("flag/template"),
        name="template",
        description="Template flag",
        type="template",
        icon_id=sid("icon/clipboard"),
        value=True,
    ),
    dict(
        id=sid("flag/audio-enabled"),
        name="Audio Enabled",
        description="Audio enabled flag for simulation scenario",
        type="audio_enabled",
        icon_id=sid("icon/volume"),
        value=True,
    ),
    dict(
        id=sid("flag/text-enabled"),
        name="Text Enabled",
        description="Text enabled flag for simulation scenario",
        type="text_enabled",
        icon_id=sid("icon/file-text"),
        value=True,
    ),
    dict(
        id=sid("flag/show-problem-statement"),
        name="Show Problem Statement",
        description="Show problem statement flag for simulation scenario",
        type="show_problem_statement",
        icon_id=sid("icon/message-square"),
        value=True,
    ),
    dict(
        id=sid("flag/show-objectives"),
        name="Show Objectives",
        description="Show objectives flag for simulation scenario",
        type="show_objectives",
        icon_id=sid("icon/target"),
        value=True,
    ),
    dict(
        id=sid("flag/show-images"),
        name="Show Images",
        description="Show images flag for simulation scenario",
        type="show_images",
        icon_id=sid("icon/image"),
        value=True,
    ),
    dict(
        id=sid("flag/hints-enabled"),
        name="Hints Enabled",
        description="Hints enabled flag for simulation scenario",
        type="hints_enabled",
        icon_id=sid("icon/lightbulb"),
        value=True,
    ),
    dict(
        id=sid("flag/copy-paste-allowed"),
        name="Copy Paste Allowed",
        description="Copy paste allowed flag for simulation scenario",
        type="copy_paste_allowed",
        icon_id=sid("icon/copy"),
        value=True,
    ),
    dict(
        id=sid("flag/use-templates"),
        name="use_templates",
        description="Use templates flag for scenarios",
        type="use_templates",
        icon_id=sid("icon/clipboard"),
        value=True,
    ),
    dict(
        id=sid("flag/mcp"),
        name="mcp",
        description="Enable or disable the use of the MCP server",
        type="mcp",
        icon_id=sid("icon/server"),
        value=True,
    ),
    dict(
        id=sid("flag/scenario-active"),
        name="Active",
        description="Controls whether this scenario is published and available for simulations",
        type="scenario_active",
        icon_id=sid("icon/power"),
        value=True,
    ),
    dict(
        id=sid("flag/field-active"),
        name="field_active",
        description="Controls whether this field is visible and editable in forms",
        type="field_active",
        icon_id=sid("icon/power"),
        value=True,
    ),
    dict(
        id=sid("flag/model-active"),
        name="model_active",
        description="Controls whether this AI model is available for selection by agents",
        type="model_active",
        icon_id=sid("icon/power"),
        value=True,
    ),
    dict(
        id=sid("flag/profile-active"),
        name="profile_active",
        description="Controls whether this user profile is active and can access the system",
        type="profile_active",
        icon_id=sid("icon/power"),
        value=True,
    ),
    dict(
        id=sid("flag/provider-active"),
        name="provider_active",
        description="Controls whether this AI provider is available for use",
        type="provider_active",
        icon_id=sid("icon/power"),
        value=True,
    ),
    dict(
        id=sid("flag/rubric-active"),
        name="rubric_active",
        description="Controls whether this rubric is available for grading simulations",
        type="rubric_active",
        icon_id=sid("icon/power"),
        value=True,
    ),
    dict(
        id=sid("flag/setting-active"),
        name="setting_active",
        description="Controls whether this setting is enabled and applied",
        type="setting_active",
        icon_id=sid("icon/power"),
        value=True,
    ),
    dict(
        id=sid("flag/tool-active"),
        name="tool_active",
        description="Controls whether this tool is available for use by AI agents",
        type="tool_active",
        icon_id=sid("icon/power"),
        value=True,
    ),
    dict(
        id=sid("flag/cohort-active"),
        name="Active",
        description="Controls whether this cohort is active and can run simulations",
        type="cohort_active",
        icon_id=sid("icon/power"),
        value=True,
    ),
    dict(
        id=sid("flag/persona-active"),
        name="Active",
        description="Controls whether this persona is available for use in scenarios",
        type="persona_active",
        icon_id=sid("icon/power"),
        value=True,
    ),
    dict(
        id=sid("flag/simulation-active"),
        name="Active",
        description="Controls whether this simulation is active and can be started",
        type="simulation_active",
        icon_id=sid("icon/power"),
        value=True,
    ),
    dict(
        id=sid("flag/agent-active"),
        name="agent_active",
        description="Controls whether this AI agent is available for use in simulations",
        type="agent_active",
        icon_id=sid("icon/power"),
        value=True,
    ),
    dict(
        id=sid("flag/auth-active"),
        name="auth_active",
        description="Controls whether this authentication method is enabled for login",
        type="auth_active",
        icon_id=sid("icon/power"),
        value=True,
    ),
    dict(
        id=sid("flag/department-active"),
        name="department_active",
        description="Controls whether this department is visible in the organization structure",
        type="department_active",
        icon_id=sid("icon/power"),
        value=True,
    ),
    dict(
        id=sid("flag/document-active"),
        name="document_active",
        description="Controls whether this document is available for reference in scenarios",
        type="document_active",
        icon_id=sid("icon/power"),
        value=True,
    ),
    dict(
        id=sid("flag/eval-active"),
        name="eval_active",
        description="Controls whether this evaluation configuration is active and can be used",
        type="eval_active",
        icon_id=sid("icon/power"),
        value=True,
    ),
    dict(
        id=sid("flag/simulation-rubric"),
        name="simulation_rubric",
        description="Rubric used for simulation grading",
        type="simulation_rubric",
        icon_id=sid("icon/clipboard"),
        value=True,
    ),
    dict(
        id=sid("flag/video-rubric"),
        name="video_rubric",
        description="Rubric used for video grading",
        type="video_rubric",
        icon_id=sid("icon/film"),
        value=True,
    ),
    dict(
        id=sid("flag/infinite-mode"),
        name="Infinite Mode",
        description="Enable infinite mode for unlimited attempts",
        type="infinite_mode",
        icon_id=sid("icon/infinity"),
        value=True,
    ),
    dict(
        id=sid("flag/strengths-enabled"),
        name="Strengths Enabled",
        description="Enable strengths feedback for scenarios",
        type="strengths_enabled",
        icon_id=sid("icon/star"),
        value=True,
    ),
    dict(
        id=sid("flag/use-custom"),
        name="Use Custom",
        description="Allow custom configuration for scenarios",
        type="use_custom",
        icon_id=sid("icon/settings"),
        value=True,
    ),
    dict(
        id=sid("flag/analyses-enabled"),
        name="Analyses Enabled",
        description="Enable analysis feedback for scenarios",
        type="analyses_enabled",
        icon_id=sid("icon/bar-chart"),
        value=True,
    ),
    dict(
        id=sid("flag/use-previous"),
        name="Use Previous",
        description="Use previous attempt context for scenarios",
        type="use_previous",
        icon_id=sid("icon/rewind"),
        value=True,
    ),
    dict(
        id=sid("flag/improvements-enabled"),
        name="Improvements Enabled",
        description="Enable improvements feedback for scenarios",
        type="improvements_enabled",
        icon_id=sid("icon/trending-up"),
        value=True,
    ),
]
