"""Icon resource seeds.

191 rows of Lucide icon references used across the application for
personas, artifacts, and UI elements. Each icon has a name, description, and value.
"""

from database.seeds.ids import sid

icons = [
    dict(
        id=sid("icon/smile-plus"),
        name="SmilePlus",
        description="Persona icon",
        value="SmilePlus",
    ),
    dict(
        id=sid("icon/help-circle"),
        name="HelpCircle",
        description="Persona icon",
        value="HelpCircle",
    ),
    dict(
        id=sid("icon/zap"),
        name="Zap",
        description="Persona icon",
        value="Zap",
    ),
    dict(
        id=sid("icon/cloud"),
        name="Cloud",
        description="Persona icon",
        value="Cloud",
    ),
    dict(
        id=sid("icon/user"),
        name="User",
        description="Persona icon",
        value="User",
    ),
    dict(
        id=sid("icon/graduation-cap"),
        name="GraduationCap",
        description="Persona icon",
        value="GraduationCap",
    ),
    dict(
        id=sid("icon/users"),
        name="Users",
        description="Persona icon",
        value="Users",
    ),
    dict(
        id=sid("icon/award"),
        name="Award",
        description="Award icon",
        value="Award",
    ),
    dict(
        id=sid("icon/book-open"),
        name="BookOpen",
        description="BookOpen icon",
        value="BookOpen",
    ),
    dict(
        id=sid("icon/database"),
        name="Database",
        description="Database icon",
        value="Database",
    ),
    dict(
        id=sid("icon/file-text"),
        name="FileText",
        description="FileText icon",
        value="FileText",
    ),
    dict(
        id=sid("icon/globe"),
        name="Globe",
        description="Globe icon",
        value="Globe",
    ),
    dict(
        id=sid("icon/mail"),
        name="Mail",
        description="Mail icon",
        value="Mail",
    ),
    dict(
        id=sid("icon/mic"),
        name="Mic",
        description="Mic icon",
        value="Mic",
    ),
    dict(
        id=sid("icon/brain"),
        name="Brain",
        description="Brain icon",
        value="Brain",
    ),
    dict(
        id=sid("icon/phone"),
        name="Phone",
        description="Phone icon",
        value="Phone",
    ),
    dict(
        id=sid("icon/search"),
        name="Search",
        description="Search icon",
        value="Search",
    ),
    dict(
        id=sid("icon/settings"),
        name="Settings",
        description="Settings icon",
        value="Settings",
    ),
    dict(
        id=sid("icon/shield"),
        name="Shield",
        description="Shield icon",
        value="Shield",
    ),
    dict(
        id=sid("icon/video"),
        name="Video",
        description="Video icon",
        value="Video",
    ),
    dict(
        id=sid("icon/wifi"),
        name="Wifi",
        description="Wifi icon",
        value="Wifi",
    ),
    dict(
        id=sid("icon/monitor"),
        name="Monitor",
        description="Monitor icon",
        value="Monitor",
    ),
    dict(
        id=sid("icon/sparkles"),
        name="Sparkles",
        description="Sparkles icon",
        value="Sparkles",
    ),
    dict(
        id=sid("icon/heart"),
        name="Heart",
        description="Heart icon",
        value="Heart",
    ),
    dict(
        id=sid("icon/star"),
        name="Star",
        description="Star icon",
        value="Star",
    ),
    dict(
        id=sid("icon/message-square"),
        name="MessageSquare",
        description="MessageSquare icon",
        value="MessageSquare",
    ),
    dict(
        id=sid("icon/lightbulb"),
        name="Lightbulb",
        description="Lightbulb icon",
        value="Lightbulb",
    ),
    dict(
        id=sid("icon/target"),
        name="Target",
        description="Target icon",
        value="Target",
    ),
    dict(
        id=sid("icon/info"),
        name="Info",
        description="Info icon",
        value="Info",
    ),
    dict(
        id=sid("icon/briefcase"),
        name="Briefcase",
        description="Briefcase icon",
        value="Briefcase",
    ),
    dict(
        id=sid("icon/building"),
        name="Building",
        description="Building icon",
        value="Building",
    ),
    dict(
        id=sid("icon/computer"),
        name="Computer",
        description="Computer icon",
        value="Computer",
    ),
    dict(
        id=sid("icon/laptop"),
        name="Laptop",
        description="Laptop icon",
        value="Laptop",
    ),
    dict(
        id=sid("icon/smartphone"),
        name="Smartphone",
        description="Smartphone icon",
        value="Smartphone",
    ),
    dict(
        id=sid("icon/tablet"),
        name="Tablet",
        description="Tablet icon",
        value="Tablet",
    ),
    dict(
        id=sid("icon/printer"),
        name="Printer",
        description="Printer icon",
        value="Printer",
    ),
    dict(
        id=sid("icon/file"),
        name="File",
        description="File icon",
        value="File",
    ),
    dict(
        id=sid("icon/folder"),
        name="Folder",
        description="Folder icon",
        value="Folder",
    ),
    dict(
        id=sid("icon/archive"),
        name="Archive",
        description="Archive icon",
        value="Archive",
    ),
    dict(
        id=sid("icon/clipboard"),
        name="Clipboard",
        description="Clipboard icon",
        value="Clipboard",
    ),
    dict(
        id=sid("icon/pen-tool"),
        name="PenTool",
        description="PenTool icon",
        value="PenTool",
    ),
    dict(
        id=sid("icon/edit"),
        name="Edit",
        description="Edit icon",
        value="Edit",
    ),
    dict(
        id=sid("icon/edit2"),
        name="Edit2",
        description="Edit2 icon",
        value="Edit2",
    ),
    dict(
        id=sid("icon/edit3"),
        name="Edit3",
        description="Edit3 icon",
        value="Edit3",
    ),
    dict(
        id=sid("icon/save"),
        name="Save",
        description="Save icon",
        value="Save",
    ),
    dict(
        id=sid("icon/download"),
        name="Download",
        description="Download icon",
        value="Download",
    ),
    dict(
        id=sid("icon/upload"),
        name="Upload",
        description="Upload icon",
        value="Upload",
    ),
    dict(
        id=sid("icon/activity"),
        name="Activity",
        description="Activity icon",
        value="Activity",
    ),
    dict(
        id=sid("icon/play"),
        name="Play",
        description="Play icon",
        value="Play",
    ),
    dict(
        id=sid("icon/pause"),
        name="Pause",
        description="Pause icon",
        value="Pause",
    ),
    dict(
        id=sid("icon/skip-back"),
        name="SkipBack",
        description="SkipBack icon",
        value="SkipBack",
    ),
    dict(
        id=sid("icon/skip-forward"),
        name="SkipForward",
        description="SkipForward icon",
        value="SkipForward",
    ),
    dict(
        id=sid("icon/rewind"),
        name="Rewind",
        description="Rewind icon",
        value="Rewind",
    ),
    dict(
        id=sid("icon/fast-forward"),
        name="FastForward",
        description="FastForward icon",
        value="FastForward",
    ),
    dict(
        id=sid("icon/timer"),
        name="Timer",
        description="Timer icon",
        value="Timer",
    ),
    dict(
        id=sid("icon/clock"),
        name="Clock",
        description="Clock icon",
        value="Clock",
    ),
    dict(
        id=sid("icon/calendar"),
        name="Calendar",
        description="Calendar icon",
        value="Calendar",
    ),
    dict(
        id=sid("icon/map-pin"),
        name="MapPin",
        description="MapPin icon",
        value="MapPin",
    ),
    dict(
        id=sid("icon/navigation"),
        name="Navigation",
        description="Navigation icon",
        value="Navigation",
    ),
    dict(
        id=sid("icon/compass"),
        name="Compass",
        description="Compass icon",
        value="Compass",
    ),
    dict(
        id=sid("icon/flag"),
        name="Flag",
        description="Flag icon",
        value="Flag",
    ),
    dict(
        id=sid("icon/trophy"),
        name="Trophy",
        description="Trophy icon",
        value="Trophy",
    ),
    dict(
        id=sid("icon/medal"),
        name="Medal",
        description="Medal icon",
        value="Medal",
    ),
    dict(
        id=sid("icon/gift"),
        name="Gift",
        description="Gift icon",
        value="Gift",
    ),
    dict(
        id=sid("icon/wrench"),
        name="Wrench",
        description="Wrench icon",
        value="Wrench",
    ),
    dict(
        id=sid("icon/cog"),
        name="Cog",
        description="Cog icon",
        value="Cog",
    ),
    dict(
        id=sid("icon/server"),
        name="Server",
        description="Server icon",
        value="Server",
    ),
    dict(
        id=sid("icon/network"),
        name="Network",
        description="Network icon",
        value="Network",
    ),
    dict(
        id=sid("icon/wifi-off"),
        name="WifiOff",
        description="WifiOff icon",
        value="WifiOff",
    ),
    dict(
        id=sid("icon/bluetooth"),
        name="Bluetooth",
        description="Bluetooth icon",
        value="Bluetooth",
    ),
    dict(
        id=sid("icon/battery"),
        name="Battery",
        description="Battery icon",
        value="Battery",
    ),
    dict(
        id=sid("icon/power"),
        name="Power",
        description="Power icon",
        value="Power",
    ),
    dict(
        id=sid("icon/lock"),
        name="Lock",
        description="Lock icon",
        value="Lock",
    ),
    dict(
        id=sid("icon/unlock"),
        name="Unlock",
        description="Unlock icon",
        value="Unlock",
    ),
    dict(
        id=sid("icon/shield-off"),
        name="ShieldOff",
        description="ShieldOff icon",
        value="ShieldOff",
    ),
    dict(
        id=sid("icon/key"),
        name="Key",
        description="Key icon",
        value="Key",
    ),
    dict(
        id=sid("icon/link"),
        name="Link",
        description="Link icon",
        value="Link",
    ),
    dict(
        id=sid("icon/link2"),
        name="Link2",
        description="Link2 icon",
        value="Link2",
    ),
    dict(
        id=sid("icon/palette"),
        name="Palette",
        description="Palette icon",
        value="Palette",
    ),
    dict(
        id=sid("icon/brush"),
        name="Brush",
        description="Brush icon",
        value="Brush",
    ),
    dict(
        id=sid("icon/camera"),
        name="Camera",
        description="Camera icon",
        value="Camera",
    ),
    dict(
        id=sid("icon/music"),
        name="Music",
        description="Music icon",
        value="Music",
    ),
    dict(
        id=sid("icon/guitar"),
        name="Guitar",
        description="Guitar icon",
        value="Guitar",
    ),
    dict(
        id=sid("icon/piano"),
        name="Piano",
        description="Piano icon",
        value="Piano",
    ),
    dict(
        id=sid("icon/film"),
        name="Film",
        description="Film icon",
        value="Film",
    ),
    dict(
        id=sid("icon/image"),
        name="Image",
        description="Image icon",
        value="Image",
    ),
    dict(
        id=sid("icon/paintbrush"),
        name="Paintbrush",
        description="Paintbrush icon",
        value="Paintbrush",
    ),
    dict(
        id=sid("icon/scissors"),
        name="Scissors",
        description="Scissors icon",
        value="Scissors",
    ),
    dict(
        id=sid("icon/copy"),
        name="Copy",
        description="Copy icon",
        value="Copy",
    ),
    dict(
        id=sid("icon/layers"),
        name="Layers",
        description="Layers icon",
        value="Layers",
    ),
    dict(
        id=sid("icon/grid"),
        name="Grid",
        description="Grid icon",
        value="Grid",
    ),
    dict(
        id=sid("icon/layout"),
        name="Layout",
        description="Layout icon",
        value="Layout",
    ),
    dict(
        id=sid("icon/columns"),
        name="Columns",
        description="Columns icon",
        value="Columns",
    ),
    dict(
        id=sid("icon/rows"),
        name="Rows",
        description="Rows icon",
        value="Rows",
    ),
    dict(
        id=sid("icon/leaf"),
        name="Leaf",
        description="Leaf icon",
        value="Leaf",
    ),
    dict(
        id=sid("icon/flower"),
        name="Flower",
        description="Flower icon",
        value="Flower",
    ),
    dict(
        id=sid("icon/mountain"),
        name="Mountain",
        description="Mountain icon",
        value="Mountain",
    ),
    dict(
        id=sid("icon/waves"),
        name="Waves",
        description="Waves icon",
        value="Waves",
    ),
    dict(
        id=sid("icon/fish"),
        name="Fish",
        description="Fish icon",
        value="Fish",
    ),
    dict(
        id=sid("icon/bird"),
        name="Bird",
        description="Bird icon",
        value="Bird",
    ),
    dict(
        id=sid("icon/cat"),
        name="Cat",
        description="Cat icon",
        value="Cat",
    ),
    dict(
        id=sid("icon/dog"),
        name="Dog",
        description="Dog icon",
        value="Dog",
    ),
    dict(
        id=sid("icon/paw-print"),
        name="PawPrint",
        description="PawPrint icon",
        value="PawPrint",
    ),
    dict(
        id=sid("icon/bug"),
        name="Bug",
        description="Bug icon",
        value="Bug",
    ),
    dict(
        id=sid("icon/rainbow"),
        name="Rainbow",
        description="Rainbow icon",
        value="Rainbow",
    ),
    dict(
        id=sid("icon/dollar-sign"),
        name="DollarSign",
        description="DollarSign icon",
        value="DollarSign",
    ),
    dict(
        id=sid("icon/credit-card"),
        name="CreditCard",
        description="CreditCard icon",
        value="CreditCard",
    ),
    dict(
        id=sid("icon/wallet"),
        name="Wallet",
        description="Wallet icon",
        value="Wallet",
    ),
    dict(
        id=sid("icon/piggy-bank"),
        name="PiggyBank",
        description="PiggyBank icon",
        value="PiggyBank",
    ),
    dict(
        id=sid("icon/trending-up"),
        name="TrendingUp",
        description="TrendingUp icon",
        value="TrendingUp",
    ),
    dict(
        id=sid("icon/trending-down"),
        name="TrendingDown",
        description="TrendingDown icon",
        value="TrendingDown",
    ),
    dict(
        id=sid("icon/bar-chart"),
        name="BarChart",
        description="BarChart icon",
        value="BarChart",
    ),
    dict(
        id=sid("icon/pie-chart"),
        name="PieChart",
        description="PieChart icon",
        value="PieChart",
    ),
    dict(
        id=sid("icon/calculator"),
        name="Calculator",
        description="Calculator icon",
        value="Calculator",
    ),
    dict(
        id=sid("icon/percent"),
        name="Percent",
        description="Percent icon",
        value="Percent",
    ),
    dict(
        id=sid("icon/hash"),
        name="Hash",
        description="Hash icon",
        value="Hash",
    ),
    dict(
        id=sid("icon/at-sign"),
        name="AtSign",
        description="AtSign icon",
        value="AtSign",
    ),
    dict(
        id=sid("icon/plus"),
        name="Plus",
        description="Plus icon",
        value="Plus",
    ),
    dict(
        id=sid("icon/frown"),
        name="Frown",
        description="Frown icon",
        value="Frown",
    ),
    dict(
        id=sid("icon/equal"),
        name="Equal",
        description="Equal icon",
        value="Equal",
    ),
    dict(
        id=sid("icon/infinity"),
        name="Infinity",
        description="Infinity icon",
        value="Infinity",
    ),
    dict(
        id=sid("icon/heart-pulse"),
        name="HeartPulse",
        description="HeartPulse icon",
        value="HeartPulse",
    ),
    dict(
        id=sid("icon/dumbbell"),
        name="Dumbbell",
        description="Dumbbell icon",
        value="Dumbbell",
    ),
    dict(
        id=sid("icon/bike"),
        name="Bike",
        description="Bike icon",
        value="Bike",
    ),
    dict(
        id=sid("icon/car"),
        name="Car",
        description="Car icon",
        value="Car",
    ),
    dict(
        id=sid("icon/bus"),
        name="Bus",
        description="Bus icon",
        value="Bus",
    ),
    dict(
        id=sid("icon/train"),
        name="Train",
        description="Train icon",
        value="Train",
    ),
    dict(
        id=sid("icon/plane"),
        name="Plane",
        description="Plane icon",
        value="Plane",
    ),
    dict(
        id=sid("icon/ship"),
        name="Ship",
        description="Ship icon",
        value="Ship",
    ),
    dict(
        id=sid("icon/rocket"),
        name="Rocket",
        description="Rocket icon",
        value="Rocket",
    ),
    dict(
        id=sid("icon/satellite"),
        name="Satellite",
        description="Satellite icon",
        value="Satellite",
    ),
    dict(
        id=sid("icon/telescope"),
        name="Telescope",
        description="Telescope icon",
        value="Telescope",
    ),
    dict(
        id=sid("icon/microscope"),
        name="Microscope",
        description="Microscope icon",
        value="Microscope",
    ),
    dict(
        id=sid("icon/stethoscope"),
        name="Stethoscope",
        description="Stethoscope icon",
        value="Stethoscope",
    ),
    dict(
        id=sid("icon/pill"),
        name="Pill",
        description="Pill icon",
        value="Pill",
    ),
    dict(
        id=sid("icon/cross"),
        name="Cross",
        description="Cross icon",
        value="Cross",
    ),
    dict(
        id=sid("icon/hourglass"),
        name="Hourglass",
        description="Hourglass icon",
        value="Hourglass",
    ),
    dict(
        id=sid("icon/watch"),
        name="Watch",
        description="Watch icon",
        value="Watch",
    ),
    dict(
        id=sid("icon/alarm-clock"),
        name="AlarmClock",
        description="AlarmClock icon",
        value="AlarmClock",
    ),
    dict(
        id=sid("icon/bell"),
        name="Bell",
        description="Bell icon",
        value="Bell",
    ),
    dict(
        id=sid("icon/check"),
        name="Check",
        description="Check icon",
        value="Check",
    ),
    dict(
        id=sid("icon/x"),
        name="X",
        description="X icon",
        value="X",
    ),
    dict(
        id=sid("icon/arrow-up"),
        name="ArrowUp",
        description="ArrowUp icon",
        value="ArrowUp",
    ),
    dict(
        id=sid("icon/arrow-down"),
        name="ArrowDown",
        description="ArrowDown icon",
        value="ArrowDown",
    ),
    dict(
        id=sid("icon/arrow-left"),
        name="ArrowLeft",
        description="ArrowLeft icon",
        value="ArrowLeft",
    ),
    dict(
        id=sid("icon/arrow-right"),
        name="ArrowRight",
        description="ArrowRight icon",
        value="ArrowRight",
    ),
    dict(
        id=sid("icon/chevron-up"),
        name="ChevronUp",
        description="ChevronUp icon",
        value="ChevronUp",
    ),
    dict(
        id=sid("icon/chevron-down"),
        name="ChevronDown",
        description="ChevronDown icon",
        value="ChevronDown",
    ),
    dict(
        id=sid("icon/home"),
        name="Home",
        description="Home icon",
        value="Home",
    ),
    dict(
        id=sid("icon/store"),
        name="Store",
        description="Store icon",
        value="Store",
    ),
    dict(
        id=sid("icon/package"),
        name="Package",
        description="Package icon",
        value="Package",
    ),
    dict(
        id=sid("icon/box"),
        name="Box",
        description="Box icon",
        value="Box",
    ),
    dict(
        id=sid("icon/circle"),
        name="Circle",
        description="Circle icon",
        value="Circle",
    ),
    dict(
        id=sid("icon/square"),
        name="Square",
        description="Square icon",
        value="Square",
    ),
    dict(
        id=sid("icon/triangle"),
        name="Triangle",
        description="Triangle icon",
        value="Triangle",
    ),
    dict(
        id=sid("icon/hexagon"),
        name="Hexagon",
        description="Hexagon icon",
        value="Hexagon",
    ),
    dict(
        id=sid("icon/diamond"),
        name="Diamond",
        description="Diamond icon",
        value="Diamond",
    ),
    dict(
        id=sid("icon/spade"),
        name="Spade",
        description="Spade icon",
        value="Spade",
    ),
    dict(
        id=sid("icon/club"),
        name="Club",
        description="Club icon",
        value="Club",
    ),
    dict(
        id=sid("icon/dice1"),
        name="Dice1",
        description="Dice1 icon",
        value="Dice1",
    ),
    dict(
        id=sid("icon/gamepad"),
        name="Gamepad",
        description="Gamepad icon",
        value="Gamepad",
    ),
    dict(
        id=sid("icon/puzzle"),
        name="Puzzle",
        description="Puzzle icon",
        value="Puzzle",
    ),
    dict(
        id=sid("icon/minus"),
        name="Minus",
        description="Minus icon",
        value="Minus",
    ),
    dict(
        id=sid("icon/angry"),
        name="Angry",
        description="Angry icon",
        value="Angry",
    ),
    dict(
        id=sid("icon/heart-crack"),
        name="HeartCrack",
        description="HeartCrack icon",
        value="HeartCrack",
    ),
    dict(
        id=sid("icon/crown"),
        name="Crown",
        description="Crown icon",
        value="Crown",
    ),
    dict(
        id=sid("icon/flame"),
        name="Flame",
        description="Flame icon",
        value="Flame",
    ),
    dict(
        id=sid("icon/sun"),
        name="Sun",
        description="Sun icon",
        value="Sun",
    ),
    dict(
        id=sid("icon/moon"),
        name="Moon",
        description="Moon icon",
        value="Moon",
    ),
    dict(
        id=sid("icon/droplet"),
        name="Droplet",
        description="Droplet icon",
        value="Droplet",
    ),
    dict(
        id=sid("icon/message-circle"),
        name="MessageCircle",
        description="MessageCircle icon",
        value="MessageCircle",
    ),
    dict(
        id=sid("icon/user-plus"),
        name="UserPlus",
        description="UserPlus icon",
        value="UserPlus",
    ),
    dict(
        id=sid("icon/user-minus"),
        name="UserMinus",
        description="UserMinus icon",
        value="UserMinus",
    ),
    dict(
        id=sid("icon/user-check"),
        name="UserCheck",
        description="UserCheck icon",
        value="UserCheck",
    ),
    dict(
        id=sid("icon/user-x"),
        name="UserX",
        description="UserX icon",
        value="UserX",
    ),
    dict(
        id=sid("icon/speech"),
        name="Speech",
        description="Speech icon",
        value="Speech",
    ),
    dict(
        id=sid("icon/mic-off"),
        name="MicOff",
        description="MicOff icon",
        value="MicOff",
    ),
    dict(
        id=sid("icon/volume"),
        name="Volume",
        description="Volume icon",
        value="Volume",
    ),
    dict(
        id=sid("icon/volume1"),
        name="Volume1",
        description="Volume1 icon",
        value="Volume1",
    ),
    dict(
        id=sid("icon/volume2"),
        name="Volume2",
        description="Volume2 icon",
        value="Volume2",
    ),
    dict(
        id=sid("icon/volume-x"),
        name="VolumeX",
        description="VolumeX icon",
        value="VolumeX",
    ),
    dict(
        id=sid("icon/headphones"),
        name="Headphones",
        description="Headphones icon",
        value="Headphones",
    ),
    dict(
        id=sid("icon/speaker"),
        name="Speaker",
        description="Speaker icon",
        value="Speaker",
    ),
    dict(
        id=sid("icon/book"),
        name="Book",
        description="Book icon",
        value="Book",
    ),
    dict(
        id=sid("icon/school"),
        name="School",
        description="School icon",
        value="School",
    ),
    dict(
        id=sid("icon/eye"),
        name="Eye",
        description="Eye icon",
        value="Eye",
    ),
    dict(
        id=sid("icon/eye-off"),
        name="EyeOff",
        description="EyeOff icon",
        value="EyeOff",
    ),
    dict(
        id=sid("icon/check-circle"),
        name="CheckCircle",
        description="CheckCircle icon",
        value="CheckCircle",
    ),
    dict(
        id=sid("icon/x-circle"),
        name="XCircle",
        description="XCircle icon",
        value="XCircle",
    ),
    dict(
        id=sid("icon/alert-circle"),
        name="AlertCircle",
        description="AlertCircle icon",
        value="AlertCircle",
    ),
]
