"""Icon resource seeds — loads inline SVG from database/seeds/icons/.

190 Lucide icon SVGs used across the application for personas, artifacts,
and UI elements. Each icon has a name, description, and inline SVG value.
"""

from pathlib import Path

from database.seeds.ids import sid

ICONS_DIR = Path(__file__).parent.parent / "icons"


def _load_svg(slug: str) -> str:
    """Read an SVG file by slug, e.g. 'smile-plus' → icons/smile-plus.svg."""
    return (ICONS_DIR / f"{slug}.svg").read_text(encoding="utf-8").strip()


# (slug, human name, description)
_ICON_DEFS = [
    ("smile-plus", "SmilePlus", "Persona icon"),
    ("help-circle", "HelpCircle", "Persona icon"),
    ("zap", "Zap", "Persona icon"),
    ("cloud", "Cloud", "Persona icon"),
    ("user", "User", "Persona icon"),
    ("graduation-cap", "GraduationCap", "Persona icon"),
    ("users", "Users", "Persona icon"),
    ("award", "Award", "Award icon"),
    ("book-open", "BookOpen", "BookOpen icon"),
    ("database", "Database", "Database icon"),
    ("file-text", "FileText", "FileText icon"),
    ("globe", "Globe", "Globe icon"),
    ("mail", "Mail", "Mail icon"),
    ("mic", "Mic", "Mic icon"),
    ("brain", "Brain", "Brain icon"),
    ("phone", "Phone", "Phone icon"),
    ("search", "Search", "Search icon"),
    ("settings", "Settings", "Settings icon"),
    ("shield", "Shield", "Shield icon"),
    ("video", "Video", "Video icon"),
    ("wifi", "Wifi", "Wifi icon"),
    ("monitor", "Monitor", "Monitor icon"),
    ("sparkles", "Sparkles", "Sparkles icon"),
    ("heart", "Heart", "Heart icon"),
    ("star", "Star", "Star icon"),
    ("message-square", "MessageSquare", "MessageSquare icon"),
    ("lightbulb", "Lightbulb", "Lightbulb icon"),
    ("target", "Target", "Target icon"),
    ("info", "Info", "Info icon"),
    ("briefcase", "Briefcase", "Briefcase icon"),
    ("building", "Building", "Building icon"),
    ("computer", "Computer", "Computer icon"),
    ("laptop", "Laptop", "Laptop icon"),
    ("smartphone", "Smartphone", "Smartphone icon"),
    ("tablet", "Tablet", "Tablet icon"),
    ("printer", "Printer", "Printer icon"),
    ("file", "File", "File icon"),
    ("folder", "Folder", "Folder icon"),
    ("archive", "Archive", "Archive icon"),
    ("clipboard", "Clipboard", "Clipboard icon"),
    ("pen-tool", "PenTool", "PenTool icon"),
    ("edit", "Edit", "Edit icon"),
    ("edit2", "Edit2", "Edit2 icon"),
    ("edit3", "Edit3", "Edit3 icon"),
    ("save", "Save", "Save icon"),
    ("download", "Download", "Download icon"),
    ("upload", "Upload", "Upload icon"),
    ("activity", "Activity", "Activity icon"),
    ("play", "Play", "Play icon"),
    ("pause", "Pause", "Pause icon"),
    ("skip-back", "SkipBack", "SkipBack icon"),
    ("skip-forward", "SkipForward", "SkipForward icon"),
    ("rewind", "Rewind", "Rewind icon"),
    ("fast-forward", "FastForward", "FastForward icon"),
    ("timer", "Timer", "Timer icon"),
    ("clock", "Clock", "Clock icon"),
    ("calendar", "Calendar", "Calendar icon"),
    ("map-pin", "MapPin", "MapPin icon"),
    ("navigation", "Navigation", "Navigation icon"),
    ("compass", "Compass", "Compass icon"),
    ("flag", "Flag", "Flag icon"),
    ("trophy", "Trophy", "Trophy icon"),
    ("medal", "Medal", "Medal icon"),
    ("gift", "Gift", "Gift icon"),
    ("wrench", "Wrench", "Wrench icon"),
    ("cog", "Cog", "Cog icon"),
    ("server", "Server", "Server icon"),
    ("network", "Network", "Network icon"),
    ("wifi-off", "WifiOff", "WifiOff icon"),
    ("bluetooth", "Bluetooth", "Bluetooth icon"),
    ("battery", "Battery", "Battery icon"),
    ("power", "Power", "Power icon"),
    ("lock", "Lock", "Lock icon"),
    ("unlock", "Unlock", "Unlock icon"),
    ("shield-off", "ShieldOff", "ShieldOff icon"),
    ("key", "Key", "Key icon"),
    ("link", "Link", "Link icon"),
    ("link2", "Link2", "Link2 icon"),
    ("palette", "Palette", "Palette icon"),
    ("brush", "Brush", "Brush icon"),
    ("camera", "Camera", "Camera icon"),
    ("music", "Music", "Music icon"),
    ("guitar", "Guitar", "Guitar icon"),
    ("piano", "Piano", "Piano icon"),
    ("film", "Film", "Film icon"),
    ("image", "Image", "Image icon"),
    ("paintbrush", "Paintbrush", "Paintbrush icon"),
    ("scissors", "Scissors", "Scissors icon"),
    ("copy", "Copy", "Copy icon"),
    ("layers", "Layers", "Layers icon"),
    ("grid", "Grid", "Grid icon"),
    ("layout", "Layout", "Layout icon"),
    ("columns", "Columns", "Columns icon"),
    ("rows", "Rows", "Rows icon"),
    ("leaf", "Leaf", "Leaf icon"),
    ("flower", "Flower", "Flower icon"),
    ("mountain", "Mountain", "Mountain icon"),
    ("waves", "Waves", "Waves icon"),
    ("fish", "Fish", "Fish icon"),
    ("bird", "Bird", "Bird icon"),
    ("cat", "Cat", "Cat icon"),
    ("dog", "Dog", "Dog icon"),
    ("paw-print", "PawPrint", "PawPrint icon"),
    ("bug", "Bug", "Bug icon"),
    ("rainbow", "Rainbow", "Rainbow icon"),
    ("dollar-sign", "DollarSign", "DollarSign icon"),
    ("credit-card", "CreditCard", "CreditCard icon"),
    ("wallet", "Wallet", "Wallet icon"),
    ("piggy-bank", "PiggyBank", "PiggyBank icon"),
    ("trending-up", "TrendingUp", "TrendingUp icon"),
    ("trending-down", "TrendingDown", "TrendingDown icon"),
    ("bar-chart", "BarChart", "BarChart icon"),
    ("pie-chart", "PieChart", "PieChart icon"),
    ("calculator", "Calculator", "Calculator icon"),
    ("percent", "Percent", "Percent icon"),
    ("hash", "Hash", "Hash icon"),
    ("at-sign", "AtSign", "AtSign icon"),
    ("plus", "Plus", "Plus icon"),
    ("frown", "Frown", "Frown icon"),
    ("equal", "Equal", "Equal icon"),
    ("infinity", "Infinity", "Infinity icon"),
    ("heart-pulse", "HeartPulse", "HeartPulse icon"),
    ("dumbbell", "Dumbbell", "Dumbbell icon"),
    ("bike", "Bike", "Bike icon"),
    ("car", "Car", "Car icon"),
    ("bus", "Bus", "Bus icon"),
    ("train", "Train", "Train icon"),
    ("plane", "Plane", "Plane icon"),
    ("ship", "Ship", "Ship icon"),
    ("rocket", "Rocket", "Rocket icon"),
    ("satellite", "Satellite", "Satellite icon"),
    ("telescope", "Telescope", "Telescope icon"),
    ("microscope", "Microscope", "Microscope icon"),
    ("stethoscope", "Stethoscope", "Stethoscope icon"),
    ("pill", "Pill", "Pill icon"),
    ("cross", "Cross", "Cross icon"),
    ("hourglass", "Hourglass", "Hourglass icon"),
    ("watch", "Watch", "Watch icon"),
    ("alarm-clock", "AlarmClock", "AlarmClock icon"),
    ("bell", "Bell", "Bell icon"),
    ("check", "Check", "Check icon"),
    ("x", "X", "X icon"),
    ("arrow-up", "ArrowUp", "ArrowUp icon"),
    ("arrow-down", "ArrowDown", "ArrowDown icon"),
    ("arrow-left", "ArrowLeft", "ArrowLeft icon"),
    ("arrow-right", "ArrowRight", "ArrowRight icon"),
    ("chevron-up", "ChevronUp", "ChevronUp icon"),
    ("chevron-down", "ChevronDown", "ChevronDown icon"),
    ("home", "Home", "Home icon"),
    ("store", "Store", "Store icon"),
    ("package", "Package", "Package icon"),
    ("box", "Box", "Box icon"),
    ("circle", "Circle", "Circle icon"),
    ("square", "Square", "Square icon"),
    ("triangle", "Triangle", "Triangle icon"),
    ("hexagon", "Hexagon", "Hexagon icon"),
    ("diamond", "Diamond", "Diamond icon"),
    ("spade", "Spade", "Spade icon"),
    ("club", "Club", "Club icon"),
    ("dice1", "Dice1", "Dice1 icon"),
    ("gamepad", "Gamepad", "Gamepad icon"),
    ("puzzle", "Puzzle", "Puzzle icon"),
    ("minus", "Minus", "Minus icon"),
    ("angry", "Angry", "Angry icon"),
    ("heart-crack", "HeartCrack", "HeartCrack icon"),
    ("crown", "Crown", "Crown icon"),
    ("flame", "Flame", "Flame icon"),
    ("sun", "Sun", "Sun icon"),
    ("moon", "Moon", "Moon icon"),
    ("droplet", "Droplet", "Droplet icon"),
    ("message-circle", "MessageCircle", "MessageCircle icon"),
    ("user-plus", "UserPlus", "UserPlus icon"),
    ("user-minus", "UserMinus", "UserMinus icon"),
    ("user-check", "UserCheck", "UserCheck icon"),
    ("user-x", "UserX", "UserX icon"),
    ("speech", "Speech", "Speech icon"),
    ("mic-off", "MicOff", "MicOff icon"),
    ("volume", "Volume", "Volume icon"),
    ("volume1", "Volume1", "Volume1 icon"),
    ("volume2", "Volume2", "Volume2 icon"),
    ("volume-x", "VolumeX", "VolumeX icon"),
    ("headphones", "Headphones", "Headphones icon"),
    ("speaker", "Speaker", "Speaker icon"),
    ("book", "Book", "Book icon"),
    ("school", "School", "School icon"),
    ("eye", "Eye", "Eye icon"),
    ("eye-off", "EyeOff", "EyeOff icon"),
    ("check-circle", "CheckCircle", "CheckCircle icon"),
    ("x-circle", "XCircle", "XCircle icon"),
    ("alert-circle", "AlertCircle", "AlertCircle icon"),
]

icons = [
    dict(
        id=sid(f"icon/{slug}"),
        name=name,
        description=desc,
        value=_load_svg(slug),
    )
    for slug, name, desc in _ICON_DEFS
]
