"""Standard resource seeds.

25 standards (5 levels per standard group): Excellent, Good, Acceptable, Marginal, Poor.
"""

from database.seeds.ids import sid

standards = [
    # ── Active Listening ──────────────────────────────────────────────────
    dict(
        id=sid("standard/active-listening/excellent"),
        name="Excellent",
        description="Consistently employs open-ended questions that empower students to discover solutions independently.",
        points=5,
        standard_group_id=sid("standard-group/active-listening"),
    ),
    dict(
        id=sid("standard/active-listening/good"),
        name="Good",
        description="Regularly uses guided questioning, encouraging student reasoning with occasional prompts.",
        points=4,
        standard_group_id=sid("standard-group/active-listening"),
    ),
    dict(
        id=sid("standard/active-listening/acceptable"),
        name="Acceptable",
        description="Occasionally guides students with questions but sometimes provides direct answers.",
        points=3,
        standard_group_id=sid("standard-group/active-listening"),
    ),
    dict(
        id=sid("standard/active-listening/marginal"),
        name="Marginal",
        description="Rarely uses questioning techniques, often resorting to hints or partial solutions.",
        points=2,
        standard_group_id=sid("standard-group/active-listening"),
    ),
    dict(
        id=sid("standard/active-listening/poor"),
        name="Poor",
        description="Directly provided the answer.",
        points=1,
        standard_group_id=sid("standard-group/active-listening"),
    ),
    # ── Time Management ───────────────────────────────────────────────────
    dict(
        id=sid("standard/time-management/excellent"),
        name="Excellent",
        description="Begins and concludes sessions within scheduled times, maximizing productivity and respecting student availability.",
        points=5,
        standard_group_id=sid("standard-group/time-management"),
    ),
    dict(
        id=sid("standard/time-management/good"),
        name="Good",
        description="Generally adheres to time allocations with minor deviations that do not impact session quality.",
        points=4,
        standard_group_id=sid("standard-group/time-management"),
    ),
    dict(
        id=sid("standard/time-management/acceptable"),
        name="Acceptable",
        description="Sometimes exceeds or finishes early, slightly affecting pacing yet maintaining core engagement.",
        points=3,
        standard_group_id=sid("standard-group/time-management"),
    ),
    dict(
        id=sid("standard/time-management/marginal"),
        name="Marginal",
        description="Frequently mismanages time, leading to rushed explanations or unnecessary prolongation.",
        points=2,
        standard_group_id=sid("standard-group/time-management"),
    ),
    dict(
        id=sid("standard/time-management/poor"),
        name="Poor",
        description="Ended the conversation really early, or made it last longer than needed.",
        points=1,
        standard_group_id=sid("standard-group/time-management"),
    ),
    # ── Adaptability ──────────────────────────────────────────────────────
    dict(
        id=sid("standard/adaptability/excellent"),
        name="Excellent",
        description="Perfectly adapts approach to diverse student emotional and attitude types.",
        points=5,
        standard_group_id=sid("standard-group/adaptability"),
    ),
    dict(
        id=sid("standard/adaptability/good"),
        name="Good",
        description="Mostly seamlessly adjusted communication and teaching style to effectively engage students across a wide range of emotions.",
        points=4,
        standard_group_id=sid("standard-group/adaptability"),
    ),
    dict(
        id=sid("standard/adaptability/acceptable"),
        name="Acceptable",
        description="Demonstrates thoughtful adjustments to support most student types, maintaining a supportive and responsive demeanor.",
        points=3,
        standard_group_id=sid("standard-group/adaptability"),
    ),
    dict(
        id=sid("standard/adaptability/marginal"),
        name="Marginal",
        description="Shows minimal ability to adjust to varied student behaviors, occasionally missing cues or responding inappropriately.",
        points=2,
        standard_group_id=sid("standard-group/adaptability"),
    ),
    dict(
        id=sid("standard/adaptability/poor"),
        name="Poor",
        description="Fails to adapt to different student types, responding uniformly without consideration of individual emotional or behavioral needs.",
        points=1,
        standard_group_id=sid("standard-group/adaptability"),
    ),
    # ── Communication ─────────────────────────────────────────────────────
    dict(
        id=sid("standard/communication/excellent"),
        name="Excellent",
        description="Consistently communicates with clarity and professionalism. Follows up when needed and maintains respectful boundaries in all interactions.",
        points=5,
        standard_group_id=sid("standard-group/communication"),
    ),
    dict(
        id=sid("standard/communication/good"),
        name="Good",
        description="Communicates respectfully and clearly with minor lapses in tone or timing. Upholds professional standards.",
        points=4,
        standard_group_id=sid("standard-group/communication"),
    ),
    dict(
        id=sid("standard/communication/acceptable"),
        name="Acceptable",
        description="Communication is mostly appropriate but may occasionally be abrupt, or overly casual.",
        points=3,
        standard_group_id=sid("standard-group/communication"),
    ),
    dict(
        id=sid("standard/communication/marginal"),
        name="Marginal",
        description="Shows limited awareness of tone or affect. May interrupt, dismiss student concerns, or respond in ways that feel cold or reactive.",
        points=2,
        standard_group_id=sid("standard-group/communication"),
    ),
    dict(
        id=sid("standard/communication/poor"),
        name="Poor",
        description="Demonstrates inappropriate or unprofessional behavior (e.g., sarcastic tone, dismissive responses, or failure to maintain respectful interaction).",
        points=1,
        standard_group_id=sid("standard-group/communication"),
    ),
    # ── Content Mastery ───────────────────────────────────────────────────
    dict(
        id=sid("standard/content-mastery/excellent"),
        name="Excellent",
        description="States core concepts clearly; explains in clear, bite-sized steps; uses analogies/visuals to clarify when needed; consistently checks understanding.",
        points=5,
        standard_group_id=sid("standard-group/content-mastery"),
    ),
    dict(
        id=sid("standard/content-mastery/good"),
        name="Good",
        description="Explains core concepts accurately and relates examples to key learning outcomes. Generally provides step-by-step reasoning and occasionally checks for student comprehension.",
        points=4,
        standard_group_id=sid("standard-group/content-mastery"),
    ),
    dict(
        id=sid("standard/content-mastery/acceptable"),
        name="Acceptable",
        description="Provides a basic overview of concepts but with occasional inaccuracies or lack of depth. Some explanations may feel rushed or cognitively dense.",
        points=3,
        standard_group_id=sid("standard-group/content-mastery"),
    ),
    dict(
        id=sid("standard/content-mastery/marginal"),
        name="Marginal",
        description="Demonstrates limited awareness of core concepts and offers explanations with minor errors. Explanations frequently rushed, dense, or skip logical steps; seldom checks comprehension.",
        points=2,
        standard_group_id=sid("standard-group/content-mastery"),
    ),
    dict(
        id=sid("standard/content-mastery/poor"),
        name="Poor",
        description="Misstates or omits concepts; dumps information or skips logic, confusing students; no comprehension checks and may rely on students for content.",
        points=1,
        standard_group_id=sid("standard-group/content-mastery"),
    ),
    # ── Persona Identity ─────────────────────────────────────────────────
    dict(
        id=sid("standard/persona-identity/excellent"),
        name="Excellent",
        description="Name and description form a vivid, immediately recognizable character with specific personality traits, background, and communication style that clearly differentiates from other personas.",
        points=5,
        standard_group_id=sid("standard-group/persona-identity"),
    ),
    dict(
        id=sid("standard/persona-identity/good"),
        name="Good",
        description="Name and description convey a clear character with identifiable traits. Minor gaps in specificity but the persona is distinct and believable.",
        points=4,
        standard_group_id=sid("standard-group/persona-identity"),
    ),
    dict(
        id=sid("standard/persona-identity/acceptable"),
        name="Acceptable",
        description="Name and description provide a basic character outline but lack specificity. The persona is functional but could be confused with similar archetypes.",
        points=3,
        standard_group_id=sid("standard-group/persona-identity"),
    ),
    dict(
        id=sid("standard/persona-identity/marginal"),
        name="Marginal",
        description="Name or description is generic or vague. The persona lacks distinguishing traits and feels interchangeable.",
        points=2,
        standard_group_id=sid("standard-group/persona-identity"),
    ),
    dict(
        id=sid("standard/persona-identity/poor"),
        name="Poor",
        description="Name and description are missing, contradictory, or so generic they convey no meaningful character.",
        points=1,
        standard_group_id=sid("standard-group/persona-identity"),
    ),
    # ── Persona Behavioral Instructions ──────────────────────────────────
    dict(
        id=sid("standard/persona-behavioral-instructions/excellent"),
        name="Excellent",
        description="Instructions are highly specific and actionable — they define tone, response patterns, boundaries, escalation triggers, and edge-case handling. A different model would produce consistent behavior from these instructions alone.",
        points=5,
        standard_group_id=sid("standard-group/persona-behavioral-instructions"),
    ),
    dict(
        id=sid("standard/persona-behavioral-instructions/good"),
        name="Good",
        description="Instructions cover tone and key behavioral patterns with minor gaps. Most interactions would produce consistent persona behavior.",
        points=4,
        standard_group_id=sid("standard-group/persona-behavioral-instructions"),
    ),
    dict(
        id=sid("standard/persona-behavioral-instructions/acceptable"),
        name="Acceptable",
        description="Instructions provide general guidance but leave significant behavior undefined. Some interactions may produce inconsistent persona behavior.",
        points=3,
        standard_group_id=sid("standard-group/persona-behavioral-instructions"),
    ),
    dict(
        id=sid("standard/persona-behavioral-instructions/marginal"),
        name="Marginal",
        description="Instructions are vague or overly brief. Most behavioral details are left to inference, leading to unpredictable persona responses.",
        points=2,
        standard_group_id=sid("standard-group/persona-behavioral-instructions"),
    ),
    dict(
        id=sid("standard/persona-behavioral-instructions/poor"),
        name="Poor",
        description="Instructions are missing, contradictory, or too generic to drive any specific persona behavior.",
        points=1,
        standard_group_id=sid("standard-group/persona-behavioral-instructions"),
    ),
    # ── Persona Parameter Alignment ──────────────────────────────────────
    dict(
        id=sid("standard/persona-parameter-alignment/excellent"),
        name="Excellent",
        description="All selected parameter fields precisely match the persona's character — temperament, intensity, role, and type selections reinforce the identity and instructions.",
        points=5,
        standard_group_id=sid("standard-group/persona-parameter-alignment"),
    ),
    dict(
        id=sid("standard/persona-parameter-alignment/good"),
        name="Good",
        description="Parameter selections are appropriate with minor mismatches. The overall parameter profile supports the persona's character.",
        points=4,
        standard_group_id=sid("standard-group/persona-parameter-alignment"),
    ),
    dict(
        id=sid("standard/persona-parameter-alignment/acceptable"),
        name="Acceptable",
        description="Some parameter selections are reasonable but others feel arbitrary or disconnected from the persona's identity.",
        points=3,
        standard_group_id=sid("standard-group/persona-parameter-alignment"),
    ),
    dict(
        id=sid("standard/persona-parameter-alignment/marginal"),
        name="Marginal",
        description="Parameter selections are mostly default or misaligned with the persona's stated character traits.",
        points=2,
        standard_group_id=sid("standard-group/persona-parameter-alignment"),
    ),
    dict(
        id=sid("standard/persona-parameter-alignment/poor"),
        name="Poor",
        description="No parameter fields selected, or selections directly contradict the persona's identity.",
        points=1,
        standard_group_id=sid("standard-group/persona-parameter-alignment"),
    ),
    # ── Persona Consistency ──────────────────────────────────────────────
    dict(
        id=sid("standard/persona-consistency/excellent"),
        name="Excellent",
        description="All resources tell a coherent story — name, description, instructions, and parameters mutually reinforce each other with no contradictions.",
        points=5,
        standard_group_id=sid("standard-group/persona-consistency"),
    ),
    dict(
        id=sid("standard/persona-consistency/good"),
        name="Good",
        description="Resources are mostly consistent with minor tonal or detail mismatches that don't undermine the overall persona.",
        points=4,
        standard_group_id=sid("standard-group/persona-consistency"),
    ),
    dict(
        id=sid("standard/persona-consistency/acceptable"),
        name="Acceptable",
        description="Some resources feel disconnected — e.g., instructions suggest a different personality than the name implies, but the persona is still usable.",
        points=3,
        standard_group_id=sid("standard-group/persona-consistency"),
    ),
    dict(
        id=sid("standard/persona-consistency/marginal"),
        name="Marginal",
        description="Notable contradictions between resources. The persona would behave unpredictably due to conflicting signals.",
        points=2,
        standard_group_id=sid("standard-group/persona-consistency"),
    ),
    dict(
        id=sid("standard/persona-consistency/poor"),
        name="Poor",
        description="Resources actively contradict each other or are so disconnected they describe different characters.",
        points=1,
        standard_group_id=sid("standard-group/persona-consistency"),
    ),
    # ── Persona Completeness ─────────────────────────────────────────────
    dict(
        id=sid("standard/persona-completeness/excellent"),
        name="Excellent",
        description="Every relevant resource is populated with a meaningful, considered value. Name, description, instructions, departments, parameter fields, and flags are all set appropriately.",
        points=5,
        standard_group_id=sid("standard-group/persona-completeness"),
    ),
    dict(
        id=sid("standard/persona-completeness/good"),
        name="Good",
        description="Core resources are populated. One or two optional fields may be missing but the persona is fully functional.",
        points=4,
        standard_group_id=sid("standard-group/persona-completeness"),
    ),
    dict(
        id=sid("standard/persona-completeness/acceptable"),
        name="Acceptable",
        description="Required fields are set but several optional resources that would improve the persona are left empty.",
        points=3,
        standard_group_id=sid("standard-group/persona-completeness"),
    ),
    dict(
        id=sid("standard/persona-completeness/marginal"),
        name="Marginal",
        description="Only minimal fields are populated. The persona is technically valid but missing significant detail.",
        points=2,
        standard_group_id=sid("standard-group/persona-completeness"),
    ),
    dict(
        id=sid("standard/persona-completeness/poor"),
        name="Poor",
        description="Critical resources are missing or empty. The persona cannot function as intended.",
        points=1,
        standard_group_id=sid("standard-group/persona-completeness"),
    ),
    # ── University: Clarity ────────────────────────────────────────────
    dict(
        id=sid("standard/uni-clarity/excellent"),
        name="Excellent",
        description="Consistently provides well-structured, step-by-step explanations that make complex information immediately accessible.",
        points=5,
        standard_group_id=sid("standard-group/uni-clarity"),
    ),
    dict(
        id=sid("standard/uni-clarity/good"),
        name="Good",
        description="Explanations are generally clear and organized with minor gaps in structure or detail.",
        points=4,
        standard_group_id=sid("standard-group/uni-clarity"),
    ),
    dict(
        id=sid("standard/uni-clarity/acceptable"),
        name="Acceptable",
        description="Provides basic explanations that convey the main idea but may lack logical flow or skip steps.",
        points=3,
        standard_group_id=sid("standard-group/uni-clarity"),
    ),
    dict(
        id=sid("standard/uni-clarity/marginal"),
        name="Marginal",
        description="Explanations are disorganized or overly dense, requiring the student to fill in gaps.",
        points=2,
        standard_group_id=sid("standard-group/uni-clarity"),
    ),
    dict(
        id=sid("standard/uni-clarity/poor"),
        name="Poor",
        description="Explanations are confusing, contradictory, or absent, leaving the student more confused than before.",
        points=1,
        standard_group_id=sid("standard-group/uni-clarity"),
    ),
    # ── University: Active Listening ─────────────────────────────────
    dict(
        id=sid("standard/uni-active-listening/excellent"),
        name="Excellent",
        description="Consistently paraphrases student concerns, asks targeted clarifying questions, and confirms understanding before proceeding.",
        points=5,
        standard_group_id=sid("standard-group/uni-active-listening"),
    ),
    dict(
        id=sid("standard/uni-active-listening/good"),
        name="Good",
        description="Regularly demonstrates listening through paraphrasing and follow-up questions with occasional missed cues.",
        points=4,
        standard_group_id=sid("standard-group/uni-active-listening"),
    ),
    dict(
        id=sid("standard/uni-active-listening/acceptable"),
        name="Acceptable",
        description="Acknowledges student input but sometimes moves forward without fully confirming understanding.",
        points=3,
        standard_group_id=sid("standard-group/uni-active-listening"),
    ),
    dict(
        id=sid("standard/uni-active-listening/marginal"),
        name="Marginal",
        description="Rarely paraphrases or asks clarifying questions, often responding to assumptions rather than stated concerns.",
        points=2,
        standard_group_id=sid("standard-group/uni-active-listening"),
    ),
    dict(
        id=sid("standard/uni-active-listening/poor"),
        name="Poor",
        description="Ignores or talks over student concerns, showing no evidence of listening.",
        points=1,
        standard_group_id=sid("standard-group/uni-active-listening"),
    ),
    # ── University: Empathy & Rapport ────────────────────────────────
    dict(
        id=sid("standard/uni-empathy/excellent"),
        name="Excellent",
        description="Consistently validates student emotions, creates a warm and supportive tone, and builds genuine rapport throughout the interaction.",
        points=5,
        standard_group_id=sid("standard-group/uni-empathy"),
    ),
    dict(
        id=sid("standard/uni-empathy/good"),
        name="Good",
        description="Shows empathy and warmth with minor moments where tone feels transactional rather than supportive.",
        points=4,
        standard_group_id=sid("standard-group/uni-empathy"),
    ),
    dict(
        id=sid("standard/uni-empathy/acceptable"),
        name="Acceptable",
        description="Acknowledges student emotions at a surface level but doesn't consistently build rapport or create a supportive atmosphere.",
        points=3,
        standard_group_id=sid("standard-group/uni-empathy"),
    ),
    dict(
        id=sid("standard/uni-empathy/marginal"),
        name="Marginal",
        description="Interaction feels impersonal or scripted, with little acknowledgment of the student's emotional state.",
        points=2,
        standard_group_id=sid("standard-group/uni-empathy"),
    ),
    dict(
        id=sid("standard/uni-empathy/poor"),
        name="Poor",
        description="Dismisses or ignores student emotions, creating an adversarial or unwelcoming interaction.",
        points=1,
        standard_group_id=sid("standard-group/uni-empathy"),
    ),
    # ── University: Language Adaptation ───────────────────────────────
    dict(
        id=sid("standard/uni-language-adaptation/excellent"),
        name="Excellent",
        description="Seamlessly adjusts vocabulary and complexity based on student cues, avoiding jargon and checking comprehension naturally.",
        points=5,
        standard_group_id=sid("standard-group/uni-language-adaptation"),
    ),
    dict(
        id=sid("standard/uni-language-adaptation/good"),
        name="Good",
        description="Generally adapts language appropriately with occasional use of unexplained terminology.",
        points=4,
        standard_group_id=sid("standard-group/uni-language-adaptation"),
    ),
    dict(
        id=sid("standard/uni-language-adaptation/acceptable"),
        name="Acceptable",
        description="Uses mostly accessible language but doesn't actively adjust based on student feedback or confusion.",
        points=3,
        standard_group_id=sid("standard-group/uni-language-adaptation"),
    ),
    dict(
        id=sid("standard/uni-language-adaptation/marginal"),
        name="Marginal",
        description="Relies on institutional jargon or overly formal language that creates barriers to understanding.",
        points=2,
        standard_group_id=sid("standard-group/uni-language-adaptation"),
    ),
    dict(
        id=sid("standard/uni-language-adaptation/poor"),
        name="Poor",
        description="Uses inaccessible language throughout, making no effort to match the student's level of understanding.",
        points=1,
        standard_group_id=sid("standard-group/uni-language-adaptation"),
    ),
    # ── University: Policy Accuracy ──────────────────────────────────
    dict(
        id=sid("standard/uni-policy-accuracy/excellent"),
        name="Excellent",
        description="Cites specific policies correctly, clearly distinguishes policy from opinion, and provides accurate details without hesitation.",
        points=5,
        standard_group_id=sid("standard-group/uni-policy-accuracy"),
    ),
    dict(
        id=sid("standard/uni-policy-accuracy/good"),
        name="Good",
        description="References policies accurately with minor omissions or imprecise language that doesn't mislead.",
        points=4,
        standard_group_id=sid("standard-group/uni-policy-accuracy"),
    ),
    dict(
        id=sid("standard/uni-policy-accuracy/acceptable"),
        name="Acceptable",
        description="Provides generally correct policy information but occasionally confuses details or offers vague guidance.",
        points=3,
        standard_group_id=sid("standard-group/uni-policy-accuracy"),
    ),
    dict(
        id=sid("standard/uni-policy-accuracy/marginal"),
        name="Marginal",
        description="Provides inaccurate or outdated policy information, or mixes personal opinion with official guidelines.",
        points=2,
        standard_group_id=sid("standard-group/uni-policy-accuracy"),
    ),
    dict(
        id=sid("standard/uni-policy-accuracy/poor"),
        name="Poor",
        description="States incorrect policies, fabricates guidelines, or shows no awareness of relevant institutional rules.",
        points=1,
        standard_group_id=sid("standard-group/uni-policy-accuracy"),
    ),
    # ── University: Procedure Compliance ─────────────────────────────
    dict(
        id=sid("standard/uni-procedure-compliance/excellent"),
        name="Excellent",
        description="Guides the student through every required step in the correct order, ensuring nothing is missed.",
        points=5,
        standard_group_id=sid("standard-group/uni-procedure-compliance"),
    ),
    dict(
        id=sid("standard/uni-procedure-compliance/good"),
        name="Good",
        description="Follows proper procedures with minor steps mentioned out of order or briefly.",
        points=4,
        standard_group_id=sid("standard-group/uni-procedure-compliance"),
    ),
    dict(
        id=sid("standard/uni-procedure-compliance/acceptable"),
        name="Acceptable",
        description="Covers the main procedural steps but skips secondary requirements or doesn't confirm completion.",
        points=3,
        standard_group_id=sid("standard-group/uni-procedure-compliance"),
    ),
    dict(
        id=sid("standard/uni-procedure-compliance/marginal"),
        name="Marginal",
        description="Misses important procedural steps or provides an incorrect sequence that could cause issues.",
        points=2,
        standard_group_id=sid("standard-group/uni-procedure-compliance"),
    ),
    dict(
        id=sid("standard/uni-procedure-compliance/poor"),
        name="Poor",
        description="Ignores established procedures entirely, offering ad-hoc guidance that circumvents institutional workflows.",
        points=1,
        standard_group_id=sid("standard-group/uni-procedure-compliance"),
    ),
    # ── University: Resource Referral ────────────────────────────────
    dict(
        id=sid("standard/uni-resource-referral/excellent"),
        name="Excellent",
        description="Identifies the exact office, form, or person the student needs and provides actionable next steps for contacting them.",
        points=5,
        standard_group_id=sid("standard-group/uni-resource-referral"),
    ),
    dict(
        id=sid("standard/uni-resource-referral/good"),
        name="Good",
        description="Recommends appropriate resources with minor gaps in specificity (e.g., correct office but no contact details).",
        points=4,
        standard_group_id=sid("standard-group/uni-resource-referral"),
    ),
    dict(
        id=sid("standard/uni-resource-referral/acceptable"),
        name="Acceptable",
        description="Points the student in the right general direction but doesn't identify the specific resource or next step.",
        points=3,
        standard_group_id=sid("standard-group/uni-resource-referral"),
    ),
    dict(
        id=sid("standard/uni-resource-referral/marginal"),
        name="Marginal",
        description="Provides vague or incorrect referrals that could send the student to the wrong place.",
        points=2,
        standard_group_id=sid("standard-group/uni-resource-referral"),
    ),
    dict(
        id=sid("standard/uni-resource-referral/poor"),
        name="Poor",
        description="Makes no attempt to connect the student with relevant resources or directs them to entirely wrong departments.",
        points=1,
        standard_group_id=sid("standard-group/uni-resource-referral"),
    ),
    # ── University: Conflict Recognition ─────────────────────────────
    dict(
        id=sid("standard/uni-conflict-recognition/excellent"),
        name="Excellent",
        description="Immediately recognizes emotional cues, names the student's specific concern, and validates their frustration without being defensive.",
        points=5,
        standard_group_id=sid("standard-group/uni-conflict-recognition"),
    ),
    dict(
        id=sid("standard/uni-conflict-recognition/good"),
        name="Good",
        description="Acknowledges the student's frustration and identifies the core concern with minor delay or imprecision.",
        points=4,
        standard_group_id=sid("standard-group/uni-conflict-recognition"),
    ),
    dict(
        id=sid("standard/uni-conflict-recognition/acceptable"),
        name="Acceptable",
        description="Recognizes that the student is upset but doesn't specifically name or validate the underlying concern.",
        points=3,
        standard_group_id=sid("standard-group/uni-conflict-recognition"),
    ),
    dict(
        id=sid("standard/uni-conflict-recognition/marginal"),
        name="Marginal",
        description="Misreads or minimizes the student's emotional state, leading to responses that feel dismissive.",
        points=2,
        standard_group_id=sid("standard-group/uni-conflict-recognition"),
    ),
    dict(
        id=sid("standard/uni-conflict-recognition/poor"),
        name="Poor",
        description="Ignores clear signs of frustration or becomes defensive, escalating the conflict rather than acknowledging it.",
        points=1,
        standard_group_id=sid("standard-group/uni-conflict-recognition"),
    ),
    # ── University: Emotional Regulation ─────────────────────────────
    dict(
        id=sid("standard/uni-emotional-regulation/excellent"),
        name="Excellent",
        description="Remains calm and composed throughout, modeling emotional stability even when the student is highly agitated.",
        points=5,
        standard_group_id=sid("standard-group/uni-emotional-regulation"),
    ),
    dict(
        id=sid("standard/uni-emotional-regulation/good"),
        name="Good",
        description="Maintains professionalism with brief moments of visible frustration that are quickly recovered.",
        points=4,
        standard_group_id=sid("standard-group/uni-emotional-regulation"),
    ),
    dict(
        id=sid("standard/uni-emotional-regulation/acceptable"),
        name="Acceptable",
        description="Generally stays composed but occasionally mirrors the student's agitation or uses reactive language.",
        points=3,
        standard_group_id=sid("standard-group/uni-emotional-regulation"),
    ),
    dict(
        id=sid("standard/uni-emotional-regulation/marginal"),
        name="Marginal",
        description="Shows visible frustration or impatience that affects the quality of the interaction.",
        points=2,
        standard_group_id=sid("standard-group/uni-emotional-regulation"),
    ),
    dict(
        id=sid("standard/uni-emotional-regulation/poor"),
        name="Poor",
        description="Loses composure, responds emotionally, or retaliates, making the situation significantly worse.",
        points=1,
        standard_group_id=sid("standard-group/uni-emotional-regulation"),
    ),
    # ── University: Solution-Oriented Approach ───────────────────────
    dict(
        id=sid("standard/uni-solution-oriented/excellent"),
        name="Excellent",
        description="Smoothly redirects from complaints to concrete next steps, offering multiple options and collaborating on a resolution.",
        points=5,
        standard_group_id=sid("standard-group/uni-solution-oriented"),
    ),
    dict(
        id=sid("standard/uni-solution-oriented/good"),
        name="Good",
        description="Offers actionable solutions with minor gaps in specificity or collaboration.",
        points=4,
        standard_group_id=sid("standard-group/uni-solution-oriented"),
    ),
    dict(
        id=sid("standard/uni-solution-oriented/acceptable"),
        name="Acceptable",
        description="Attempts to resolve the situation but offers generic solutions without tailoring to the student's specific problem.",
        points=3,
        standard_group_id=sid("standard-group/uni-solution-oriented"),
    ),
    dict(
        id=sid("standard/uni-solution-oriented/marginal"),
        name="Marginal",
        description="Focuses on explaining why the problem exists rather than working toward a resolution.",
        points=2,
        standard_group_id=sid("standard-group/uni-solution-oriented"),
    ),
    dict(
        id=sid("standard/uni-solution-oriented/poor"),
        name="Poor",
        description="Makes no attempt to resolve the situation or offers solutions that are unrealistic or dismissive.",
        points=1,
        standard_group_id=sid("standard-group/uni-solution-oriented"),
    ),
    # ── University: Professional Tone ────────────────────────────────
    dict(
        id=sid("standard/uni-professional-tone/excellent"),
        name="Excellent",
        description="Consistently uses measured, respectful language even under pressure; tone remains warm but professional throughout.",
        points=5,
        standard_group_id=sid("standard-group/uni-professional-tone"),
    ),
    dict(
        id=sid("standard/uni-professional-tone/good"),
        name="Good",
        description="Maintains a professional tone with minor lapses that don't significantly impact the interaction.",
        points=4,
        standard_group_id=sid("standard-group/uni-professional-tone"),
    ),
    dict(
        id=sid("standard/uni-professional-tone/acceptable"),
        name="Acceptable",
        description="Tone is generally appropriate but occasionally comes across as curt, overly formal, or slightly condescending.",
        points=3,
        standard_group_id=sid("standard-group/uni-professional-tone"),
    ),
    dict(
        id=sid("standard/uni-professional-tone/marginal"),
        name="Marginal",
        description="Uses language that is noticeably confrontational, sarcastic, or dismissive at points during the conversation.",
        points=2,
        standard_group_id=sid("standard-group/uni-professional-tone"),
    ),
    dict(
        id=sid("standard/uni-professional-tone/poor"),
        name="Poor",
        description="Tone is hostile, sarcastic, or unprofessional, actively damaging the student relationship.",
        points=1,
        standard_group_id=sid("standard-group/uni-professional-tone"),
    ),
]
