"""Standard group resource seeds.

5 standard groups shared across all base rubrics (Adaptability, Active Listening,
Content Mastery, Communication, Time Management).
"""

from database.seeds.ids import sid

standard_groups = [
    dict(
        id=sid("standard-group/adaptability"),
        name="Adapts approach to individual student needs",
        short_name="Adaptability",
        description="Flexibility in teaching approach based on student personality and needs.",
        points=5,
        pass_points=4,
    ),
    dict(
        id=sid("standard-group/active-listening"),
        name="Facilitates student-driven learning",
        short_name="Active Listening",
        description="Ability to guide students to discover solutions independently through questioning.",
        points=5,
        pass_points=4,
    ),
    dict(
        id=sid("standard-group/content-mastery"),
        name="Demonstrates understanding of core concepts",
        short_name="Content Mastery",
        description="Knowledge and articulation of core goals and learning outcomes.",
        points=5,
        pass_points=4,
    ),
    dict(
        id=sid("standard-group/communication"),
        name="Interpersonal communication and professionalism",
        short_name="Communication",
        description="Flexibility in teaching approach based on student personality and needs.",
        points=5,
        pass_points=4,
    ),
    dict(
        id=sid("standard-group/time-management"),
        name="Manages session time effectively",
        short_name="Time Management",
        description="Efficient use of session time and respect for scheduling.",
        points=5,
        pass_points=4,
    ),
    # ── Persona-specific standard groups (for agent eval) ────────────────
    dict(
        id=sid("standard-group/persona-identity"),
        name="Creates a distinct, believable persona identity",
        short_name="Identity",
        description="Name and description capture a specific, differentiated character with clear personality traits.",
        points=5,
        pass_points=4,
    ),
    dict(
        id=sid("standard-group/persona-behavioral-instructions"),
        name="Produces actionable behavioral instructions",
        short_name="Behavioral Instructions",
        description="Instructions are specific and actionable, driving consistent persona behavior including tone, boundaries, and response patterns.",
        points=5,
        pass_points=4,
    ),
    dict(
        id=sid("standard-group/persona-parameter-alignment"),
        name="Selects appropriate parameter fields",
        short_name="Parameter Alignment",
        description="Selected parameter fields (temperament, intensity, role, type) accurately reflect the persona's intended character.",
        points=5,
        pass_points=4,
    ),
    dict(
        id=sid("standard-group/persona-consistency"),
        name="Maintains coherence across all resources",
        short_name="Consistency",
        description="All resources are coherent — name matches description, description matches instructions, parameters match the overall persona identity.",
        points=5,
        pass_points=4,
    ),
    dict(
        id=sid("standard-group/persona-completeness"),
        name="Populates all relevant persona resources",
        short_name="Completeness",
        description="All relevant resources are populated with meaningful values — nothing critical is left empty or at defaults when it should be specified.",
        points=5,
        pass_points=4,
    ),
    # ── University: Communication Skills rubric ────────────────────────
    dict(
        id=sid("standard-group/uni-clarity"),
        name="Explains concepts clearly and in a structured way",
        short_name="Clarity",
        description="Provides organized, easy-to-follow explanations that break complex information into digestible parts.",
        points=5,
        pass_points=4,
    ),
    dict(
        id=sid("standard-group/uni-active-listening"),
        name="Demonstrates understanding of student concerns",
        short_name="Active Listening",
        description="Listens attentively, paraphrases student concerns, and asks clarifying questions to confirm understanding.",
        points=5,
        pass_points=4,
    ),
    dict(
        id=sid("standard-group/uni-empathy"),
        name="Shows empathy and builds rapport with students",
        short_name="Empathy & Rapport",
        description="Acknowledges student emotions, validates their experience, and creates a supportive conversational environment.",
        points=5,
        pass_points=4,
    ),
    dict(
        id=sid("standard-group/uni-language-adaptation"),
        name="Adapts language to the student's level of understanding",
        short_name="Language Adaptation",
        description="Adjusts vocabulary, tone, and complexity based on student cues, avoiding jargon when unnecessary.",
        points=5,
        pass_points=4,
    ),
    # ── University: Policy Knowledge rubric ──────────────────────────
    dict(
        id=sid("standard-group/uni-policy-accuracy"),
        name="Cites policies and guidelines accurately",
        short_name="Policy Accuracy",
        description="References correct institutional policies, avoids misinformation, and distinguishes policy from personal opinion.",
        points=5,
        pass_points=4,
    ),
    dict(
        id=sid("standard-group/uni-procedure-compliance"),
        name="Follows proper institutional procedures",
        short_name="Procedure Compliance",
        description="Guides students through correct procedural steps and adheres to established institutional workflows.",
        points=5,
        pass_points=4,
    ),
    dict(
        id=sid("standard-group/uni-resource-referral"),
        name="Directs students to appropriate institutional resources",
        short_name="Resource Referral",
        description="Identifies and recommends the correct offices, forms, or personnel for the student's specific situation.",
        points=5,
        pass_points=4,
    ),
    # ── University: De-escalation rubric ─────────────────────────────
    dict(
        id=sid("standard-group/uni-conflict-recognition"),
        name="Identifies and acknowledges the source of frustration",
        short_name="Conflict Recognition",
        description="Recognizes emotional cues, names the student's concern, and validates their frustration without being defensive.",
        points=5,
        pass_points=4,
    ),
    dict(
        id=sid("standard-group/uni-emotional-regulation"),
        name="Maintains composure and professional demeanor",
        short_name="Emotional Regulation",
        description="Stays calm under pressure, avoids reactive language, and models emotional stability throughout the interaction.",
        points=5,
        pass_points=4,
    ),
    dict(
        id=sid("standard-group/uni-solution-oriented"),
        name="Guides conversation toward constructive resolution",
        short_name="Solution-Oriented Approach",
        description="Redirects from complaints to actionable next steps, offering concrete options and collaborative problem-solving.",
        points=5,
        pass_points=4,
    ),
    dict(
        id=sid("standard-group/uni-professional-tone"),
        name="Maintains calm, respectful, non-confrontational language",
        short_name="Professional Tone",
        description="Uses measured, respectful phrasing even when challenged; avoids sarcasm, dismissiveness, or escalating language.",
        points=5,
        pass_points=4,
    ),
]
