"""Standard resource seeds.

25 standards (5 levels per standard group): Excellent, Good, Acceptable, Marginal, Poor.
"""

from database.seeds.ids import sid

standards = [
    # ── Active Listening ──────────────────────────────────────────────────
    dict(
        id=sid("standard/active-listening/excellent"),
        name="Excellent",
        description="Consistently employs open-ended questions that empower students to discover solutions independently.",
        points=5,
        standard_group_id=sid("standard-group/active-listening"),
    ),
    dict(
        id=sid("standard/active-listening/good"),
        name="Good",
        description="Regularly uses guided questioning, encouraging student reasoning with occasional prompts.",
        points=4,
        standard_group_id=sid("standard-group/active-listening"),
    ),
    dict(
        id=sid("standard/active-listening/acceptable"),
        name="Acceptable",
        description="Occasionally guides students with questions but sometimes provides direct answers.",
        points=3,
        standard_group_id=sid("standard-group/active-listening"),
    ),
    dict(
        id=sid("standard/active-listening/marginal"),
        name="Marginal",
        description="Rarely uses questioning techniques, often resorting to hints or partial solutions.",
        points=2,
        standard_group_id=sid("standard-group/active-listening"),
    ),
    dict(
        id=sid("standard/active-listening/poor"),
        name="Poor",
        description="Directly provided the answer.",
        points=1,
        standard_group_id=sid("standard-group/active-listening"),
    ),
    # ── Time Management ───────────────────────────────────────────────────
    dict(
        id=sid("standard/time-management/excellent"),
        name="Excellent",
        description="Begins and concludes sessions within scheduled times, maximizing productivity and respecting student availability.",
        points=5,
        standard_group_id=sid("standard-group/time-management"),
    ),
    dict(
        id=sid("standard/time-management/good"),
        name="Good",
        description="Generally adheres to time allocations with minor deviations that do not impact session quality.",
        points=4,
        standard_group_id=sid("standard-group/time-management"),
    ),
    dict(
        id=sid("standard/time-management/acceptable"),
        name="Acceptable",
        description="Sometimes exceeds or finishes early, slightly affecting pacing yet maintaining core engagement.",
        points=3,
        standard_group_id=sid("standard-group/time-management"),
    ),
    dict(
        id=sid("standard/time-management/marginal"),
        name="Marginal",
        description="Frequently mismanages time, leading to rushed explanations or unnecessary prolongation.",
        points=2,
        standard_group_id=sid("standard-group/time-management"),
    ),
    dict(
        id=sid("standard/time-management/poor"),
        name="Poor",
        description="Ended the conversation really early, or made it last longer than needed.",
        points=1,
        standard_group_id=sid("standard-group/time-management"),
    ),
    # ── Adaptability ──────────────────────────────────────────────────────
    dict(
        id=sid("standard/adaptability/excellent"),
        name="Excellent",
        description="Perfectly adapts approach to diverse student emotional and attitude types.",
        points=5,
        standard_group_id=sid("standard-group/adaptability"),
    ),
    dict(
        id=sid("standard/adaptability/good"),
        name="Good",
        description="Mostly seamlessly adjusted communication and teaching style to effectively engage students across a wide range of emotions.",
        points=4,
        standard_group_id=sid("standard-group/adaptability"),
    ),
    dict(
        id=sid("standard/adaptability/acceptable"),
        name="Acceptable",
        description="Demonstrates thoughtful adjustments to support most student types, maintaining a supportive and responsive demeanor.",
        points=3,
        standard_group_id=sid("standard-group/adaptability"),
    ),
    dict(
        id=sid("standard/adaptability/marginal"),
        name="Marginal",
        description="Shows minimal ability to adjust to varied student behaviors, occasionally missing cues or responding inappropriately.",
        points=2,
        standard_group_id=sid("standard-group/adaptability"),
    ),
    dict(
        id=sid("standard/adaptability/poor"),
        name="Poor",
        description="Fails to adapt to different student types, responding uniformly without consideration of individual emotional or behavioral needs.",
        points=1,
        standard_group_id=sid("standard-group/adaptability"),
    ),
    # ── Communication ─────────────────────────────────────────────────────
    dict(
        id=sid("standard/communication/excellent"),
        name="Excellent",
        description="Consistently communicates with clarity and professionalism. Follows up when needed and maintains respectful boundaries in all interactions.",
        points=5,
        standard_group_id=sid("standard-group/communication"),
    ),
    dict(
        id=sid("standard/communication/good"),
        name="Good",
        description="Communicates respectfully and clearly with minor lapses in tone or timing. Upholds professional standards.",
        points=4,
        standard_group_id=sid("standard-group/communication"),
    ),
    dict(
        id=sid("standard/communication/acceptable"),
        name="Acceptable",
        description="Communication is mostly appropriate but may occasionally be abrupt, or overly casual.",
        points=3,
        standard_group_id=sid("standard-group/communication"),
    ),
    dict(
        id=sid("standard/communication/marginal"),
        name="Marginal",
        description="Shows limited awareness of tone or affect. May interrupt, dismiss student concerns, or respond in ways that feel cold or reactive.",
        points=2,
        standard_group_id=sid("standard-group/communication"),
    ),
    dict(
        id=sid("standard/communication/poor"),
        name="Poor",
        description="Demonstrates inappropriate or unprofessional behavior (e.g., sarcastic tone, dismissive responses, or failure to maintain respectful interaction).",
        points=1,
        standard_group_id=sid("standard-group/communication"),
    ),
    # ── Content Mastery ───────────────────────────────────────────────────
    dict(
        id=sid("standard/content-mastery/excellent"),
        name="Excellent",
        description="States core concepts clearly; explains in clear, bite-sized steps; uses analogies/visuals to clarify when needed; consistently checks understanding.",
        points=5,
        standard_group_id=sid("standard-group/content-mastery"),
    ),
    dict(
        id=sid("standard/content-mastery/good"),
        name="Good",
        description="Explains core concepts accurately and relates examples to key learning outcomes. Generally provides step-by-step reasoning and occasionally checks for student comprehension.",
        points=4,
        standard_group_id=sid("standard-group/content-mastery"),
    ),
    dict(
        id=sid("standard/content-mastery/acceptable"),
        name="Acceptable",
        description="Provides a basic overview of concepts but with occasional inaccuracies or lack of depth. Some explanations may feel rushed or cognitively dense.",
        points=3,
        standard_group_id=sid("standard-group/content-mastery"),
    ),
    dict(
        id=sid("standard/content-mastery/marginal"),
        name="Marginal",
        description="Demonstrates limited awareness of core concepts and offers explanations with minor errors. Explanations frequently rushed, dense, or skip logical steps; seldom checks comprehension.",
        points=2,
        standard_group_id=sid("standard-group/content-mastery"),
    ),
    dict(
        id=sid("standard/content-mastery/poor"),
        name="Poor",
        description="Misstates or omits concepts; dumps information or skips logic, confusing students; no comprehension checks and may rely on students for content.",
        points=1,
        standard_group_id=sid("standard-group/content-mastery"),
    ),
    # ── Persona Identity ─────────────────────────────────────────────────
    dict(
        id=sid("standard/persona-identity/excellent"),
        name="Excellent",
        description="Name and description form a vivid, immediately recognizable character with specific personality traits, background, and communication style that clearly differentiates from other personas.",
        points=5,
        standard_group_id=sid("standard-group/persona-identity"),
    ),
    dict(
        id=sid("standard/persona-identity/good"),
        name="Good",
        description="Name and description convey a clear character with identifiable traits. Minor gaps in specificity but the persona is distinct and believable.",
        points=4,
        standard_group_id=sid("standard-group/persona-identity"),
    ),
    dict(
        id=sid("standard/persona-identity/acceptable"),
        name="Acceptable",
        description="Name and description provide a basic character outline but lack specificity. The persona is functional but could be confused with similar archetypes.",
        points=3,
        standard_group_id=sid("standard-group/persona-identity"),
    ),
    dict(
        id=sid("standard/persona-identity/marginal"),
        name="Marginal",
        description="Name or description is generic or vague. The persona lacks distinguishing traits and feels interchangeable.",
        points=2,
        standard_group_id=sid("standard-group/persona-identity"),
    ),
    dict(
        id=sid("standard/persona-identity/poor"),
        name="Poor",
        description="Name and description are missing, contradictory, or so generic they convey no meaningful character.",
        points=1,
        standard_group_id=sid("standard-group/persona-identity"),
    ),
    # ── Persona Behavioral Instructions ──────────────────────────────────
    dict(
        id=sid("standard/persona-behavioral-instructions/excellent"),
        name="Excellent",
        description="Instructions are highly specific and actionable — they define tone, response patterns, boundaries, escalation triggers, and edge-case handling. A different model would produce consistent behavior from these instructions alone.",
        points=5,
        standard_group_id=sid("standard-group/persona-behavioral-instructions"),
    ),
    dict(
        id=sid("standard/persona-behavioral-instructions/good"),
        name="Good",
        description="Instructions cover tone and key behavioral patterns with minor gaps. Most interactions would produce consistent persona behavior.",
        points=4,
        standard_group_id=sid("standard-group/persona-behavioral-instructions"),
    ),
    dict(
        id=sid("standard/persona-behavioral-instructions/acceptable"),
        name="Acceptable",
        description="Instructions provide general guidance but leave significant behavior undefined. Some interactions may produce inconsistent persona behavior.",
        points=3,
        standard_group_id=sid("standard-group/persona-behavioral-instructions"),
    ),
    dict(
        id=sid("standard/persona-behavioral-instructions/marginal"),
        name="Marginal",
        description="Instructions are vague or overly brief. Most behavioral details are left to inference, leading to unpredictable persona responses.",
        points=2,
        standard_group_id=sid("standard-group/persona-behavioral-instructions"),
    ),
    dict(
        id=sid("standard/persona-behavioral-instructions/poor"),
        name="Poor",
        description="Instructions are missing, contradictory, or too generic to drive any specific persona behavior.",
        points=1,
        standard_group_id=sid("standard-group/persona-behavioral-instructions"),
    ),
    # ── Persona Parameter Alignment ──────────────────────────────────────
    dict(
        id=sid("standard/persona-parameter-alignment/excellent"),
        name="Excellent",
        description="All selected parameter fields precisely match the persona's character — temperament, intensity, role, and type selections reinforce the identity and instructions.",
        points=5,
        standard_group_id=sid("standard-group/persona-parameter-alignment"),
    ),
    dict(
        id=sid("standard/persona-parameter-alignment/good"),
        name="Good",
        description="Parameter selections are appropriate with minor mismatches. The overall parameter profile supports the persona's character.",
        points=4,
        standard_group_id=sid("standard-group/persona-parameter-alignment"),
    ),
    dict(
        id=sid("standard/persona-parameter-alignment/acceptable"),
        name="Acceptable",
        description="Some parameter selections are reasonable but others feel arbitrary or disconnected from the persona's identity.",
        points=3,
        standard_group_id=sid("standard-group/persona-parameter-alignment"),
    ),
    dict(
        id=sid("standard/persona-parameter-alignment/marginal"),
        name="Marginal",
        description="Parameter selections are mostly default or misaligned with the persona's stated character traits.",
        points=2,
        standard_group_id=sid("standard-group/persona-parameter-alignment"),
    ),
    dict(
        id=sid("standard/persona-parameter-alignment/poor"),
        name="Poor",
        description="No parameter fields selected, or selections directly contradict the persona's identity.",
        points=1,
        standard_group_id=sid("standard-group/persona-parameter-alignment"),
    ),
    # ── Persona Consistency ──────────────────────────────────────────────
    dict(
        id=sid("standard/persona-consistency/excellent"),
        name="Excellent",
        description="All resources tell a coherent story — name, description, instructions, and parameters mutually reinforce each other with no contradictions.",
        points=5,
        standard_group_id=sid("standard-group/persona-consistency"),
    ),
    dict(
        id=sid("standard/persona-consistency/good"),
        name="Good",
        description="Resources are mostly consistent with minor tonal or detail mismatches that don't undermine the overall persona.",
        points=4,
        standard_group_id=sid("standard-group/persona-consistency"),
    ),
    dict(
        id=sid("standard/persona-consistency/acceptable"),
        name="Acceptable",
        description="Some resources feel disconnected — e.g., instructions suggest a different personality than the name implies, but the persona is still usable.",
        points=3,
        standard_group_id=sid("standard-group/persona-consistency"),
    ),
    dict(
        id=sid("standard/persona-consistency/marginal"),
        name="Marginal",
        description="Notable contradictions between resources. The persona would behave unpredictably due to conflicting signals.",
        points=2,
        standard_group_id=sid("standard-group/persona-consistency"),
    ),
    dict(
        id=sid("standard/persona-consistency/poor"),
        name="Poor",
        description="Resources actively contradict each other or are so disconnected they describe different characters.",
        points=1,
        standard_group_id=sid("standard-group/persona-consistency"),
    ),
    # ── Persona Completeness ─────────────────────────────────────────────
    dict(
        id=sid("standard/persona-completeness/excellent"),
        name="Excellent",
        description="Every relevant resource is populated with a meaningful, considered value. Name, description, instructions, departments, parameter fields, and flags are all set appropriately.",
        points=5,
        standard_group_id=sid("standard-group/persona-completeness"),
    ),
    dict(
        id=sid("standard/persona-completeness/good"),
        name="Good",
        description="Core resources are populated. One or two optional fields may be missing but the persona is fully functional.",
        points=4,
        standard_group_id=sid("standard-group/persona-completeness"),
    ),
    dict(
        id=sid("standard/persona-completeness/acceptable"),
        name="Acceptable",
        description="Required fields are set but several optional resources that would improve the persona are left empty.",
        points=3,
        standard_group_id=sid("standard-group/persona-completeness"),
    ),
    dict(
        id=sid("standard/persona-completeness/marginal"),
        name="Marginal",
        description="Only minimal fields are populated. The persona is technically valid but missing significant detail.",
        points=2,
        standard_group_id=sid("standard-group/persona-completeness"),
    ),
    dict(
        id=sid("standard/persona-completeness/poor"),
        name="Poor",
        description="Critical resources are missing or empty. The persona cannot function as intended.",
        points=1,
        standard_group_id=sid("standard-group/persona-completeness"),
    ),
]
