-- Migration: Drop version column from all draft tables and MVs
-- Purpose: version is redundant — created_at + uuidv7 ordering already provides
-- the same functionality. Drafts are append-only, so "latest version" is just
-- the most recent row by created_at.
--
-- Steps:
--   1. Drop all 19 draft MVs (they reference version)
--   2. Drop version from 19 entry tables + 182 connection tables
--   3. Recreate MVs without version
--   4. Recreate MV indexes

DROP MATERIALIZED VIEW IF EXISTS public.agent_drafts_mv CASCADE;
DROP MATERIALIZED VIEW IF EXISTS public.auth_drafts_mv CASCADE;
DROP MATERIALIZED VIEW IF EXISTS public.chat_drafts_mv CASCADE;
DROP MATERIALIZED VIEW IF EXISTS public.cohort_drafts_mv CASCADE;
DROP MATERIALIZED VIEW IF EXISTS public.department_drafts_mv CASCADE;
DROP MATERIALIZED VIEW IF EXISTS public.document_drafts_mv CASCADE;
DROP MATERIALIZED VIEW IF EXISTS public.eval_drafts_mv CASCADE;
DROP MATERIALIZED VIEW IF EXISTS public.field_drafts_mv CASCADE;
DROP MATERIALIZED VIEW IF EXISTS public.invocation_drafts_mv CASCADE;
DROP MATERIALIZED VIEW IF EXISTS public.model_drafts_mv CASCADE;
DROP MATERIALIZED VIEW IF EXISTS public.parameter_drafts_mv CASCADE;
DROP MATERIALIZED VIEW IF EXISTS public.persona_drafts_mv CASCADE;
DROP MATERIALIZED VIEW IF EXISTS public.profile_drafts_mv CASCADE;
DROP MATERIALIZED VIEW IF EXISTS public.provider_drafts_mv CASCADE;
DROP MATERIALIZED VIEW IF EXISTS public.rubric_drafts_mv CASCADE;
DROP MATERIALIZED VIEW IF EXISTS public.scenario_drafts_mv CASCADE;
DROP MATERIALIZED VIEW IF EXISTS public.setting_drafts_mv CASCADE;
DROP MATERIALIZED VIEW IF EXISTS public.simulation_drafts_mv CASCADE;
DROP MATERIALIZED VIEW IF EXISTS public.tool_drafts_mv CASCADE;
ALTER TABLE public.agent_drafts_entry DROP COLUMN IF EXISTS version;
ALTER TABLE public.agent_drafts_flags_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.agent_drafts_models_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.agent_drafts_names_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.agent_drafts_profiles_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.agent_drafts_qualities_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.agent_drafts_reasoning_levels_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.agent_drafts_rubrics_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.agent_drafts_temperature_levels_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.agent_drafts_tools_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.agent_drafts_voices_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.auth_drafts_departments_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.auth_drafts_descriptions_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.auth_drafts_entry DROP COLUMN IF EXISTS version;
ALTER TABLE public.auth_drafts_flags_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.auth_drafts_items_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.auth_drafts_names_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.auth_drafts_profiles_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.auth_drafts_protocols_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.auth_drafts_slugs_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.chat_drafts_departments_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.chat_drafts_descriptions_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.chat_drafts_documents_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.chat_drafts_entry DROP COLUMN IF EXISTS version;
ALTER TABLE public.chat_drafts_fields_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.chat_drafts_flags_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.chat_drafts_images_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.chat_drafts_names_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.chat_drafts_objectives_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.chat_drafts_options_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.chat_drafts_parameter_fields_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.chat_drafts_parameters_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.chat_drafts_personas_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.chat_drafts_problem_statements_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.chat_drafts_profiles_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.chat_drafts_questions_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.chat_drafts_scenarios_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.chat_drafts_videos_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.cohort_drafts_departments_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.cohort_drafts_descriptions_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.cohort_drafts_entry DROP COLUMN IF EXISTS version;
ALTER TABLE public.cohort_drafts_flags_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.cohort_drafts_names_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.cohort_drafts_profile_personas_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.cohort_drafts_profiles_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.cohort_drafts_simulation_positions_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.cohort_drafts_simulations_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.department_drafts_descriptions_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.department_drafts_entry DROP COLUMN IF EXISTS version;
ALTER TABLE public.department_drafts_flags_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.department_drafts_names_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.department_drafts_profiles_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.department_drafts_settings_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.document_drafts_departments_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.document_drafts_descriptions_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.document_drafts_entry DROP COLUMN IF EXISTS version;
ALTER TABLE public.document_drafts_files_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.document_drafts_flags_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.document_drafts_images_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.document_drafts_names_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.document_drafts_parameter_fields_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.document_drafts_parameters_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.document_drafts_profiles_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.document_drafts_texts_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.eval_drafts_departments_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.eval_drafts_descriptions_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.eval_drafts_entry DROP COLUMN IF EXISTS version;
ALTER TABLE public.eval_drafts_flags_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.eval_drafts_models_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.eval_drafts_names_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.eval_drafts_profiles_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.eval_drafts_rubrics_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.field_drafts_conditional_parameters_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.field_drafts_departments_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.field_drafts_descriptions_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.field_drafts_entry DROP COLUMN IF EXISTS version;
ALTER TABLE public.field_drafts_flags_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.field_drafts_names_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.field_drafts_profiles_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.invocation_drafts_departments_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.invocation_drafts_descriptions_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.invocation_drafts_entry DROP COLUMN IF EXISTS version;
ALTER TABLE public.invocation_drafts_flags_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.invocation_drafts_keys_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.invocation_drafts_model_flags_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.invocation_drafts_model_positions_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.invocation_drafts_model_rubrics_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.invocation_drafts_names_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.invocation_drafts_profiles_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.invocation_drafts_reasoning_levels_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.invocation_drafts_temperature_levels_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.invocation_drafts_voices_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.model_drafts_departments_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.model_drafts_descriptions_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.model_drafts_entry DROP COLUMN IF EXISTS version;
ALTER TABLE public.model_drafts_flags_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.model_drafts_modalities_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.model_drafts_names_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.model_drafts_pricing_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.model_drafts_profiles_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.model_drafts_providers_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.model_drafts_qualities_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.model_drafts_reasoning_levels_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.model_drafts_temperature_levels_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.model_drafts_values_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.model_drafts_voices_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.parameter_drafts_departments_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.parameter_drafts_descriptions_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.parameter_drafts_entry DROP COLUMN IF EXISTS version;
ALTER TABLE public.parameter_drafts_fields_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.parameter_drafts_flags_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.parameter_drafts_names_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.parameter_drafts_profiles_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.persona_drafts_colors_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.persona_drafts_departments_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.persona_drafts_descriptions_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.persona_drafts_entry DROP COLUMN IF EXISTS version;
ALTER TABLE public.persona_drafts_examples_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.persona_drafts_flags_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.persona_drafts_icons_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.persona_drafts_instructions_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.persona_drafts_names_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.persona_drafts_parameter_fields_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.persona_drafts_profiles_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.persona_drafts_voices_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.profile_drafts_departments_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.profile_drafts_emails_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.profile_drafts_entry DROP COLUMN IF EXISTS version;
ALTER TABLE public.profile_drafts_flags_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.profile_drafts_names_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.profile_drafts_profiles_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.profile_drafts_roles_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.provider_drafts_departments_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.provider_drafts_descriptions_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.provider_drafts_endpoints_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.provider_drafts_entry DROP COLUMN IF EXISTS version;
ALTER TABLE public.provider_drafts_flags_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.provider_drafts_keys_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.provider_drafts_names_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.provider_drafts_profiles_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.provider_drafts_values_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.rubric_drafts_departments_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.rubric_drafts_descriptions_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.rubric_drafts_entry DROP COLUMN IF EXISTS version;
ALTER TABLE public.rubric_drafts_flags_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.rubric_drafts_names_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.rubric_drafts_points_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.rubric_drafts_profiles_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.rubric_drafts_standard_groups_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.rubric_drafts_standards_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.scenario_drafts_departments_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.scenario_drafts_descriptions_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.scenario_drafts_documents_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.scenario_drafts_entry DROP COLUMN IF EXISTS version;
ALTER TABLE public.scenario_drafts_flags_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.scenario_drafts_images_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.scenario_drafts_names_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.scenario_drafts_objectives_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.scenario_drafts_options_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.scenario_drafts_parameter_fields_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.scenario_drafts_personas_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.scenario_drafts_problem_statements_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.scenario_drafts_profiles_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.scenario_drafts_questions_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.scenario_drafts_videos_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.setting_drafts_agents_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.setting_drafts_auth_item_keys_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.setting_drafts_auths_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.setting_drafts_colors_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.setting_drafts_departments_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.setting_drafts_descriptions_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.setting_drafts_entry DROP COLUMN IF EXISTS version;
ALTER TABLE public.setting_drafts_flags_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.setting_drafts_items_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.setting_drafts_names_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.setting_drafts_profiles_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.setting_drafts_provider_keys_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.setting_drafts_thresholds_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.simulation_drafts_departments_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.simulation_drafts_descriptions_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.simulation_drafts_entry DROP COLUMN IF EXISTS version;
ALTER TABLE public.simulation_drafts_flags_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.simulation_drafts_names_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.simulation_drafts_profiles_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.simulation_drafts_scenario_flags_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.simulation_drafts_scenario_positions_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.simulation_drafts_scenario_rubrics_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.simulation_drafts_scenario_time_limits_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.simulation_drafts_scenarios_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.tool_drafts_arg_positions_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.tool_drafts_args_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.tool_drafts_args_outputs_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.tool_drafts_departments_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.tool_drafts_descriptions_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.tool_drafts_entry DROP COLUMN IF EXISTS version;
ALTER TABLE public.tool_drafts_flags_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.tool_drafts_instructions_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.tool_drafts_names_connection DROP COLUMN IF EXISTS version;
ALTER TABLE public.tool_drafts_profiles_connection DROP COLUMN IF EXISTS version;
CREATE MATERIALIZED VIEW public.agent_drafts_mv AS SELECT id, created_at, generated, mcp, active, group_id, session_id FROM public.agent_drafts_entry WHERE active = true WITH NO DATA;
CREATE MATERIALIZED VIEW public.auth_drafts_mv AS SELECT id, created_at, generated, mcp, active, group_id, session_id FROM public.auth_drafts_entry WHERE active = true WITH NO DATA;
CREATE MATERIALIZED VIEW public.chat_drafts_mv AS SELECT id, created_at, generated, mcp, active, group_id, session_id FROM public.chat_drafts_entry WHERE active = true WITH NO DATA;
CREATE MATERIALIZED VIEW public.cohort_drafts_mv AS SELECT id, created_at, generated, mcp, active, group_id, session_id FROM public.cohort_drafts_entry WHERE active = true WITH NO DATA;
CREATE MATERIALIZED VIEW public.department_drafts_mv AS SELECT id, created_at, generated, mcp, active, group_id, session_id FROM public.department_drafts_entry WHERE active = true WITH NO DATA;
CREATE MATERIALIZED VIEW public.document_drafts_mv AS SELECT id, created_at, generated, mcp, active, group_id, session_id FROM public.document_drafts_entry WHERE active = true WITH NO DATA;
CREATE MATERIALIZED VIEW public.eval_drafts_mv AS SELECT id, created_at, generated, mcp, active, group_id, session_id FROM public.eval_drafts_entry WHERE active = true WITH NO DATA;
CREATE MATERIALIZED VIEW public.field_drafts_mv AS SELECT id, created_at, generated, mcp, active, group_id, session_id FROM public.field_drafts_entry WHERE active = true WITH NO DATA;
CREATE MATERIALIZED VIEW public.invocation_drafts_mv AS SELECT id, created_at, generated, mcp, active, group_id, session_id FROM public.invocation_drafts_entry WHERE active = true WITH NO DATA;
CREATE MATERIALIZED VIEW public.model_drafts_mv AS SELECT id, created_at, generated, mcp, active, group_id, session_id FROM public.model_drafts_entry WHERE active = true WITH NO DATA;
CREATE MATERIALIZED VIEW public.parameter_drafts_mv AS SELECT id, created_at, generated, mcp, active, group_id, session_id FROM public.parameter_drafts_entry WHERE active = true WITH NO DATA;
CREATE MATERIALIZED VIEW public.persona_drafts_mv AS SELECT id, created_at, generated, mcp, active, group_id, session_id FROM public.persona_drafts_entry WHERE active = true WITH NO DATA;
CREATE MATERIALIZED VIEW public.profile_drafts_mv AS SELECT id, created_at, generated, mcp, active, group_id, session_id FROM public.profile_drafts_entry WHERE active = true WITH NO DATA;
CREATE MATERIALIZED VIEW public.provider_drafts_mv AS SELECT id, created_at, generated, mcp, active, group_id, session_id FROM public.provider_drafts_entry WHERE active = true WITH NO DATA;
CREATE MATERIALIZED VIEW public.rubric_drafts_mv AS SELECT id, created_at, generated, mcp, active, group_id, session_id FROM public.rubric_drafts_entry WHERE active = true WITH NO DATA;
CREATE MATERIALIZED VIEW public.scenario_drafts_mv AS SELECT id, created_at, generated, mcp, active, group_id, session_id FROM public.scenario_drafts_entry WHERE active = true WITH NO DATA;
CREATE MATERIALIZED VIEW public.setting_drafts_mv AS SELECT id, created_at, generated, mcp, active, group_id, session_id FROM public.setting_drafts_entry WHERE active = true WITH NO DATA;
CREATE MATERIALIZED VIEW public.simulation_drafts_mv AS SELECT id, created_at, generated, mcp, active, group_id, session_id FROM public.simulation_drafts_entry WHERE active = true WITH NO DATA;
CREATE MATERIALIZED VIEW public.tool_drafts_mv AS SELECT id, created_at, generated, mcp, active, group_id, session_id FROM public.tool_drafts_entry WHERE active = true WITH NO DATA;
CREATE UNIQUE INDEX IF NOT EXISTS idx_agent_drafts_mv_id ON public.agent_drafts_mv USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_auth_drafts_mv_id ON public.auth_drafts_mv USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_chat_drafts_mv_id ON public.chat_drafts_mv USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_cohort_drafts_mv_id ON public.cohort_drafts_mv USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_department_drafts_mv_id ON public.department_drafts_mv USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_document_drafts_mv_id ON public.document_drafts_mv USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_eval_drafts_mv_id ON public.eval_drafts_mv USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_field_drafts_mv_id ON public.field_drafts_mv USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_invocation_drafts_mv_id ON public.invocation_drafts_mv USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_model_drafts_mv_id ON public.model_drafts_mv USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_parameter_drafts_mv_id ON public.parameter_drafts_mv USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_persona_drafts_mv_id ON public.persona_drafts_mv USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_profile_drafts_mv_id ON public.profile_drafts_mv USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_provider_drafts_mv_id ON public.provider_drafts_mv USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_rubric_drafts_mv_id ON public.rubric_drafts_mv USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_scenario_drafts_mv_id ON public.scenario_drafts_mv USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_setting_drafts_mv_id ON public.setting_drafts_mv USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_simulation_drafts_mv_id ON public.simulation_drafts_mv USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_tool_drafts_mv_id ON public.tool_drafts_mv USING btree (id);
