-- Foreign keys: primary_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: primary_departments_resource primary_departments_resource_departments_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.primary_departments_resource
    ADD CONSTRAINT primary_departments_resource_departments_id_fkey FOREIGN KEY (departments_id) REFERENCES public.departments_resource(id) ON DELETE CASCADE;


--
