-- Foreign keys: tools_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: tools_resource tools_resource_agent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tools_resource
    ADD CONSTRAINT tools_resource_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents_resource(id) ON DELETE SET NULL;


--

-- Name: tools_resource tools_resource_instruction_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tools_resource
    ADD CONSTRAINT tools_resource_instruction_id_fkey FOREIGN KEY (instruction_id) REFERENCES public.instructions_resource(id) ON DELETE SET NULL;


--
