-- MV indexes: agent_drafts_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: agent_drafts_mv_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX agent_drafts_mv_id_idx ON public.agent_drafts_mv USING btree (id);


--
