-- MV indexes: attempt_chat_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: attempt_chat_mv_chat_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX attempt_chat_mv_chat_id_idx ON public.attempt_chat_mv USING btree (chat_id);


--
