-- MV indexes: attempt_highlight_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: attempt_highlight_mv_highlight_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX attempt_highlight_mv_highlight_id_idx ON public.attempt_highlight_mv USING btree (highlight_id);


--
