-- MV indexes: attempt_replacement_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: attempt_replacement_mv_replacement_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX attempt_replacement_mv_replacement_id_idx ON public.attempt_replacement_mv USING btree (replacement_id);


--
