-- MV indexes: attempt_hint_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: attempt_hint_mv_hint_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX attempt_hint_mv_hint_id_idx ON public.attempt_hint_mv USING btree (hint_id);


--
