-- MV indexes: attempt_improvement_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: attempt_improvement_mv_improvement_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX attempt_improvement_mv_improvement_id_idx ON public.attempt_improvement_mv USING btree (improvement_id);


--
