-- MV indexes: attempt_conversations_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: attempt_conversations_mv_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX attempt_conversations_mv_id_idx ON public.attempt_conversations_mv USING btree (id);


--
