-- MV indexes: attempt_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: attempt_mv_attempt_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX attempt_mv_attempt_id_idx ON public.attempt_mv USING btree (attempt_id);


--

-- Name: attempt_mv_role_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX attempt_mv_role_id_idx ON public.attempt_mv USING btree (role_id);


--
