-- MV indexes: attempt_strength_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: attempt_strength_mv_strength_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX attempt_strength_mv_strength_id_idx ON public.attempt_strength_mv USING btree (strength_id);


--
