-- MV indexes: auth_drafts_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: auth_drafts_mv_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX auth_drafts_mv_id_idx ON public.auth_drafts_mv USING btree (id);


--
