-- MV indexes: chat_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: chat_mv_chat_entry_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX chat_mv_chat_entry_id_idx ON public.chat_mv USING btree (chat_entry_id);


--
