-- MV indexes: chat_drafts_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: chat_drafts_mv_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX chat_drafts_mv_id_idx ON public.chat_drafts_mv USING btree (id);


--
