-- MV indexes: cohort_drafts_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: cohort_drafts_mv_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX cohort_drafts_mv_id_idx ON public.cohort_drafts_mv USING btree (id);


--
