-- MV indexes: department_drafts_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: department_drafts_mv_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX department_drafts_mv_id_idx ON public.department_drafts_mv USING btree (id);


--
