-- MV indexes: document_drafts_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: document_drafts_mv_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX document_drafts_mv_id_idx ON public.document_drafts_mv USING btree (id);


--

-- Name: document_drafts_mv_name_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX document_drafts_mv_name_idx ON public.document_drafts_mv USING btree (lower(name) text_pattern_ops);


--
