-- MV indexes: field_drafts_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: field_drafts_mv_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX field_drafts_mv_id_idx ON public.field_drafts_mv USING btree (id);


--
