-- MV indexes: group_names_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: group_names_mv_group_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX group_names_mv_group_id_idx ON public.group_names_mv USING btree (group_id);


--

-- Name: group_names_mv_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX group_names_mv_id_idx ON public.group_names_mv USING btree (id);


--
