-- MV indexes: invocation_drafts_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: invocation_drafts_mv_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX invocation_drafts_mv_id_idx ON public.invocation_drafts_mv USING btree (id);


--

-- Name: invocation_drafts_mv_name_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX invocation_drafts_mv_name_idx ON public.invocation_drafts_mv USING btree (lower(name) text_pattern_ops);


--
