-- MV indexes: logouts_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: logouts_mv_logout_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX logouts_mv_logout_id_idx ON public.logouts_mv USING btree (logout_id);


--
