-- MV indexes: model_drafts_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: model_drafts_mv_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX model_drafts_mv_id_idx ON public.model_drafts_mv USING btree (id);


--

-- Name: model_drafts_mv_name_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX model_drafts_mv_name_idx ON public.model_drafts_mv USING btree (lower(name) text_pattern_ops);


--
