-- MV indexes: parameter_drafts_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: parameter_drafts_mv_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX parameter_drafts_mv_id_idx ON public.parameter_drafts_mv USING btree (id);


--
