-- MV indexes: persona_drafts_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: persona_drafts_mv_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX persona_drafts_mv_id_idx ON public.persona_drafts_mv USING btree (id);


--
