-- MV indexes: profile_drafts_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: profile_drafts_mv_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX profile_drafts_mv_id_idx ON public.profile_drafts_mv USING btree (id);


--
