-- MV indexes: provider_drafts_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: provider_drafts_mv_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX provider_drafts_mv_id_idx ON public.provider_drafts_mv USING btree (id);


--
