-- MV indexes: refreshes_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: refreshes_mv_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX refreshes_mv_id_idx ON public.refreshes_mv USING btree (id);


--
