-- MV indexes: rubric_drafts_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: rubric_drafts_mv_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX rubric_drafts_mv_id_idx ON public.rubric_drafts_mv USING btree (id);


--

-- Name: rubric_drafts_mv_name_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX rubric_drafts_mv_name_idx ON public.rubric_drafts_mv USING btree (lower(name) text_pattern_ops);


--
