-- MV indexes: scenario_drafts_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: scenario_drafts_mv_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX scenario_drafts_mv_id_idx ON public.scenario_drafts_mv USING btree (id);


--
