-- MV indexes: sessions_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_sessions_mv_session_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_sessions_mv_session_id ON public.sessions_mv USING btree (session_id);


--

-- Name: idx_sessions_mv_profile_created; Type: INDEX; Schema: public; Owner: -
-- report-15 P1: served on every authenticated request (search_sessions by profile_id).
--

CREATE INDEX idx_sessions_mv_profile_created ON public.sessions_mv USING btree (profile_id, session_created_at DESC);


--
