-- MV indexes: setting_drafts_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: setting_drafts_mv_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX setting_drafts_mv_id_idx ON public.setting_drafts_mv USING btree (id);


--

-- Name: setting_drafts_mv_name_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX setting_drafts_mv_name_idx ON public.setting_drafts_mv USING btree (lower(name) text_pattern_ops);


--
