-- MV indexes: simulation_drafts_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: simulation_drafts_mv_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX simulation_drafts_mv_id_idx ON public.simulation_drafts_mv USING btree (id);


--
