-- MV indexes: soft_calls_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_soft_calls_mv_call; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_soft_calls_mv_call ON public.soft_calls_mv USING btree (call_id);


--

-- Name: idx_soft_calls_mv_target; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_soft_calls_mv_target ON public.soft_calls_mv USING btree (artifact, artifact_id, status);


--
