-- MV indexes: test_grade_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: test_grade_mv_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX test_grade_mv_id_idx ON public.test_grade_mv USING btree (id);


--
