-- MV indexes: test_invocation_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: test_invocation_mv_invocation_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX test_invocation_mv_invocation_id_idx ON public.test_invocation_mv USING btree (invocation_id);


--
