-- MV indexes: test_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: test_mv_test_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX test_mv_test_id_idx ON public.test_mv USING btree (test_id);


--
