-- MV indexes: tool_drafts_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: tool_drafts_mv_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX tool_drafts_mv_id_idx ON public.tool_drafts_mv USING btree (id);


--
