-- Indexes: audios_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: audios_resource_active_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audios_resource_active_idx ON public.audios_resource USING btree (active);


--

-- Name: audios_resource_created_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audios_resource_created_at_idx ON public.audios_resource USING btree (created_at);


--

-- Name: audios_resource_name_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audios_resource_name_idx ON public.audios_resource USING btree (name);


--

-- Name: idx_audios_resource_mcp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audios_resource_mcp ON public.audios_resource USING btree (mcp);


--
