-- Indexes: emails_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: emails_email_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX emails_email_idx ON public.emails_resource USING btree (email);


--

-- Name: idx_emails_generated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_emails_generated ON public.emails_resource USING btree (generated);


--

-- Name: idx_emails_mcp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_emails_mcp ON public.emails_resource USING btree (mcp);


--

-- Name: idx_emails_resource_lower_email; Type: INDEX; Schema: public; Owner: -
-- report-15 P4: serves the case-insensitive auth-path email lookup.
--

CREATE INDEX idx_emails_resource_lower_email ON public.emails_resource USING btree (LOWER(email));


--
