-- Indexes: primary_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_primary_departments_resource_departments_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_primary_departments_resource_departments_id ON public.primary_departments_resource USING btree (departments_id);


--
