-- Indexes: migration_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_migration_tracking_number; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_migration_tracking_number ON public.migration_tracking USING btree (migration_number DESC);


--

-- Name: idx_migration_tracking_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_migration_tracking_type ON public.migration_tracking USING btree (migration_type);


--
