-- Table definitions + constraints: migration_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: migration_tracking; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.migration_tracking (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    migration_number integer NOT NULL,
    migration_file character varying(255) NOT NULL,
    migration_type character varying(10) NOT NULL,
    applied_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    applied_by character varying(255),
    CONSTRAINT migration_tracking_migration_type_check CHECK (((migration_type)::text = ANY ((ARRAY['add'::character varying, 'remove'::character varying])::text[])))
);


--

-- Name: migration_tracking migration_tracking_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.migration_tracking
    ADD CONSTRAINT migration_tracking_pkey PRIMARY KEY (id);


--

-- Name: migration_tracking migration_tracking_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.migration_tracking
    ADD CONSTRAINT migration_tracking_unique UNIQUE (migration_number, migration_type);


--
