-- Table definitions + constraints: images_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: images_images_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.images_images_connection (
    image_id uuid NOT NULL,
    images_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--

-- Name: images_qualities_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.images_qualities_connection (
    image_id uuid NOT NULL,
    quality_id uuid NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--

-- Name: images_images_connection images_images_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.images_images_connection
    ADD CONSTRAINT images_images_connection_pkey PRIMARY KEY (image_id, images_id);


--

-- Name: images_qualities_connection images_qualities_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.images_qualities_connection
    ADD CONSTRAINT images_qualities_connection_pkey PRIMARY KEY (image_id, quality_id);


--
