-- Table definitions + constraints: personas_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: personas_personas_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.personas_personas_connection (
    personas_entry_id uuid NOT NULL,
    personas_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--

-- Name: personas_personas_connection personas_personas_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personas_personas_connection
    ADD CONSTRAINT personas_personas_connection_pkey PRIMARY KEY (personas_entry_id, personas_id);


--
