-- Table definitions + constraints: videos_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: videos_videos_connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.videos_videos_connection (
    video_id uuid NOT NULL,
    videos_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--

-- Name: videos_videos_connection videos_videos_connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.videos_videos_connection
    ADD CONSTRAINT videos_videos_connection_pkey PRIMARY KEY (video_id, videos_id);


--
