<#-- Custom head.ftl for Glow theme -->
<#-- This file is included by Keycloak's base template.ftl -->

<#-- Geist font from Google Fonts (matching Next.js app) -->
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Geist:wght@400;500;600;700&display=swap" rel="stylesheet" />

<#-- Favicon (SVG for modern browsers) -->
<link rel="icon" href="${url.resourcesPath}/favicon.svg" type="image/svg+xml" />

<#-- Favicon fallbacks (PNG and ICO for older browsers) -->
<link rel="icon" href="${url.resourcesPath}/img/favicon.png" type="image/png" sizes="512x512" />
<link rel="shortcut icon" href="${url.resourcesPath}/img/favicon.ico" />

<#-- Theme CSS variables — generated by app.infra.identity.keycloak_theme.
     Defines :root tokens (light) plus a prefers-color-scheme dark block.
     Loaded BEFORE styles.css so styles.css's var() consumers (gradient,
     sparkles, primary button) pick up the active palette. Static .css
     file rather than a FreeMarker include — Keycloak's template loader
     can fail to resolve relative includes from head.ftl when head.ftl
     is invoked through the inherited template.ftl. -->
<link rel="stylesheet" href="${url.resourcesPath}/css/theme-vars.css" />
