-- Materialized view: agent_drafts_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: agent_drafts_mv; Type: MATERIALIZED VIEW; Schema: public; Owner: -
--

CREATE MATERIALIZED VIEW public.agent_drafts_mv AS
 SELECT id,
    created_at,
    generated,
    mcp,
    active,
    session_id,
    name
   FROM public.agent_drafts_entry
  WHERE (active = true)
  WITH NO DATA;


--
