-- Materialized view: attempt_replacement_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: attempt_replacement_mv; Type: MATERIALIZED VIEW; Schema: public; Owner: -
--

CREATE MATERIALIZED VIEW public.attempt_replacement_mv AS
 SELECT rp.id AS replacement_id,
    rp.improvement_id,
    rp.section,
    rp.replace,
    rp.created_at
   FROM (((((public.attempt_replacement_entry rp
     JOIN public.attempt_improvement_entry i ON ((i.id = rp.improvement_id)))
     JOIN public.attempt_message_entry sm ON ((sm.id = i.message_id)))
     JOIN public.attempt_chat_entry c ON ((c.id = sm.chat_id)))
     JOIN public.attempt_chat_bridge_entry ac ON ((ac.attempt_chat_id = c.id)))
     JOIN public.attempt_entry a ON ((a.id = ac.attempt_id)))
  WHERE ((rp.active = true) AND (i.active = true) AND (c.active = true) AND (a.active = true))
  WITH NO DATA;


--
