-- Materialized view: attempt_highlight_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: attempt_highlight_mv; Type: MATERIALIZED VIEW; Schema: public; Owner: -
--

CREATE MATERIALIZED VIEW public.attempt_highlight_mv AS
 SELECT hl.id AS highlight_id,
    hl.strength_id,
    hl.section,
    hl.idx,
    hl.created_at
   FROM (((((public.attempt_highlight_entry hl
     JOIN public.attempt_strength_entry s ON ((s.id = hl.strength_id)))
     JOIN public.attempt_message_entry sm ON ((sm.id = s.message_id)))
     JOIN public.attempt_chat_entry c ON ((c.id = sm.chat_id)))
     JOIN public.attempt_chat_bridge_entry ac ON ((ac.attempt_chat_id = c.id)))
     JOIN public.attempt_entry a ON ((a.id = ac.attempt_id)))
  WHERE ((hl.active = true) AND (s.active = true) AND (c.active = true) AND (a.active = true))
  WITH NO DATA;


--
