-- Materialized view: attempt_hint_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: attempt_hint_mv; Type: MATERIALIZED VIEW; Schema: public; Owner: -
--

CREATE MATERIALIZED VIEW public.attempt_hint_mv AS
 SELECT h.id AS hint_id,
    h.message_id,
    h.hint,
    h.created_at
   FROM ((((public.attempt_hint_entry h
     JOIN public.attempt_message_entry sm ON ((sm.id = h.message_id)))
     JOIN public.attempt_chat_entry c ON ((c.id = sm.chat_id)))
     JOIN public.attempt_chat_bridge_entry ac ON ((ac.attempt_chat_id = c.id)))
     JOIN public.attempt_entry a ON ((a.id = ac.attempt_id)))
  WHERE ((h.active = true) AND (c.active = true) AND (a.active = true))
  WITH NO DATA;


--
