-- Materialized view: attempt_improvement_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: attempt_improvement_mv; Type: MATERIALIZED VIEW; Schema: public; Owner: -
--

CREATE MATERIALIZED VIEW public.attempt_improvement_mv AS
 SELECT i.id AS improvement_id,
    i.message_id,
    i.name,
    i.description,
    i.created_at
   FROM ((((public.attempt_improvement_entry i
     JOIN public.attempt_message_entry sm ON ((sm.id = i.message_id)))
     JOIN public.attempt_chat_entry c ON ((c.id = sm.chat_id)))
     JOIN public.attempt_chat_bridge_entry ac ON ((ac.attempt_chat_id = c.id)))
     JOIN public.attempt_entry a ON ((a.id = ac.attempt_id)))
  WHERE ((i.active = true) AND (c.active = true) AND (a.active = true))
  WITH NO DATA;


--
