-- Materialized view: group_names_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: group_names_mv; Type: MATERIALIZED VIEW; Schema: public; Owner: -
--

CREATE MATERIALIZED VIEW public.group_names_mv AS
 SELECT DISTINCT ON (group_id) id,
    group_id,
    name,
    created_at,
    generated,
    mcp
   FROM public.group_names_entry gn
  WHERE (active = true)
  ORDER BY group_id, created_at DESC
  WITH NO DATA;


--
