-- Materialized view: groups_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: groups_mv; Type: MATERIALIZED VIEW; Schema: public; Owner: -
--

CREATE MATERIALIZED VIEW public.groups_mv AS
 SELECT g.id AS group_id,
    g.session_id,
    g.created_at,
    COALESCE(gn.name, ''::text) AS name,
    g.active,
    g.mcp,
    g.generated,
    g.artifact_type
   FROM (public.groups_entry g
     LEFT JOIN public.group_names_mv gn ON ((gn.group_id = g.id)))
  WHERE (g.active = true)
  WITH NO DATA;


--
