-- Materialized view: logouts_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: logouts_mv; Type: MATERIALIZED VIEW; Schema: public; Owner: -
--

CREATE MATERIALIZED VIEW public.logouts_mv AS
 SELECT l.id AS logout_id,
    plc.profiles_id AS profile_id,
    l.session_id,
    l.created_at,
    l.active,
    l.mcp,
    l.generated
   FROM (public.logouts_entry l
     LEFT JOIN public.profiles_logouts_connection plc ON (((plc.logout_id = l.id) AND (plc.active = true))))
  WITH NO DATA;


--
