-- Materialized view: refresh_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: refresh_mv; Type: MATERIALIZED VIEW; Schema: public; Owner: -
--

CREATE MATERIALIZED VIEW public.refresh_mv AS
 SELECT id,
    operation_key,
    artifact_type,
    target,
    session_id,
    created_at,
    active,
    generated,
    mcp
   FROM public.refresh_entry r
  WHERE (active = true)
  WITH NO DATA;


--
