-- Materialized view: soft_calls_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: soft_calls_mv; Type: MATERIALIZED VIEW; Schema: public; Owner: -
--

CREATE MATERIALIZED VIEW public.soft_calls_mv AS
 SELECT DISTINCT ON (call_id) id AS soft_call_entry_id,
    call_id,
    artifact,
    operation,
    status,
    artifact_id,
    patch,
    created_at
   FROM public.soft_calls_entry s
  WHERE (active = true)
  ORDER BY call_id, created_at DESC
  WITH NO DATA;


--
