-- Materialized view: test_invocation_traces_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: test_invocation_traces_mv; Type: MATERIALIZED VIEW; Schema: public; Owner: -
--

CREATE MATERIALIZED VIEW public.test_invocation_traces_mv AS
 SELECT e.id,
    e.test_invocation_id,
    e.run_id,
    e.created_at,
    e.updated_at,
    e.generated,
    e.mcp,
    e.active,
    COALESCE(array_agg(DISTINCT rlc.reasoning_levels_id) FILTER (WHERE (rlc.reasoning_levels_id IS NOT NULL)), ARRAY[]::uuid[]) AS reasoning_level_ids,
    COALESCE(array_agg(DISTINCT tlc.temperature_levels_id) FILTER (WHERE (tlc.temperature_levels_id IS NOT NULL)), ARRAY[]::uuid[]) AS temperature_level_ids,
    COALESCE(array_agg(DISTINCT vc.voices_id) FILTER (WHERE (vc.voices_id IS NOT NULL)), ARRAY[]::uuid[]) AS voice_ids,
    COALESCE(array_agg(DISTINCT pc.prompts_id) FILTER (WHERE (pc.prompts_id IS NOT NULL)), ARRAY[]::uuid[]) AS prompt_ids,
    COALESCE(array_agg(DISTINCT ic.instructions_id) FILTER (WHERE (ic.instructions_id IS NOT NULL)), ARRAY[]::uuid[]) AS instruction_ids,
    COALESCE(array_agg(DISTINCT tc.tools_id) FILTER (WHERE (tc.tools_id IS NOT NULL)), ARRAY[]::uuid[]) AS tool_ids,
    COALESCE(array_agg(DISTINCT qc.qualities_id) FILTER (WHERE (qc.qualities_id IS NOT NULL)), ARRAY[]::uuid[]) AS quality_ids,
    COALESCE(array_agg(DISTINCT mc.modalities_id) FILTER (WHERE (mc.modalities_id IS NOT NULL)), ARRAY[]::uuid[]) AS modality_ids
   FROM ((((((((public.test_invocation_traces_entry e
     LEFT JOIN public.test_invocation_traces_reasoning_levels_connection rlc ON (((rlc.test_invocation_traces_id = e.id) AND (rlc.active = true))))
     LEFT JOIN public.test_invocation_traces_temperature_levels_connection tlc ON (((tlc.test_invocation_traces_id = e.id) AND (tlc.active = true))))
     LEFT JOIN public.test_invocation_traces_voices_connection vc ON (((vc.test_invocation_traces_id = e.id) AND (vc.active = true))))
     LEFT JOIN public.test_invocation_traces_prompts_connection pc ON (((pc.test_invocation_traces_id = e.id) AND (pc.active = true))))
     LEFT JOIN public.test_invocation_traces_instructions_connection ic ON (((ic.test_invocation_traces_id = e.id) AND (ic.active = true))))
     LEFT JOIN public.test_invocation_traces_tools_connection tc ON (((tc.test_invocation_traces_id = e.id) AND (tc.active = true))))
     LEFT JOIN public.test_invocation_traces_qualities_connection qc ON (((qc.test_invocation_traces_id = e.id) AND (qc.active = true))))
     LEFT JOIN public.test_invocation_traces_modalities_connection mc ON (((mc.test_invocation_traces_id = e.id) AND (mc.active = true))))
  WHERE (e.active = true)
  GROUP BY e.id, e.test_invocation_id, e.run_id, e.created_at, e.updated_at, e.generated, e.mcp, e.active
  WITH NO DATA;


--
