-- Materialized view: test_invocation_runs_mv
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: test_invocation_runs_mv; Type: MATERIALIZED VIEW; Schema: public; Owner: -
--

CREATE MATERIALIZED VIEW public.test_invocation_runs_mv AS
 SELECT id,
    test_invocation_id,
    test_invocation_traces_id,
    run_id,
    created_at,
    updated_at,
    generated,
    mcp,
    active
   FROM public.test_invocation_runs_entry e
  WHERE (active = true)
  WITH NO DATA;


--
