#!/bin/bash
# Generate docker-compose.override.yml for deployment provisioning.
#
# Handles two modes:
#   Exposed (default): Traefik routing + deployment network + server aliases
#   Airgapped:         Deployment network + server aliases only (no Traefik, no public URL)
#
# Usage:
#   ./scripts/provision.sh deploy --name <id> --subdomain <sub> --base-domain <domain> --compose-dir <dir> --entry-service <svc> --entry-port <port>
#   ./scripts/provision.sh deploy --name <id> --compose-dir <dir> --airgapped
#   ./scripts/provision.sh teardown --name <name> --compose-dir <dir>

set -e

COMMAND="${1:?Usage: $0 <deploy|teardown> [options]}"
shift

AIRGAPPED=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --name) NAME="$2"; shift 2 ;;
    --subdomain) SUBDOMAIN="$2"; shift 2 ;;
    --base-domain) BASE_DOMAIN="$2"; shift 2 ;;
    --compose-dir) COMPOSE_DIR="$2"; shift 2 ;;
    --entry-service) ENTRY_SERVICE="$2"; shift 2 ;;
    --entry-port) ENTRY_PORT="$2"; shift 2 ;;
    --airgapped) AIRGAPPED=true; shift ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

case "$COMMAND" in
  deploy)
    : "${NAME:?--name required}"
    : "${COMPOSE_DIR:?--compose-dir required}"

    # Deployment network (shared between server + clients)
    DEPLOY_NETWORK="glow-${NAME}"
    docker network create "$DEPLOY_NETWORK" 2>/dev/null || true

    cd "$COMPOSE_DIR"
    rm -f docker-compose.override.yml

    # Discover services
    SERVICES=$(docker compose config --services 2>/dev/null || echo "${ENTRY_SERVICE:-nginx}")

    # Build server network entries (glow-api alias for client access)
    SERVER_ENTRIES=""
    for svc in $SERVICES; do
      case "$svc" in
        server-blue|server-green)
          SERVER_ENTRIES="${SERVER_ENTRIES}
  ${svc}:
    networks:
      deployment:
        aliases:
        - glow-api"
          ;;
      esac
    done

    if [ "$AIRGAPPED" = true ]; then
      # ── Airgapped: deployment network only, no Traefik ──
      cat > "$COMPOSE_DIR/docker-compose.override.yml" <<OVERRIDE
# Auto-generated by provision.sh (airgapped) -- do not edit manually
services:${SERVER_ENTRIES}
networks:
  deployment:
    external: true
    name: ${DEPLOY_NETWORK}
OVERRIDE
      echo "Airgapped override generated (no public URL, network: ${DEPLOY_NETWORK})"

    else
      # ── Exposed: Traefik routing + deployment network ──
      : "${SUBDOMAIN:?--subdomain required for exposed mode}"
      : "${BASE_DOMAIN:?--base-domain required for exposed mode}"
      : "${ENTRY_SERVICE:?--entry-service required for exposed mode}"
      : "${ENTRY_PORT:?--entry-port required for exposed mode}"

      DOMAIN="${SUBDOMAIN}.${BASE_DOMAIN}"
      docker network create traefik_routing 2>/dev/null || true

      # Build extra_hosts for non-entry services
      EXTRA_HOSTS_ENTRIES=""
      for svc in $SERVICES; do
        [ "$svc" = "$ENTRY_SERVICE" ] && continue
        # Skip if already in SERVER_ENTRIES (server-blue/green)
        case "$svc" in
          server-blue|server-green) continue ;;
        esac
        EXTRA_HOSTS_ENTRIES="${EXTRA_HOSTS_ENTRIES}
  ${svc}:
    extra_hosts:
    - ${DOMAIN}:host-gateway"
      done

      # Server entries need both extra_hosts AND deployment network
      SERVER_WITH_HOSTS=""
      for svc in $SERVICES; do
        case "$svc" in
          server-blue|server-green)
            SERVER_WITH_HOSTS="${SERVER_WITH_HOSTS}
  ${svc}:
    extra_hosts:
    - ${DOMAIN}:host-gateway
    networks:
      deployment:
        aliases:
        - glow-api"
            ;;
        esac
      done

      cat > "$COMPOSE_DIR/docker-compose.override.yml" <<OVERRIDE
# Auto-generated by provision.sh -- do not edit manually
services:
  ${ENTRY_SERVICE}:
    networks:
    - traefik_routing
    labels:
    - traefik.enable=true
    - traefik.http.routers.${NAME}.rule=Host(\`${DOMAIN}\`)
    - traefik.http.routers.${NAME}.entrypoints=websecure
    - traefik.http.routers.${NAME}.tls.certresolver=letsencrypt
    - traefik.http.routers.${NAME}.middlewares=secure-public@file
    - traefik.http.services.${NAME}.loadbalancer.server.port=${ENTRY_PORT}
    - traefik.docker.network=traefik_routing
    security_opt:
    - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
    extra_hosts:
    - ${DOMAIN}:host-gateway${SERVER_WITH_HOSTS}${EXTRA_HOSTS_ENTRIES}
networks:
  traefik_routing:
    external: true
    name: traefik_routing
  deployment:
    external: true
    name: ${DEPLOY_NETWORK}
OVERRIDE
      echo "Traefik override generated for ${DOMAIN} → ${ENTRY_SERVICE}:${ENTRY_PORT} (network: ${DEPLOY_NETWORK})"
    fi
    ;;

  teardown)
    : "${NAME:?--name required}"
    : "${COMPOSE_DIR:?--compose-dir required}"

    cd "$COMPOSE_DIR"
    docker compose down -v --remove-orphans 2>/dev/null || true
    rm -f docker-compose.override.yml

    # Clean up deployment network
    docker network rm "glow-${NAME}" 2>/dev/null || true

    echo "Teardown complete for $NAME"
    ;;

  *)
    echo "Unknown command: $COMMAND (use deploy or teardown)"
    exit 1
    ;;
esac
