-- Indexes: calls_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: calls_external_call_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX calls_external_call_id_idx ON public.calls_entry USING btree (external_call_id);


--

-- Name: idx_calls_entry_session_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_calls_entry_session_id ON public.calls_entry USING btree (session_id);


--

-- Name: idx_calls_run_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_calls_run_id ON public.calls_entry USING btree (run_id);


--

-- Name: tool_calls_created_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tool_calls_created_at_idx ON public.calls_entry USING btree (created_at);


--

-- Name: idx_calls_entry_operation_key; Type: INDEX; Schema: public; Owner: -
-- Idempotency replay gate — base-table lookup on operation_key.
-- Mirrors database/migrate/add/20260520_add_operation_key_indexes.sql so fresh
-- (schema.sql) deploys match migrated instances. Keep the two in sync.
--

CREATE INDEX idx_calls_entry_operation_key ON public.calls_entry USING btree (operation_key);


--
