-- Indexes: group_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_group_names_entry_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_group_names_entry_created_at ON public.group_names_entry USING btree (created_at);


--

-- Name: idx_group_names_entry_group_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_group_names_entry_group_id ON public.group_names_entry USING btree (group_id);


--
