-- Indexes: logouts_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_logouts_entry_generated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_logouts_entry_generated ON public.logouts_entry USING btree (generated);


--

-- Name: idx_logouts_entry_mcp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_logouts_entry_mcp ON public.logouts_entry USING btree (mcp);


--

-- Name: logouts_entry_session_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX logouts_entry_session_id_idx ON public.logouts_entry USING btree (session_id);


--
