-- Indexes: refreshes_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_refreshes_entry_operation_key; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_refreshes_entry_operation_key ON public.refreshes_entry USING btree (operation_key);


--

-- Name: idx_refreshes_entry_target_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_refreshes_entry_target_created ON public.refreshes_entry USING btree (target, created_at DESC);


--
