-- Indexes: soft_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: idx_soft_calls_entry_call_lookup; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_soft_calls_entry_call_lookup ON public.soft_calls_entry USING btree (call_id, created_at DESC);


--

-- Name: idx_soft_calls_entry_target_lookup; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_soft_calls_entry_target_lookup ON public.soft_calls_entry USING btree (artifact, artifact_id, status);


--
