-- Table definitions + constraints: tool_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: tool_agents_junction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tool_agents_junction (
    tool_id uuid NOT NULL,
    agents_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--

-- Name: tool_arg_positions_junction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tool_arg_positions_junction (
    tool_id uuid NOT NULL,
    arg_positions_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--

-- Name: tool_args_junction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tool_args_junction (
    tool_id uuid CONSTRAINT tool_args_tool_id_not_null NOT NULL,
    args_id uuid CONSTRAINT tool_args_args_id_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT tool_args_created_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT tool_args_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT tool_args_mcp_not_null NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: tool_args_outputs_junction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tool_args_outputs_junction (
    tool_id uuid CONSTRAINT tool_args_outputs_tool_id_not_null NOT NULL,
    args_outputs_id uuid CONSTRAINT tool_args_outputs_args_outputs_id_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT tool_args_outputs_created_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT tool_args_outputs_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT tool_args_outputs_mcp_not_null NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--

-- Name: tool_departments_junction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tool_departments_junction (
    tool_id uuid CONSTRAINT tool_departments_tool_id_not_null NOT NULL,
    departments_id uuid CONSTRAINT tool_departments_department_id_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT tool_departments_active_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT tool_departments_created_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT tool_departments_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT tool_departments_mcp_not_null NOT NULL
);


--

-- Name: tool_descriptions_junction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tool_descriptions_junction (
    tool_id uuid CONSTRAINT tool_descriptions_tool_id_not_null NOT NULL,
    descriptions_id uuid CONSTRAINT tool_descriptions_description_id_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT tool_descriptions_created_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT tool_descriptions_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT tool_descriptions_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT tool_descriptions_active_not_null NOT NULL
);


--

-- Name: tool_flags_junction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tool_flags_junction (
    tool_id uuid CONSTRAINT tool_flags_tool_id_not_null NOT NULL,
    flags_id uuid CONSTRAINT tool_flags_flag_id_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT tool_flags_created_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT tool_flags_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT tool_flags_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT tool_flags_active_not_null NOT NULL
);


--

-- Name: tool_instructions_junction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tool_instructions_junction (
    tool_id uuid NOT NULL,
    instructions_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--

-- Name: tool_names_junction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tool_names_junction (
    tool_id uuid CONSTRAINT tool_names_tool_id_not_null NOT NULL,
    names_id uuid CONSTRAINT tool_names_name_id_not_null NOT NULL,
    created_at timestamp with time zone DEFAULT now() CONSTRAINT tool_names_created_at_not_null NOT NULL,
    generated boolean DEFAULT false CONSTRAINT tool_names_generated_not_null NOT NULL,
    mcp boolean DEFAULT false CONSTRAINT tool_names_mcp_not_null NOT NULL,
    active boolean DEFAULT true CONSTRAINT tool_names_active_not_null NOT NULL
);


--

-- Name: tool_permissions_junction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tool_permissions_junction (
    tool_id uuid NOT NULL,
    permissions_id uuid NOT NULL,
    active boolean DEFAULT true NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--

-- Name: tool_tools_junction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tool_tools_junction (
    tool_id uuid NOT NULL,
    tools_id uuid NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    generated boolean DEFAULT false NOT NULL,
    mcp boolean DEFAULT false NOT NULL
);


--

-- Name: tool_agents_junction tool_agents_junction_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_agents_junction
    ADD CONSTRAINT tool_agents_junction_pkey PRIMARY KEY (tool_id, agents_id);


--

-- Name: tool_arg_positions_junction tool_arg_positions_junction_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_arg_positions_junction
    ADD CONSTRAINT tool_arg_positions_junction_pkey PRIMARY KEY (tool_id, arg_positions_id);


--

-- Name: tool_args_outputs_junction tool_args_outputs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_args_outputs_junction
    ADD CONSTRAINT tool_args_outputs_pkey PRIMARY KEY (tool_id, args_outputs_id);


--

-- Name: tool_args_junction tool_args_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_args_junction
    ADD CONSTRAINT tool_args_pkey PRIMARY KEY (tool_id, args_id);


--

-- Name: tool_departments_junction tool_departments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_departments_junction
    ADD CONSTRAINT tool_departments_pkey PRIMARY KEY (tool_id, departments_id);


--

-- Name: tool_descriptions_junction tool_descriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_descriptions_junction
    ADD CONSTRAINT tool_descriptions_pkey PRIMARY KEY (tool_id, descriptions_id);


--

-- Name: tool_flags_junction tool_flags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_flags_junction
    ADD CONSTRAINT tool_flags_pkey PRIMARY KEY (tool_id, flags_id);


--

-- Name: tool_instructions_junction tool_instructions_junction_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_instructions_junction
    ADD CONSTRAINT tool_instructions_junction_pkey PRIMARY KEY (tool_id, instructions_id);


--

-- Name: tool_names_junction tool_names_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_names_junction
    ADD CONSTRAINT tool_names_pkey PRIMARY KEY (tool_id, names_id);


--

-- Name: tool_permissions_junction tool_permissions_junction_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_permissions_junction
    ADD CONSTRAINT tool_permissions_junction_pkey PRIMARY KEY (tool_id, permissions_id);


--

-- Name: tool_tools_junction tool_tools_junction_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_tools_junction
    ADD CONSTRAINT tool_tools_junction_pkey PRIMARY KEY (tool_id, tools_id);


--
