-- Enum: operation_type_new
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: operation_type_new; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.operation_type_new AS ENUM (
    'get',
    'search',
    'create',
    'update',
    'delete',
    'duplicate',
    'draft',
    'drafts',
    'export',
    'refresh',
    'docs',
    'csv',
    'start',
    'next',
    'end',
    'end_all',
    'message',
    'grade',
    'stop',
    'response',
    'previous',
    'archive',
    'image_upload',
    'image_download',
    'video_upload',
    'video_download',
    'text_upload',
    'text_download',
    'file_upload',
    'file_download',
    'file_preview',
    'audio_start',
    'audio_frame',
    'audio_stop',
    'audio_mute',
    'audio_upload',
    'audio_download',
    'call_download',
    'run',
    'generate',
    'problem',
    'resolve',
    'emulate',
    'unemulate',
    'context',
    'decrypt'
);


--
