-- Foreign keys: audios_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: audios_audios_connection audios_audios_connection_audio_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audios_audios_connection
    ADD CONSTRAINT audios_audios_connection_audio_id_fkey FOREIGN KEY (audio_id) REFERENCES public.audios_entry(id) ON DELETE CASCADE;


--

-- Name: audios_audios_connection audios_audios_connection_audios_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audios_audios_connection
    ADD CONSTRAINT audios_audios_connection_audios_id_fkey FOREIGN KEY (audios_id) REFERENCES public.audios_resource(id);


--

-- Name: audios_voices_connection audios_voices_connection_audio_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audios_voices_connection
    ADD CONSTRAINT audios_voices_connection_audio_id_fkey FOREIGN KEY (audio_id) REFERENCES public.audios_entry(id) ON DELETE CASCADE;


--

-- Name: audios_voices_connection audios_voices_connection_voice_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audios_voices_connection
    ADD CONSTRAINT audios_voices_connection_voice_id_fkey FOREIGN KEY (voice_id) REFERENCES public.voices_resource(id) ON DELETE CASCADE;


--
