-- Foreign keys: tool_*
-- Auto-generated by split_schema.py — do not edit manually
--

-- Name: tool_agents_junction tool_agents_agents_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_agents_junction
    ADD CONSTRAINT tool_agents_agents_id_fkey FOREIGN KEY (agents_id) REFERENCES public.agents_resource(id) ON DELETE CASCADE;


--

-- Name: tool_agents_junction tool_agents_tool_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_agents_junction
    ADD CONSTRAINT tool_agents_tool_id_fkey FOREIGN KEY (tool_id) REFERENCES public.tool_artifact(id) ON DELETE CASCADE;


--

-- Name: tool_arg_positions_junction tool_arg_positions_junction_arg_positions_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_arg_positions_junction
    ADD CONSTRAINT tool_arg_positions_junction_arg_positions_id_fkey FOREIGN KEY (arg_positions_id) REFERENCES public.arg_positions_resource(id) ON DELETE CASCADE;


--

-- Name: tool_arg_positions_junction tool_arg_positions_junction_tool_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_arg_positions_junction
    ADD CONSTRAINT tool_arg_positions_junction_tool_id_fkey FOREIGN KEY (tool_id) REFERENCES public.tool_artifact(id) ON DELETE CASCADE;


--

-- Name: tool_args_junction tool_args_args_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_args_junction
    ADD CONSTRAINT tool_args_args_id_fkey FOREIGN KEY (args_id) REFERENCES public.args_resource(id) ON DELETE CASCADE;


--

-- Name: tool_args_outputs_junction tool_args_outputs_tool_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_args_outputs_junction
    ADD CONSTRAINT tool_args_outputs_tool_id_fkey FOREIGN KEY (tool_id) REFERENCES public.tool_artifact(id) ON DELETE CASCADE;


--

-- Name: tool_args_junction tool_args_tool_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_args_junction
    ADD CONSTRAINT tool_args_tool_id_fkey FOREIGN KEY (tool_id) REFERENCES public.tool_artifact(id) ON DELETE CASCADE;


--

-- Name: tool_departments_junction tool_departments_department_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_departments_junction
    ADD CONSTRAINT tool_departments_department_id_fkey FOREIGN KEY (departments_id) REFERENCES public.departments_resource(id);


--

-- Name: tool_departments_junction tool_departments_tool_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_departments_junction
    ADD CONSTRAINT tool_departments_tool_id_fkey FOREIGN KEY (tool_id) REFERENCES public.tool_artifact(id) ON DELETE CASCADE;


--

-- Name: tool_descriptions_junction tool_descriptions_description_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_descriptions_junction
    ADD CONSTRAINT tool_descriptions_description_id_fkey FOREIGN KEY (descriptions_id) REFERENCES public.descriptions_resource(id) ON DELETE CASCADE;


--

-- Name: tool_descriptions_junction tool_descriptions_tool_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_descriptions_junction
    ADD CONSTRAINT tool_descriptions_tool_id_fkey FOREIGN KEY (tool_id) REFERENCES public.tool_artifact(id) ON DELETE CASCADE;


--

-- Name: tool_flags_junction tool_flags_flag_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_flags_junction
    ADD CONSTRAINT tool_flags_flag_id_fkey FOREIGN KEY (flags_id) REFERENCES public.flags_resource(id) ON DELETE CASCADE;


--

-- Name: tool_flags_junction tool_flags_tool_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_flags_junction
    ADD CONSTRAINT tool_flags_tool_id_fkey FOREIGN KEY (tool_id) REFERENCES public.tool_artifact(id) ON DELETE CASCADE;


--

-- Name: tool_instructions_junction tool_instructions_instructions_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_instructions_junction
    ADD CONSTRAINT tool_instructions_instructions_id_fkey FOREIGN KEY (instructions_id) REFERENCES public.instructions_resource(id) ON DELETE CASCADE;


--

-- Name: tool_instructions_junction tool_instructions_tool_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_instructions_junction
    ADD CONSTRAINT tool_instructions_tool_id_fkey FOREIGN KEY (tool_id) REFERENCES public.tool_artifact(id) ON DELETE CASCADE;


--

-- Name: tool_names_junction tool_names_name_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_names_junction
    ADD CONSTRAINT tool_names_name_id_fkey FOREIGN KEY (names_id) REFERENCES public.names_resource(id) ON DELETE CASCADE;


--

-- Name: tool_names_junction tool_names_tool_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_names_junction
    ADD CONSTRAINT tool_names_tool_id_fkey FOREIGN KEY (tool_id) REFERENCES public.tool_artifact(id) ON DELETE CASCADE;


--

-- Name: tool_permissions_junction tool_permissions_junction_tool_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_permissions_junction
    ADD CONSTRAINT tool_permissions_junction_tool_id_fkey FOREIGN KEY (tool_id) REFERENCES public.tool_artifact(id) ON DELETE CASCADE;


--

-- Name: tool_tools_junction tool_tools_tool_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_tools_junction
    ADD CONSTRAINT tool_tools_tool_id_fkey FOREIGN KEY (tool_id) REFERENCES public.tool_artifact(id) ON DELETE CASCADE;


--

-- Name: tool_tools_junction tool_tools_tools_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_tools_junction
    ADD CONSTRAINT tool_tools_tools_id_fkey FOREIGN KEY (tools_id) REFERENCES public.tools_resource(id) ON DELETE CASCADE;


--
