name: Halt

on:
  workflow_dispatch:
    inputs:
      deployment_id:
        description: 'Deployment UUID'
        required: true

jobs:
  stop:
    runs-on: self-hosted
    env:
      DEPLOY_DIR: /srv/deploy/live/glow/${{ inputs.deployment_id }}
      COMPOSE_PROJECT_NAME: ${{ inputs.deployment_id }}
    steps:
      - name: Stop containers
        run: |
          if [ -d "${{ env.DEPLOY_DIR }}" ]; then
            cd "${{ env.DEPLOY_DIR }}"
            export COMPOSE_PROJECT_NAME="${{ inputs.deployment_id }}"
            docker compose stop
            echo "Containers stopped."
          else
            echo "Deployment directory not found."
          fi
