"""Input: attempt.* events."""

from . import (  # noqa: F401
    audio_download,
    audio_mute,
    audio_start,
    audio_stop,
    audio_upload,
    end,
    end_all,
    export,
    file_download,
    file_preview,
    generate,
    generations,
    get,
    grade,
    group,
    image_download,
    join,
    leave,
    message,
    next,
    problem,
    refresh,
    response,
    search,
    start,
    stop,
    text_download,
    use_previous,
    video_download,
    # Absorbed sub-modules
    dashboard,
    home,
    leaderboard,
    practice,
    record,
    reports,
)
